### ISSUE TITLE
Typo in FAQ

### ISSUE THREAD

**Issue by HotCakeX** [mullvad/mullvad-browser#10]
https://mullvad.net/en/help/tag/mullvad-browser/

![image](https://user-images.githubusercontent.com/118815227/229606154-88d6e974-6df5-4328-88d3-2c795607cda6.png)

**Comment by ruihildt** [comment]
Thanks, we will fix it as soon as possible.

**Comment by eonrider** [comment]
There are actually two errors there:

1. The question is grammatically incorrect.
2. "Time zone" is two words.

**Comment by ruihildt** [comment]
> 2\. "Time zone" is two words.

Thanks, will fix.
