### ISSUE TITLE
/

### ISSUE THREAD

**Issue by thisisauser9** [mullvad/mullvad-browser#102]

**Comment by ruihildt** [comment]
As it happens, I also use Fedora 38 KDE spin.

Can you try watching the same content in regular Firefox?

I don't encounter this error, maybe you need to install the codecs?
I remember having done something similar when I first installed Fedora.

See: https://docs.fedoraproject.org/en-US/quick-docs/assembly_installing-plugins-for-playing-movies-and-music/

**Comment by BeyondThe5D** [comment]
Yeah I thought the issue was related to that, but whenever I installed them, the error message would change to "The media could not be loaded, either because the server or network failed or because the format is not supported."

**Comment by ruihildt** [comment]
Can you try on regular Firefox and in Tor Browser to see of it works there?

**Comment by BeyondThe5D** [comment]
It works on Firefox but not Tor Browser

**Comment by BeyondThe5D** [comment]
I don't think it's just a specific website issue, it happens on multiple sites, even the bigger websites

**Comment by ruihildt** [comment]
This tag is just to indicate that it breaks a (or multiple) website experience.

**Comment by BeyondThe5D** [comment]
Oh ok, also I don't know if it's worth mentioning but I don't have the KDE desktop browser integration installed, mainly because I couldn't figure out how to do it, but I was unable to get this working on Gnome and Budgie so I don't think it's exclusive to KDE.

**Comment by ruihildt** [comment]
You had the same issue with Fedora Gnome 38?

**Comment by Thorin-Oakenpants** [comment]
Are you in Standard or Safer slider mode?

**Comment by BeyondThe5D** [comment]
> You had the same issue with Fedora Gnome 38?
I had been using Mullvad Browser in Fedora Gnome 38 before moving to KDE, after experiencing the issues I'm having right now on KDE I decided to go back to Gnome just to realise the issue happens on there.

> Are you in Standard or Safer slider mode?
I'm currently on safer but standard didn't change anything, I'm using stock settings FYI.

**Comment by Thorin-Oakenpants** [comment]
https://forums.fedoraforum.org/showthread.php?330144-Playing-videos-in-Firefox-in-Fedora-38

**Comment by BeyondThe5D** [comment]
As mentioned earlier, it works in Firefox but not Mullvad Browser.

**Comment by BeyondThe5D** [comment]
I set up a fresh install of Fedora KDE Spin on one of my laptops and installed the free RPM fusion package and the FFMPEG packages, issue still persists.
