### ISSUE TITLE
Unable to remove uBlock Origin or NoScript

### ISSUE THREAD

**Issue by eiqnepm** [mullvad/mullvad-browser#105]
Thanks Mullvad!

I just had to start off with that. Mullvad Browser is a great tool for the community, it solves problems that I have yet to see other browsers solve.

Please may an option be added to `about:config` to grant the ability to remove uBlock Origin and NoScript?

Even without these extensions, Mullvad Browser still offers unique features that I'm unable to replicate in any other browser.

I use [AdGuard AdBlocker](https://addons.mozilla.org/firefox/addon/adguard-adblocker/) together with [AdGuard Extra](https://github.com/AdguardTeam/AdGuardExtra) because when paired, the extensions have the ability to block more due to having scripting abilities, especially annoyances.

Obviously I using these extensions I am putting my trust in AdGuard to not push malicious scripts, this is not desirable for everyone, however it's a risk I'm personally willing to take for better blocking capabilities.

**Comment by Sneeze8145** [comment]
> Even without these extensions, Mullvad Browser still offers unique features that I'm unable to replicate in any other browser.
> 
> I use [AdGuard AdBlocker](https://addons.mozilla.org/firefox/addon/adguard-adblocker/) together with [AdGuard Extra](https://github.com/AdguardTeam/AdGuardExtra) because when paired, the extensions have the ability to block more due to having scripting abilities, especially annoyances.

I'm real curious about specific examples of this, I thought ublock origin was equal or even better than adguard in most if not all aspects but I would be happy to be proven wrong. What websites are annoying that can't be made less annoying using mullvad browser?

uBlock also has scripting functionality when needed: https://github.com/gorhill/uBlock/wiki/Resources-Library#available-general-purpose-scriptlets

If you or anyone encounter a thing you can't block using ublock origin and mullvad then please report it using the [speech bubble button in the ublock menu](https://github.com/gorhill/uBlock/wiki/Quick-guide:-popup-user-interface#report-an-issue-with-current-website) while you're at the specific site and it will fill out an issue template on [their very active issue repo](https://github.com/uBlockOrigin/uBlock-issues/issues). They should be able to help you and update the filters or even the addon if it's a valid issue and then we can all benefit from it.

**Comment by ruihildt** [comment]
Like mentioned by @AutonomousCat, we don't allow removing NoScript and uBlock Origin and we will not provide ways to do it.
The reason is that this will break some features (Security Level for NoScript) and will make you more unique.

That being said, if you really want to remove an extension, you can go in your profile and manually delete an extension.
