### ISSUE TITLE
Incompatible with Sites Requiring Firefox >= 110

### ISSUE THREAD

**Issue by AutonomousCat** [mullvad/mullvad-browser#106]
Issue: Website requiring Firefox 110 or above, says Mullvad Browser is based on Firefox 102. Is this true, regarding the version number?

![image](https://github.com/mullvad/mullvad-browser/assets/130127508/4b5d06b3-078c-4349-9745-96cf0e67b98a)

Not sure if this is a Mullvad Browser issue or a Tor upstream issue, but figure it's worth trying here first since there is a possibility of it being wrong.

**Comment by andretiagogr** [comment]
> Is this true, regarding the version number?

Yes. Tor browser is based on Firefox ESR and so is mullvad browser

**Comment by ruihildt** [comment]
Checking the `About` popup/page, you will see the Extended Support Release (ESR) being used by the browser.

Here's the current info (`12.0.7 (based on Mozilla Firefox 102.12.0esr) (64-bit)`):

![image](https://github.com/mullvad/mullvad-browser/assets/13787166/6ab8b92b-4f92-4d6b-8784-af003d30274e)

**Comment by ruihildt** [comment]
FYI, the Mullvad Browser 13.x will be based on the next major ESR, firefox 115.
