### ISSUE TITLE
Mullvad Browser blocked by Smart App Control

### ISSUE THREAD

**Issue by TommyTran732** [mullvad/mullvad-browser#108]
I don't know if you guys can work with Microsoft to fix this or not, but currently Mullvad Browser is blocked by Smart App Control on Windows.

The first time I launch either Mullvad or Tor Browser, I got "part of this app has been blocked", however everything still appears to be functional. 

Today, Mullvad Browser seems to be completely blocked. Tor Browser still opens just fine.

<img width="641" alt="Screenshot 2023-06-29 at 23 49 34" src="https://github.com/mullvad/mullvad-browser/assets/57488583/fc80862e-0c92-4d64-a9f0-2f91b944f382">

**Comment by ruihildt** [comment]
@TommyTran732 Do you still observe this behavior? 

We haven't any other similar feedback.

**Comment by TommyTran732** [comment]
I can check later. I just disabled SmartAppControl in my VM after realizing it is quite privacy invasive on its own.

**Comment by ave9858** [comment]
Seems fixed on the latest definition versions.

**Comment by ruihildt** [comment]
Closing this as we've not had any further report of issues regarding this.

Feel free to reopen if needed.
