### ISSUE TITLE
Find In Page feature persists search string

### ISSUE THREAD

**Issue by keywordnew** [mullvad/mullvad-browser#109]
# reproduction steps

Reproduction steps may fail. The actual behaviour (described farther below) is accurate. But the search string persisted is *not always* the most recent. The persisted string *can* be older than the most recent string input. I haven't been able to determine how to reliably make a more recent search string persist.

1. cmd-F
2. input a search string
3. delete search string
4. close Find In Page
5. request that Mullvad Browser create New Identity

# expected behaviour

Initializing Find In Page displays field as blank.

# actual behaviour

A past search string is pre-filled when the field re-initializes. 

# environment

There's no issue template, so I'll just provide basic context.

OS version: MacOS 13.4.1
Mullvad Browser version: 12.0.7

**Comment by ruihildt** [comment]
Thanks for the report.

Can you reproduce the same bug in Firefox?

**Comment by ruihildt** [comment]
And just to clarify, do you actually see the search string even after clicking the New Identity button?

**Comment by keywordnew** [comment]
> even after clicking the New Identity button?

Correct.

> Can you reproduce the same bug in Firefox?

Interesting. Yes. I can see the same behaviour in Firefox v114.0.2

**Comment by keywordnew** [comment]
The issue seems to be occurring in search fields that I can initialize with cmd-f, in multiple apps (though not all). I'm going to close this GitHub Issue now and dig further, as it's unlikely to be a Mullvad Browser issue. My apologies for the notifications.

**Comment by Thorin-Oakenpants** [comment]
FWIW I can't reproduce on windows (in any browser: FF, TB, MB)

**Comment by pospeselr** [comment]
I suspect this is related to this similar problem re earch in macOS:

- https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/14139
