### ISSUE TITLE
Large margins sometimes appear around web canvas

### ISSUE THREAD

**Issue by loukad** [mullvad/mullvad-browser#111]
I've noticed web pages render with large margins on the left, right and bottom that are outside the web site's view port (see image below):

<img width="1277" alt="image" src="https://github.com/mullvad/mullvad-browser/assets/7282874/3ce0e7d4-eeef-409c-8835-ab2b968c7ae4">

If I resize the browser window, the margins change size in a jumpy way.  Is this a side-effect of the attempt to block browser canvassing fingerprinting?

**Comment by iam-py-test** [comment]
This is a feature called Letterboxing designed to prevent websites from being able to tell your screen size

**Comment by loukad** [comment]
Ah. That’s what I suspected. Thanks for confirming. It would be good to
maybe optionally fill that space with some informational text to that
effect. Maybe on mouseover.

**Comment by iam-py-test** [comment]
I don't work for this project, but that sounds like an ok idea.

**Comment by Thorin-Oakenpants** [comment]
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/32324#note_2899463

**Comment by Eirikr70** [comment]
Hello, is there any way, any parameter, to allow the web pages to load the full size of the screen ?

**Comment by ruihildt** [comment]
> Hello, is there any way, any parameter, to allow the web pages to load the full size of the screen ?

This is not supported, because it alters the browser fingerprint and will make you more unique and thus stand out amongst other Mullvad Browser users.

We're working on improving the experience, but this feature is here to stay.
