### ISSUE TITLE
Add Startpage to default search engines (or let users add their own)

### ISSUE THREAD

**Issue by AutonomousCat** [mullvad/mullvad-browser#114]
Please add Startpage to the default list of search engines, or add a way to add default search engines. I think the latter makes the most sense because of so many instances of privacy oriented search engines like Searx, etc, - even self hosted ones.

I know that a workaround is the Startpage Firefox extension, but it hasn't been updated in 4 years so don't want to add any deprecated code that might break stuff.

**Comment by iam-py-test** [comment]
Startpage is owned by an advertising company<sup>[[1]](https://en.wikipedia.org/wiki/Startpage.com#Merger_and_recent_history)</sup> and has some shady affiliates<sup>[[2]](https://github.com/uBlockOrigin/uAssets/issues/18897)</sup> so IMO it's not a great privacy search engine, but having the ability to chose something not in the default list seems to be a excellent feature.

**Comment by ruihildt** [comment]
Closing as a duplicate of #70. (Adding search default engines is planned)
