### ISSUE TITLE
Automatic update re-added the "New Identity" button

### ISSUE THREAD

**Issue by AutonomousCat** [mullvad/mullvad-browser#116]
I previously had this hidden, so it appears to reset the customized toolbar specific to that button, because everything else is how it was.

**Comment by ruihildt** [comment]
Thanks, I could reproduce.

**Comment by ruihildt** [comment]
Upstream issue: https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/215

**Comment by ruihildt** [comment]
Fixed with https://github.com/mullvad/mullvad-browser/releases/tag/13.0
