### ISSUE TITLE
"Only Show In New Tab" Bookmark Toolbar View Option not working

### ISSUE THREAD

**Issue by tiara-adessi** [mullvad/mullvad-browser#119]
Hi all,

the "Only Show In New Tab" option for the bookmark toolbar does not work for me.

<img width="1512" alt="Screenshot 2023-07-29 at 23 48 54" src="https://github.com/mullvad/mullvad-browser/assets/134346897/6ae3a402-cd1f-4c4e-b81c-e2897dc48c36">

Mullvad Browser: 12.5.1 (based on Mozilla Firefox 102.13.0esr) (64-bit)
macOS (Ventura 13.4.1): Darwin 22.5.0 arm64

**Comment by Thorin-Oakenpants** [comment]
duplicate of #14 

quick link: https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41717

**Comment by tiara-adessi** [comment]
@Thorin-Oakenpants, thank you for pointing that out. I'll assume i'll check this issue tracker and the one of the Tor Project more thoroughly then. 🙈 Sorry for occupying time with this newbie nonsense...
