### ISSUE TITLE
H264 Videos Not Playing in Mullvad Browser on Fedora

### ISSUE THREAD

**Issue by Bok0335** [mullvad/mullvad-browser#120]
I recently started using the Mullvad browser on Fedora Linux. I've noticed that videos encoded in H264 format do not play at all in the browser, even though the necessary codecs are installed on my system. The preinstalled Firefox on my system plays H264 videos without any issues, and the Flatpak version of the Mullvad browser also plays these videos correctly. This leads me to believe that the issue might be specific to the standalone version of the Mullvad browser.

I've tried redownloading the codecs but the issue persists.

I would appreciate any assistance or insights into this issue. Is there a specific build or configuration setting that might be causing this issue? Or is there a workaround that I could use to enable H264 playback in the Mullvad browser?

Appreciate any help.

**Comment by ruihildt** [comment]
Just to make sure we're on the same page, if you click on the following link, you don't see the video in your browser?

https://test-videos.co.uk/vids/bigbuckbunny/mp4/h264/1080/Big_Buck_Bunny_1080_10s_1MB.mp4

**Comment by ruihildt** [comment]
Just to make sure we're on the same page, if you click on the following link, and then any of the download button, you don't see the video in your browser?

https://test-videos.co.uk/bigbuckbunny/mp4-h264

**Comment by Bok0335** [comment]
Thank you for your response. I followed your suggestion and tried to play the H264 video from the link you provided, after authorizing the video with NoScript, I received an error message, like always for this video format, stating "No video with supported format and MIME type found".

I would like to add that I have tested this on both XWayland and Wayland, and the issue persists on both.

**Comment by Thorin-Oakenpants** [comment]
see #102 which was originally titled `To play video, you may need to install the required video codecs` and is also about Fedora

**Comment by Thorin-Oakenpants** [comment]
*sigh* ... https://forum.torproject.org/t/playing-videos-on-fedora-38/8601

**Comment by luigir-it** [comment]
I had the same issue on Arch, installing ffmpeg4.4 fixed it

**Comment by onexgrg67** [comment]
its because arch, fedora, gentoo... they are free distros that do not have any software of this type pre-installed by default.
However, I also recommend either ffmpeg or vlc (which will install dependencies similar to ffmpeg).
