### ISSUE TITLE
Feature request: tab group

### ISSUE THREAD

**Issue by howarddo2208** [mullvad/mullvad-browser#123]
Hi, I'm daily driving Mullvad browser and loving so far, but the tab group feature is missing, it would be nice to have it on Mullvad.

**Comment by Thorin-Oakenpants** [comment]
> but the tab group feature is missing

please show me where in Firefox this so called feature is, thanks

**Comment by howarddo2208** [comment]
Oh, I moved from Chromium browser, only now that I know it's not a core feature of Firefox, I'll try the extension and close this then.
