### ISSUE TITLE
remove dead zones on edges

### ISSUE THREAD

**Issue by asdffdsazqqq** [mullvad/mullvad-browser#124]
hello, thanks much,
when the browser is maximized, there are dead zones on the left side, right side and bottom.
thus shrinking the area left to display the webpage.
firefox does not do that.

see image below, the dead zones are highlighted yellow.

left side
![image](https://github.com/mullvad/mullvad-browser/assets/90116442/d1afd8c1-026e-402d-a13b-94fc17b4b774)

right side
![image](https://github.com/mullvad/mullvad-browser/assets/90116442/f95552f6-d3c7-4db2-9c76-d0a0510c911d)

bottom
![image](https://github.com/mullvad/mullvad-browser/assets/90116442/2a38d183-0a8c-4445-b59a-155310fa07c6)

**Comment by Thorin-Oakenpants** [comment]
https://mullvad.net/help/tag/mullvad-browser/ > Show All FAQs

> What's this weird spacing around the websites?
>
> It’s called letterboxing, a function to combat fingerprinting (using your browser window size to identify you together with other measures).

**Comment by gsture** [comment]
Please before opening issues like this try to learn the very basics of fingerprinting or at least read the faq. This repository is full of people that fail to understand where this project is all about.

**Comment by ruihildt** [comment]
We could do a better job of pre-empting those kind of issues report by adding some kind of issue template, I'll look into it.

Please not that there's also an ongoing reevaluation on how to better support/implement/introduce Letterboxing to users.

**Comment by Thorin-Oakenpants** [comment]
> Please not

Please **note** :) unfortunate typo
