### ISSUE TITLE
How to make NoScript settings persist across sessions?

### ISSUE THREAD

**Issue by Vysp3r** [mullvad/mullvad-browser#126]
I am unable to find anything online on how to make NoScript settings persist across sessions which cause me to always have to re-add those for every website that I frequently use. Is there anyway to do that? Is it disabled for some reasons?

**Comment by Thorin-Oakenpants** [comment]
feel free to close this when finished reading -> https://github.com/mullvad/mullvad-browser/issues/41#issuecomment-1499533932

**Comment by Vysp3r** [comment]
@Thorin-Oakenpants Oh damn my bad, I searched for that but I was only searching for open issues not all of them. Thanks!
