### ISSUE TITLE
uBlock Origin filters are not working after restarting the browser

### ISSUE THREAD

**Issue by ruihildt** [mullvad/mullvad-browser#127]
> Within the 'My Filters' settings of uBlock Origin, I have defined a variety of element filters. I am able to append to this list, and they are effective for the current session. However, upon closing the browser and re-opening, they are no longer applied, despite that they remain listed.

And:
> I was able to reproduce this. I went to [google.com](http://google.com/) and used the element picker in the uBlock extension to block the Google logo. It disappears after force-reloading [google.com](http://google.com/), but when I restart the browser it's not blocked anymore.

**Comment by ruihildt** [comment]
@Thorin-Oakenpants Any idea about this?

**Comment by Thorin-Oakenpants** [comment]
the google logo can be dynamic. The question for us is can OP open the filter list and still see the rule

**Comment by Thorin-Oakenpants** [comment]
testing: windows

picker says, add it
```
||www.google.com/images/branding/googlelogo/*x/googlelogo_color_272x92dp.png$image
```

restart, go back, logo shows, picker says the below, add it
```
||www.google.com/images/branding/googlelogo/*x/googlelogo_color_272x92dp.png
```

restart, go back, logo shows, picker says the same as the one just above

lemme test on firefox

**Comment by ruihildt** [comment]
Just tried with something more static like:
> ! 2023-08-17 https://www.torproject.org
> www.torproject.org##.pt-5.bg-dark.container
> www.torproject.org##.pt-5.content-center.col-12

I can reproduce the issue. Is this expected?

**Comment by Thorin-Oakenpants** [comment]
> Is this expected

I wouldn't think so

**Comment by Thorin-Oakenpants** [comment]
works for me in Firefox (normal mode) .. gimme a few minutes to check pb mode

**Comment by ruihildt** [comment]
It works for me in FF (normal mode), I have been relatively often using it to hide elements on some website.

**Comment by Thorin-Oakenpants** [comment]
> It works for me in FF (normal mode)

not me, but I was testing nightly (which sanitizes everything on close - so nothing cached - maybe yours is cached?), and my uBO is just bare bones defaults - it can't be the storage thing, that was fixed, and the filter is still there, and I only tested the google logo

**Comment by ruihildt** [comment]
I also tried in PBM to create a new filter and restart, filter is kept as expected.

**Comment by Thorin-Oakenpants** [comment]
just tried in my FF116 stable (normal mode, arkenfoxed to hell and back), works and obv filter is kept

**Comment by Thorin-Oakenpants** [comment]
lemme try ESR102

**Comment by Thorin-Oakenpants** [comment]
OK, it does work in my nightly, there are two - I must be an AB test or something.

```
||www.google.com/images/branding/googlelogo/*x/googlelogo_light_color_272x92dp.png$image
||www.google.com/images/branding/googlelogo/*x/googlelogo_color_272x92dp.png$image
```

**Comment by Thorin-Oakenpants** [comment]
https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/229

**Comment by ruihildt** [comment]
This is actually because we ship uBlock Origin with the `My filters` list deactivated by default.
Users can turn this on and cosmetic filters will be applied.


![image](https://github.com/mullvad/mullvad-browser/assets/13787166/d8c81b1a-1252-4ab9-ab24-7ed270241b97)

**Comment by ruihildt** [comment]
In case this is not obvious enough, this is something that should be fixed upstream, in uBO UI.

**Comment by nadesco** [comment]
Having that box deactivated by default was not helpful. I imported a uBO backup file into Mullvad a little earlier but didn't realise that I needed to  check `My Filters` as well. So it was unexpected behaviour when `Block element` didn't show in the contextual menu and my filters didn't work right off the bat as they usually would.

**Comment by ruihildt** [comment]
@nadesco I understand that this is not the expected behavior, so I opened an issue in the uBlock Origin issue tracker.

See: https://github.com/uBlockOrigin/uBlock-issues/issues/3161

**Comment by nadesco** [comment]
Thanks! Don't know if it's related but I should add that not all the imported filters worked for some reason. On one site I had to re-add some of the elements to the `My filters` list. That was with the `My filters` box checked. Not a problem but just to say it wasn't a smooth transition. I tried re-importing the backup file and also reinstalled Mullvad but that didn't have any effect.

**Comment by ruihildt** [comment]
Can you check in a regular Firefox (with a new Firefox profile), that importing this list in uBO doesn't result in the same errors?

If it does end up with the same errors, then you should file an issue to uBO issues about it.
If not, and if you feel comfortable sharing the rules, you can create another issue here with the errors you encounter and I'll try to reproduce it.

**Comment by nadesco** [comment]
I set up a new profile in FF, imported a new backup file (from Librewolf) and it worked fine -- ie; no need to recheck the `My filters` box and the filters on the site I spoke of worked fine. I then exported the uBO file from FF and imported it to Mullvad. The bug showed up again though. Like I say, I'm not bothered about it since it's easily fixed and the filters might be 'disrupted' because `My filters` is deactivated during import. Just a guess though. The url of the site is zerohedge.com. Clicking on hyperlinks brings up an overlay and other ads which weren't there before.

**Comment by nadesco** [comment]
> If not, and if you feel comfortable sharing the rules, you can create another issue here with the errors you encounter and I'll try to reproduce it.

If it's any help I filed a new issue at https://github.com/mullvad/mullvad-browser/issues/231 with the rules for that website.

**Comment by ruihildt** [comment]
Thank you.
