### ISSUE TITLE
"Learn more" about Security Level leads to nowhere.

### ISSUE THREAD

**Issue by Lxrdux** [mullvad/mullvad-browser#128]
In the "Security Level" section of the "Privacy & Security" tab in the settings, the "Learn more" link leads to "about:manual#security-settings", which leads to an error page. 
The error reads
"""Hmm. That address doesn’t look right.
Please check that the URL is correct and try again."""
With a button that reads "Try Again"

**Comment by Thorin-Oakenpants** [comment]
indeed .. `about:manual` is TB, not base browser

**Comment by ruihildt** [comment]
Thanks for the report, here's the URL that should have been linked: https://mullvad.net/en/browser/hard-facts#security-levels
