### ISSUE TITLE
Screen resolution is different in tor and mullvad browser

### ISSUE THREAD

**Issue by Akshaybun** [mullvad/mullvad-browser#129]
It should be same, right? Tor seems to be providing more screen estate than mullvad. 

mullvad : https://0.0g.gg/?30fc54dc705c4eba#9jY71zNbxtMDWjsyJQhHFiUgnt8xkLHs1D7wbu3VpcNd
tor : https://0.0g.gg/?73e5a7656a4f54b9#29PUeHV96GSHhuygK12fsCm9tn7sUG4EN2Ha5P7HFZhL

**Comment by ruihildt** [comment]
I'm trying to reproduce, can you share your:
- OS
- resolution of your screen
- Mullvad Browser & Tor Browser versions used

**Comment by Akshaybun** [comment]
OS : 6.1.46-1-lts Arch Linux , awesomewm
Mullvad : 13.0a2 (based on Mozilla Firefox 115.1.0esr) (64-bit)
Tor: 12.5.2 (based on Mozilla Firefox 102.14.0esr) (64-bit)
Display : 1366x768

**Comment by ruihildt** [comment]
You are comparing Mullvad Browser alpha (13.0a2) with Tor Browser stable (12.5.2).

The starting window size has changed for both browser in the alpha channel.
You should get the same size if you use Tor Browser 13.0a2. (Installer: https://dist.torproject.org/torbrowser/13.0a2/)
