### ISSUE TITLE
What is the Mullvad Browser Installation FAQ (step by step) for Linux Distros?

### ISSUE THREAD

**Issue by serial02** [mullvad/mullvad-browser#13]
Hello Mullvad Browser team

On the Mullvad Browser download page, the received file is in the testing phase, correct?
 On the Mullvad Browser FAQ page (https://mullvad.net/en/help/tag/mullvad-browser/) there are no instructions on how to install Mullvad Browser on Linux distributions.  Can you send me the correct step by step to install Mullavad Browser on openSuse Tumbleweed distro please?

Thanks in advance for your attention

**Comment by asdfzxcvbn** [comment]
download the browser, verify the download hasnt been tampered by following the verification guide, unzip it, and move the .desktop file to `~/.local/share/applications/`

**Comment by asdfzxcvbn** [comment]
the actual binary to start the browser is in Browser/start-mullvad-browser btw

**Comment by june-meyers** [comment]
I just wrote with a member of the Mullvad crew and now it works for me like that:

1. download the file.
2. extract it.
3. start a terminal in the main folder.
4. run the command `./start-mullvad-browser.desktop`
5. the Mullavd Browser starts as expected.

**Comment by ruihildt** [comment]
We will put out a guide for it, I'll close this issue when it's up, for the moment you can follow @june-meyers instruction or contact support@mullvad.net if you need more help.

**Comment by championquizzer** [comment]
Adding another step to @june-meyers' list of steps here:
At step. 4, you can launch with the `--register-app` flag i.e. `./start-mullvad-browser.desktop --register-app`
This should register Mullvad Browser with the application launcher. So if you use something like rofi, dmenu, etc. you can launch Mullvad Browser directly from there.

**Comment by Deviner75** [comment]
You can also move the mullvad folder to /opt/ and create a launcher as a step 6 

```shell
vim /usr/local/bin/mullvad-browser
```
```shell
#!/bin/bash

cd /opt/mullvad-browser/Browser
./start-mullvad-browser
```

**Comment by linuxosd** [comment]
> I made this quick tutorial on how to install, update and uninstall the Mullvad Browser for a user, I hope it's relevant here: https://retiolus.net/posts/how-to-install-mullvad-browser-on-linux/

This link is down, fyi.

**Comment by serial02** [comment]
> > I made this quick tutorial on how to install, update and uninstall the Mullvad Browser for a user, I hope it's relevant here: https://retiolus.net/posts/how-to-install-mullvad-browser-on-linux/
> 
> This link is down, fyi.

Hello @linuxosd 

The site is working normally at the moment.
 I am very good with the step by step installation of the Mullvad Browser on your website.

 Thanks for the clarification.

**Comment by serial02** [comment]
> I made this quick tutorial on how to install, update and uninstall the Mullvad Browser for a user, I hope it's relevant here: https://retiolus.net/posts/how-to-install-mullvad-browser-on-linux/

Hello @retiolus 

This step by step was very accurate, fast and without margin for errors!

 Thank you very much for the indication.

 Now, does this same walkthrough also work correctly for TorBrowser?

**Comment by ruihildt** [comment]
Guide is now available on our website: https://mullvad.net/en/help/install-mullvad-browser/

If you have feedback or comment on it, please contact support@mullvad.net
