### ISSUE TITLE
Create deb/rpm packages

### ISSUE THREAD

**Issue by 0xspade** [mullvad/mullvad-browser#133]
Hi Team,

Does Mullvad browser has linux traditional deb package format? I want my mullvad browser to be managed by `apt` for updates.

**Comment by ruihildt** [comment]
We don't currently have a .deb package, but this is something we would like to have at some point.

**Comment by adrelanos** [comment]
Please consider hosting an APT repository rather than direct download `.deb`  but of course having a `.deb` is better than not having nothing at all. Related ticket:

* https://github.com/mullvad/mullvad-browser/issues/201

**Comment by ruihildt** [comment]
We will make available both rpm/deb (and also through our own repositories, see https://github.com/mullvad/mullvad-browser/issues/201), see the upstream issues regarding the packaging:

- https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/28
- https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/29

**Comment by adrelanos** [comment]
May I ask please if there should be realistic hope? Asking due to the history. Deb packaging for Tor Browser (TB) is a 12 years old rejected feature request at the Tor Project's issue tracker:

* https://gitlab.torproject.org/legacy/trac/-/issues/5236
* https://gitlab.torproject.org/legacy/trac/-/issues/3994

If the situation was better for Mullvad Browser (MB) that would be amazing and might give new hope for TB as well.

**Comment by ruihildt** [comment]
Getting deb/rpm package for Mullvad Browser is firmly in the plans for this year.

I would expect this to make it easier for Tor Browser to also be packaged, but I can't speak for their plans.

**Comment by ruihildt** [comment]
ℹ️  Deb and rpm packages are now available through our repositories.

These packages are designed exclusively for installation via our repositories to ensure automatic updates.
Installing them directly bypasses this mechanism, and **you won't receive in-browser notifications about new updates**.

To add the repositories to Fedora/Ubuntu/Debian, follow the instructions on the [download page](https://mullvad.net/en/download/browser/linux).

**Comment by truescotian** [comment]
> ℹ️ Deb and rpm packages are now available through our repositories.
> 
> These packages are designed exclusively for installation via our repositories to ensure automatic updates. Installing them directly bypasses this mechanism, and **you won't receive in-browser notifications about new updates**.
> 
> To add the repositories to Fedora/Ubuntu/Debian, follow the instructions on the [download page](https://mullvad.net/en/download/browser/linux).

@ruihildt Maybe a separate issue, but it looks like the mullvad cdn is down so I'm unable to download. Tried both downloading the app using the Mullvad repository option, and the manual installation option.
