### ISSUE TITLE
Flickering (Fedora, Wayland, Nvidia)

### ISSUE THREAD

**Issue by rideandrain** [mullvad/mullvad-browser#134]
Hi, been trying out Mullvad Browser and noticing flickering on any type of usage, but noticeably more frequent when scrolling or typing. The flickers could be the entire webpage, or a particular section of it, or only surrounding the cursor. It typically lasts 2-5 seconds or until the browser is minimized and maximized again. There are also minor framerate drops at a similar interval when viewing YouTube on fullscreen.

This has happened on both Flatpak and from the direct download. I have had no other flickering with any other app on my system. Switching to X11 appears to resolve the issue.

Is Mullvad Browser an electron app? If so, then it is probably linked to known existing flickering issues between electron and wayland.

My Specs:
- Mullvad Version: 12.5.3 (based on Mozilla Firefox 102.15.0esr) (64-bit)
- Operating System: Fedora Linux 38
- KDE Plasma Version: 5.27.7
- KDE Frameworks Version: 5.109.0
- Qt Version: 5.15.10
- Kernel Version: 6.4.13-200.fc38.x86_64 (64-bit)
- Graphics Platform: Wayland
- Graphics Processor: NVIDIA 30XX
- Nvidia Drivers: 535.104.05

**Comment by Thorin-Oakenpants** [comment]
What is your monitor's FPS? This sounds like RFP's timing mitigations

**Comment by rideandrain** [comment]
Do you mean its refresh rate? Its 60 Hz

**Comment by Thorin-Oakenpants** [comment]
Yup. 60 Hz = 60 frames per second :)

**Comment by Thorin-Oakenpants** [comment]
Does it happen in MB13 alpha - https://cdn.mullvad.net/browser/13.0a3/ ?

**Comment by rideandrain** [comment]
> Does it happen in MB13 alpha

Yes

btw, is Mullvad Browser based on electron?

**Comment by Thorin-Oakenpants** [comment]
No. It uses [gecko](https://en.wikipedia.org/wiki/Gecko_(software))

**Comment by rideandrain** [comment]
Came across https://old.reddit.com/r/kde/comments/11eq79w/screen_flicker_on_wayland_w_nvidia_driver_on_arch/jah6gjj/

MB is running on xWayland for me. 
I have also seen https://github.com/mullvad/mullvad-browser/issues/39, however even after adding `MOZ_ENABLE_WAYLAND=1` to the environment variables, its still on xWayland.
I'm unsure whether I did it correctly, or perhaps there was a regression on #39?

I have another apps running on xWayland with no issue. Firefox is running on Wayland with no issue either.

I also wonder whether the lack of any installation has any impact. The extracted folder from the [direct download for Linux](https://mullvad.net/en/download/browser/linux) appears to contain everything needed and MB runs out of that folder. Its not tracked on KDE's Discover or on DNF.

**Comment by rideandrain** [comment]
Came across https://old.reddit.com/r/kde/comments/11eq79w/screen_flicker_on_wayland_w_nvidia_driver_on_arch/jah6gjj/ and https://github.com/mullvad/mullvad-browser/issues/39

MB was previously running on xWayland, its running on Wayland now. So far so good, will report back in 24 hours.

**Comment by rideandrain** [comment]
Glad to report that switching to Wayland has resolved the flickering

**Comment by Thorin-Oakenpants** [comment]
> I have had no other flickering with any other app on my system

So Firefox flatpak doesn't have this issue? So Firefox runs on wayland by default?

**Comment by rideandrain** [comment]
FF comes preinstalled on Fedora, so I have not used the flatpak version. Honestly its been some time since I had initially setup FF, I can't remember whether I had to switch it to Wayland. I took a look at the configs and my env vars for FF are empty. IIRC, Fedora has defaulted to Wayland since F36, would be safe to assume that the preinstalled FF also uses Wayland.

**Comment by Thorin-Oakenpants** [comment]
IDK, hence asking, but at least we have #136 for followup
