### ISSUE TITLE
Not able no login Skiff mail

### ISSUE THREAD

**Issue by tabi-ya** [mullvad/mullvad-browser#139]
Hey, I recently started using Mullvad and when I try to login on Skiff mail it shows error "It looks like there's a temporary connectivity issue. Please try again in a couple of minutes. On iOS, try temporarily disabling Lockdown Mode." 

![image](https://github.com/mullvad/mullvad-browser/assets/135990135/201e99a5-93f9-4597-bacc-5fae410e7e03)

**Comment by Thorin-Oakenpants** [comment]
What is your security level. In safer mode, wasm is disabled and this will break skiff's login [source](https://old.reddit.com/r/Skiff/comments/13hc3qs/log_in_to_skiff/)

**Comment by Thorin-Oakenpants** [comment]
nope, it's global

**Comment by Thorin-Oakenpants** [comment]
we should file a ticket to explore options @ruihildt .. this is not the only example of logins using wasm, but I forget where I came across the others

**Comment by Thorin-Oakenpants** [comment]
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/30570 - Implement per-site security settings support

don't hold your breath just yet, this is a newer ticket of an even older one, and it's not super straight forward as some of the items in the slider are not engineered to be per set

**Comment by Thorin-Oakenpants** [comment]
This also happens on Tutanota (I have filed an issue so at least they are aware)
- see https://github.com/tutao/tutanota/issues/6094

**Comment by Thorin-Oakenpants** [comment]
I also dropped skiff a line
![skiff](https://github.com/mullvad/mullvad-browser/assets/16656956/64e7307b-936e-4656-bb33-a4d1d87b35fc)

**Comment by Thorin-Oakenpants** [comment]
Thanks @amilich - I sent back a reply to the latest email: support/request id: 19598
