### ISSUE TITLE
[Suggestion] Don't auto-open Github releases page after update

### ISSUE THREAD

**Issue by mojo-jojo-7** [mullvad/mullvad-browser#142]
Opening a third-party website without the user's consent is not a good practice in my opinion

**Comment by ruihildt** [comment]
This is indeed not a good practice and this needs to be fixed at some point.

**Comment by photondetector** [comment]
I came here to say this. Ultimately it's a telemetry ping to Microsoft (since they own Github), which sort of follows the principle of most astonishment for a privacy-focused browser.

I appreciate all the work folks are doing on this project, thank you!
