### ISSUE TITLE
When yubikey?

### ISSUE THREAD

**Issue by nekobits** [mullvad/mullvad-browser#146]
Love the browser, would be great if one day the browser supported signing in with security keys.

**Comment by Thorin-Oakenpants** [comment]
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/26614 @PieroV .... you guys even gave me a yubikey in costa rica!!!

**Comment by Thorin-Oakenpants** [comment]
also https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41537

**Comment by felschr** [comment]
Related: #53 #38

**Comment by ruihildt** [comment]
Duplicate of #53
