### ISSUE TITLE
Consider uBlock Origin Lite?

### ISSUE THREAD

**Issue by c3Ls1US** [mullvad/mullvad-browser#147]
With the official release of the [uBlock Origin Lite](https://github.com/uBlockOrigin/uBOL-home) (uBOL) extension about a month ago, I would like to know if there has been any discussion of possibly switching over to it? While it has less features than uBO, depending on Mullvad Browser's (MB) requirements for a content blocker, it could be a better fit.

Key features of uBOL:

- uBOL does not require broad "read/modify data" by default
- Entirely declarative for reliability and CPU/memory efficiency
- [uBOL never makes network requests to any remote servers](https://github.com/uBlockOrigin/uBOL-home/wiki/Frequently-asked-questions-(FAQ)#when-do-filter-lists-update)

Additionally, lists update whenever the extension updates which is convenient. Currently in MB, whenever new lists are added or defaults are changed in each new release, users need to remember to reset uBO to its default to acquire those changes--at least on Linux. Since users may forget to perform this action, in the case of _default_ configuration for uBO, this results in fragmentation of filter lists for each release and this is not the case for uBOL.

**Comment by mullgit** [comment]
What are the potential downsides of switching to uBOL (uBlock Origin Lite)? 
Here two quotes from their [Github-FAQ](https://github.com/uBlockOrigin/uBOL-home/wiki/Frequently-asked-questions-(FAQ)#if-i-install-ubol-will-i-see-a-difference-with-ubo):

> In uBOL, you will have to raise the blocking mode to either Optimal or Complete to benefit from cosmetic filtering and scriptlet injection.

> Furthermore, uBOL requires the default mode to be Optimal or Complete for some advanced filtering capabilities to take effect, while they are enabled by default in uBO (see [Filtering capabilities which can't be enforced without broad read/modify permissions](https://github.com/uBlockOrigin/uBOL-home/wiki/Frequently-asked-questions-(FAQ)#filtering-capabilities-which-cant-enforced-without-broad-readmodify-permissions)).

Does Mullvad Browser use filtering features that require read and modify permissions?
Is a changeover also being considered for the TorBrowser?

**Comment by mullgit** [comment]
seems to overlap with other torproject "**Feature**" for "**13.5**"

- https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/164
- https://github.com/mullvad/mullvad-browser/issues/37

**Comment by Thorin-Oakenpants** [comment]
https://gitlab.torproject.org/tpo/applications/team/-/wikis/Goteburg-2023-Meeting-Notes/ublock-origin

so in Sweden it was determined that uBO Lite was not feasible - from memory this was ma1's words
