### ISSUE TITLE
Integration of "PrivacyBadger" (EFF) addon in MullvadBrowser and TorBrowser.

### ISSUE THREAD

**Issue by mullgit** [mullvad/mullvad-browser#148]
The PrivacyBadger addon (PB) has evolved over the past years. In the past, PB has "learned" which tracker software is included on which websites by visiting websites; this [feature is disabled by default](https://www.eff.org/deeplinks/2020/10/privacy-badger-changing-protect-you-better) and should remain disabled when included. PB will rely on its [pre-trained list of tracking domains](https://www.eff.org/deeplinks/2018/08/giving-privacy-badger-jump-start) to perform blocking by default.

PB has other strengths because the EFF stays on the ball and brings improvements like [fight "link tracking" (September 2023)](https://www.eff.org/deeplinks/2023/09/new-privacy-badger-prevents-google-mangling-more-your-links-and-invading-your).

**Comment by Thorin-Oakenpants** [comment]
what an awesome source ... I shall bookmark it
