### ISSUE TITLE
[Feature Request] [Addon] Set umatrix as a default addon

### ISSUE THREAD

**Issue by cyberhardt** [mullvad/mullvad-browser#150]
I think umatrix is a better addon than noscript and ublock. it can block ads as well as scripts, but most importantly you can actually see which url's and which elements are being blocked. why not set it as a default addon, either accompanied by ublock+noscript or in their place

**Comment by Thorin-Oakenpants** [comment]
[umm, no .. just no](https://github.com/arkenfox/user.js/wiki/4.1-Extensions#-dont-bother)

> * uMatrix
>   - ⚠️ No longer maintained, the last release was Sept 2019 except for a [one-off patch](https://github.com/gorhill/uMatrix/releases/tag/1.4.2) to fix a [vulnerability](https://github.com/vtriolet/writings/blob/main/posts/2021/ublock_origin_and_umatrix_denial_of_service.adoc)

**Comment by ruihildt** [comment]
As pointed out, uMatrix is not maintained.
