### ISSUE TITLE
A Few Suggestions

### ISSUE THREAD

**Issue by anxiouslelimo** [mullvad/mullvad-browser#154]
The browser is working great. A few suggestions (not sure if it is outside the scope)

1. A homepage and new tab with tiles like firefox. 
2. More default filters for ublock origin. Easylist social widgets, easylist other annoyances and ublock cookie filter.
3. Brave Search as a search engine
4. An onboarding slide telling the benefits of browser

**Comment by ruihildt** [comment]
I opened separate issues for you 1 and 2.

- 3 : this is coming in Mullvad Browser 13.0
- 4 : we don't plan to add an on boarding. If something is unclear or missing from the website https://mullvad.net/browser, let me know and we'll update it.

**Comment by ruihildt** [comment]
> 4. In that case something i find missing is settings (changes) that doesn't affect the fingerprint.

This is something we want to address, I agree it's hard to tell if a change has any impact or not.
