### ISSUE TITLE
Latest release missing asc for linux tarball

### ISSUE THREAD

**Issue by aptalca** [mullvad/mullvad-browser#155]
The latest github release (12.5.6) is missing the asc for the linux tarball [mullvad-browser-linux64-12.5.6_ALL.tar.xz](https://github.com/mullvad/mullvad-browser/releases/download/12.5.6/mullvad-browser-linux64-12.5.6_ALL.tar.xz)
Can that be added as it's breaking our ci that ingests the releases?

Thanks

**Comment by jbjorkang** [comment]
This has now been rectified, sorry for the trouble
