### ISSUE TITLE
Windscribe VPN Disconnecting

### ISSUE THREAD

**Issue by daveroxs12** [mullvad/mullvad-browser#159]
I am using Windscribe VPN with Mullvad VPN, and frequently I receive the error: "Unable to find proxy." When it occurs, it occurs on all websites. 
![SCR-20231005-s1h](https://github.com/mullvad/mullvad-browser/assets/35511092/c85816b8-772f-4f65-b448-45db723d5b53)
Edit: This has occurred on many server (Not a server-specific issue).

**Comment by ruihildt** [comment]
Do you mean you're using
- Mullvad Browser with Windscribe VPN
- both Mullvad VPN and Windscribe VPN in conjunction
- all ofMullvad Browser, Mullvad VPN and Windscribe VPN

**Comment by daveroxs12** [comment]
> Do you mean you're using
> 
>     * Mullvad Browser with Windscribe VPN
> 
>     * both Mullvad VPN and Windscribe VPN in conjunction
> 
>     * all ofMullvad Browser, Mullvad VPN and Windscribe VPN

I am using ONLY Mullvad Browser with Windscribe VPN. Is it likely a modified setting?

**Comment by ruihildt** [comment]
It seems you have configured a proxy in Firefox which is failing.

Can you confirm you're using Windscribe through https://addons.mozilla.org/en-US/firefox/addon/windscribe/ ?

**Comment by daveroxs12** [comment]
> It seems you have configured a proxy in Firefox which is failing.
> 
> Can you confirm you're using Windscribe through https://addons.mozilla.org/en-US/firefox/addon/windscribe/ ?

Correct. I am using Windscribe VPN as a proxy(that specific link is correct) for Mullvad Browser without any of the about:config settings altered.

Additionally, have not configured Windscribe to run as a proxy in the "Connection Settings" panel for Mullvad VPN. It is running as a proxy through the Firefox extension, not the Network Settings panel-Choose how Mullvad connects to the internet.

**Comment by ruihildt** [comment]
I just tested with Mullvad Browser 12.5.6 + Windscribe addon 3.4.8 and a free account, and it worked without issue when connecting to Frankfurt Castle.

Can you please try the following:
- download and install Mullvad Browser in a new folder
- close any opened instance of Mullvad Browser
- launch the newly installed Mullvad Browser
- go to https://addons.mozilla.org/en-US/firefox/addon/windscribe/
- install the extension (during the installation, make sure to tick the box to allow running the extension in Private Window)
- connect to your windscribe account
- select the Germany > Frankfurt Castle option
- browse

**Comment by daveroxs12** [comment]
> I just tested with Mullvad Browser 12.5.6 + Windscribe addon 3.4.8 and a free account, and it worked without issue when connecting to Frankfurt Castle.
> 
> Can you please try the following:
> 
>     * download and install Mullvad Browser in a new folder
> 
>     * close any opened instance of Mullvad Browser
> 
>     * launch the newly installed Mullvad Browser
> 
>     * disable the Mullvad Browser Extension
> 
>     * go to https://addons.mozilla.org/en-US/firefox/addon/windscribe/
> 
>     * install the extension (during the installation, make sure to tick the box to allow running the extension in Private Window)
> 
>     * connect to your windscribe account
> 
>     * select the Germany > Frankfurt Castle option
> 
>     * browse

I will connect for me on any location, but the issue is that it will frequently disconnect. I can do all of that, but the issue isn't connection, per se, but when it disconnects.

**Comment by ruihildt** [comment]
Have you tried this with Firefox? Do you encounter the same issues?

**Comment by daveroxs12** [comment]
I did not have the issue when I used it with Firefox. I suspected that the issue was with DuckDuckGo, but I didn't want to manually alter the search engine molzl. When I started using Startpage, there was no issue with Windscribe VPN.
