### ISSUE TITLE
[Windows] Mullvad browser locked at 60 fps

### ISSUE THREAD

**Issue by CostcoFanboy** [mullvad/mullvad-browser#16]
It seems Mullvad is locked by default at 60 fps. 
Is there a way to remove this lock? I don't see a setting in about:config that could help.

Source:
![image](https://user-images.githubusercontent.com/123121530/229668493-0a1d9b18-eec3-463c-a8f6-3ce28000e34a.png)
https://www.testufo.com/

FF had it removed by default and I can crank up the FPS up to my monitor's Hz (144).

**Comment by Thorin-Oakenpants** [comment]
This is by design - part of RFP

**Comment by CostcoFanboy** [comment]
> This is by design - part of RFP

I see. I think this is too much of a user experience hit to be worth the use. 
I'll stick to Waterfox. Cheers, thank you for the quick answers.

**Comment by ruihildt** [comment]
See:

https://bugzilla.mozilla.org/show_bug.cgi?id=1692609
https://bugzilla.mozilla.org/show_bug.cgi?id=1774247

**Comment by Thorin-Oakenpants** [comment]
don't forget https://bugzilla.mozilla.org/show_bug.cgi?id=1772711

If you ever want relevant bugzillas, ping me - I am an encyclopedia :)

**Comment by CostcoFanboy** [comment]
> See:
> 
> https://bugzilla.mozilla.org/show_bug.cgi?id=1692609 https://bugzilla.mozilla.org/show_bug.cgi?id=1774247

I understand this being a requirement for something like TOR, but this is rather regressive for an everyday browser.

If this philosophy is followed, I believe that there is effectively no real use case for this browser. And this will just became "gimped TOR".

Every user will either go to TOR for real privacy, Firefox for "some privacy" or WaterFox/LibreWolf for "Firefox without the garbage that violates privacy".
