### ISSUE TITLE
Security Level Change from Toolbar Itself

### ISSUE THREAD

**Issue by anxiouslelimo** [mullvad/mullvad-browser#160]
It would be useful to have security level changes through toolbar instead of going to settings. 

Pros
Better ui/ux and ease of use.

**Comment by Thorin-Oakenpants** [comment]
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/30570 - Implement per-site security settings support

**Comment by ruihildt** [comment]
There is currently no plan to move the Security Levels from the toolbar itself.

There is a wider ongoing discussion as to how the Security Levels can be better integrated in the browser, based on threat models.
