### ISSUE TITLE
Why does this GitHub repository exist?

### ISSUE THREAD

**Issue by elvis-hrvat** [mullvad/mullvad-browser#163]
If this repository is a mirror of the one at torproject.org, why not just not accept Issues?
Currently, bug reports are dispersed and undesirable.

**Comment by ruihildt** [comment]
This repository exists for a few reasons:
- convenience: it's easier for some people to use their Github account to report issues (Tor Gitlab requires users to be manually approved)
- we don't want users to overload Tor Browser developers with Mullvad Browser issues, so in a way this repository acts as a first line of support
- keep all of Mullvad open source projects at the same place
- safety: it's better to have copy of the code in several places

When we started, we thought about how to optimize support for Mullvad Browser users, and we settled on this.
It's not out of the question to change this, but for now it seems to work good enough.
Tor Browser developers also keep an eye on the issues here from time to time.

Everyone is of course free to join Tor Gitlab if they prefer to open issues there. And I hope I have answered your question.
