### ISSUE TITLE
appImage version

### ISSUE THREAD

**Issue by HDInfautre** [mullvad/mullvad-browser#166]
Hi
Would it be possible to produce an appimage version?
The current installation is not easy for beginners and in addition an appimage version allows you to launch a portable version easily from an external SSD drive.
Please consider this request

**Comment by ruihildt** [comment]
An appImage version is not planned. Instead we'll try to make it in .deb, .rpm and flatpak.

**Comment by NearestWater262** [comment]
Can you please reconsider this? The options provided are not good at all for beginners to Linux. AppImage is best for them.

**Comment by jbjorkang** [comment]
There are Linux repos available for Ubuntu/Debian and Fedora listed on our download page: mullvad.net/download

**Comment by HDInfautre** [comment]
Hi
appimage leaves less trace in the system in portable mode.

**Comment by NearestWater262** [comment]
> There are Linux repos available for Ubuntu/Debian and Fedora listed on our download page: mullvad.net/download

Some people are very new to linux and don't want to configure repos and such. It turns people off from trying out linux. We as a linux community must stop doing gatekeeping!

**Comment by ruihildt** [comment]
We might reconsider it if there's a larger demand for it, but it would have a low priority anyway, because we have limited resources to allocate.

**Comment by ruihildt** [comment]
I would guess Tor Browser was released before AppImage were really a thing. Maybe if they started today, they would use an AppImage, but don't take my word for it.  I have no idea why they did things the way they did it, and if you're looking for answers, I would suggest you ask  them directly.

I don't feel qualified to discuss the merit of AppImage, and we'll happily ship AppImage for Mullvad Browser if Tor developers start doing it for Tor Browser (and it's totally possible they would accept an external contribution, please have this person contact me or the Tor devs if they want to discuss it).

Note: `dbus-glib` will not be required from Mullvad Browser 14.0. / Auto-update does work on Linux

**Comment by kevin0t** [comment]
Appimage is needed , i cannot install the deb package on linux mint

**Comment by ruihildt** [comment]
> Appimage is needed , i cannot install the deb package on linux mint

On Linux Mint, you can add our repository by following the instructions to add the repository, with a small change.
Instead of `$(lsb_release -cs)`, you add the code version for the Ubuntu used by Linux Mint. Currently it's `noble`.

**Comment by xmha97** [comment]
+1
