### ISSUE TITLE
A little suggestion

### ISSUE THREAD

**Issue by Alice1nCradle** [mullvad/mullvad-browser#170]
How about adding a feature just like what ClearURLs does?

Well, some website may add some tracking elements behind the original URL, and  of course it's trying to collect our personal information. What's worse, when I want to share a funny online video to my friends, I found that these tracking elements even include the device I used to watch this video, my current progress and even how many times I've shared this video…That's awful. It seems that I shared not only what I want to share.

Just like the URL Clean(https://urlclean.com/) said:

URLs copied from Google search results (such as links to PDFs) are more  complicated than they need to be. This tool removes the unnecessary  parts, leaving the page's original URL.

I wonder if we could add this feature or at least a filter of these tracking elements?   
Well, if you guys think it's not necessary, please tell me why and close this issue directly. 
Any prompt reply will be highly appreciated.

**Comment by iam-py-test** [comment]
Mullvad Browser comes with AdGuard URL Tracking Protection, which does some of this (but not everything).
I think the Google search results can be defeated by enabling uBlock Origin - Annoyances by default, but no idea if that has negative consequences.

**Comment by Alice1nCradle** [comment]
> Mullvad Browser comes with AdGuard URL Tracking Protection, which does some of this (but not everything). However, it only removes tracking parameters when you click a link/visit a website. I think the Google search results can be defeated by enabling uBlock Origin - Annoyances by default, but no idea if that has negative consequences. Thanks

Oh, I see, thank you. However, for example, when I watch a video on the https://www.bilibili.com, every link will let me redirect once and then add a tracking element : vd_source, someone use the rainbow table could find out the user's id from this tracking element, and this redirection will let AdGuard URL Tracking Protection not work. 
I wonder if I could customize the filter by myself in the future, and prevent redirection just like ClearURLs? Yesterday I try this addon on firefox and it can remove the vd_source by preventing its redirection.

**Comment by iam-py-test** [comment]
bilibili adds vd_source in a way which bypasses uBlock Origin (and thus AdGuard URL Tracking Protection). Also, it seems AdGuard's list doesn't remove that parameter anyway.

**Comment by Alice1nCradle** [comment]
> bilibili adds vd_source in a way which bypasses uBlock Origin (and thus AdGuard URL Tracking Protection). Also, it seems AdGuard's list doesn't remove that parameter anyway.

Wow, you replied quite rapidly! Thanks for your attention and hark work!
This issue will be closed.
