### ISSUE TITLE
Different windows installers released on github and website

### ISSUE THREAD

**Issue by ave9858** [mullvad/mullvad-browser#172]
The GitHub [latest release page](https://github.com/mullvad/mullvad-browser/releases/tag/13.0) contains only `mullvad-browser-windows-x86_64-install-13.0.exe`, which runs as admin and installs into Program Files. The version on [the website](https://mullvad.net/en/download/browser/windows) downloads `mullvad-browser-windows-x86_64-portable-13.0.exe` by default, which isn't on the GitHub release page and behaves like the previous versions.

**Comment by ave9858** [comment]
Just noticed the installable release can't auto-update

**Comment by ruihildt** [comment]
This is an oversight from our part: the install version is not supported and is a work in progress.

Thanks for pointing it out, we will update the releases.
