### ISSUE TITLE
Mullvad Browser's fingerprint is different from Tor Browser

### ISSUE THREAD

**Issue by 0x391F** [mullvad/mullvad-browser#18]
Mullvad Browser's fingerprint is different from Tor Browser, such as "features detection" result in https://browserleaks.com. 
We can test browser's fingerprint in below website:
https://browserleaks.com
https://coveryourtracks.eff.org

By the way, lots of addons will make browser's fingerprint different, a typical example is AD Blocker (uBlock Origin, etc.), so I hope Mullvad Browser only install NoScript (with the same setting as Tor Browser) and Mullvad Browser Extension by default, and warn user if install other addons, may let them easier distinguish from others.

**Comment by Thorin-Oakenpants** [comment]
Yes, because for starters they have enabled webRTC and media devices. The point is that mullvad browser provides the ability for users to form a crowd against advanced scripts

**Comment by 0x391F** [comment]
By the way, could Mullvad Browser add a "plus" version which have strictest restriction, and it have the same fingerprint as Tor Browser? It only have NoScript (with the same setting as Tor Browser) and Mullvad Browser Extension by default, and warn user if install other addons, will let them easier distinguish from others.

**Comment by Thorin-Oakenpants** [comment]
> By the way, could Mullvad Browser add a "plus" version

I doubt it. Too much work. I'm not sure if TB is going to add webRTC and media devices (I think they might), and for years I've wished they would add uBO (in locked down form to keep filters and users the same) to help reduce the tor network load and reduce latency - but there's a ethical question there - something about, it's not TB's mission to decide if ads are good or bad or deprive content creators of income. That said, reducing the attack surface, of ads, is always a good point. There's a tor ticket on it, been open for about seven years :)

PS: even if they did that, Mullvad Browser will still be different - the IP address is not a tor exit node, there are resource:// and chrome:// differences .. etc

You can't make different products look the same, so pointless. If they were made to look the same, then they are the same product! :)

**Comment by 0x391F** [comment]
In fact, AD Blockers is a type of fingerprint, if user install it to Tor Browser, it may let someone looks different from others. Test is available on https://browserleaks.com/proxy. 
About "the IP address is not a tor exit node", this is not a problem, user could use Mullvad VPN node or even connect directly, in this situation, we only need the resist fingerprinting feature, which introduce by Tor Project.

**Comment by Thorin-Oakenpants** [comment]
that's what I said. To look like MB vs TB, TB would need to add uBO because it can be fingerprinted - but it's a moot point.

The IP address is absolutely a problem - tor exit nodes are public, and tor browser can only use tor IPs and MB can't, end of story - but again, a moot point - see the other differences.

**Comment by yanagibashi-mt** [comment]
There's indeed no point in MB having the same fingerprint as TB, because you can already distinguish Tor users from non-Tor users just by IP. And that's also not the stated goal.

The only thing that matters is that MB itself has the same fingerprint for every user. It doesn't matter if uBO is installed or not for that, as long as every MB user is the same.

**Comment by ruihildt** [comment]
> I hope Mullvad Browser only install NoScript (with the same setting as Tor Browser) and Mullvad Browser Extension by default, and warn user if install other addons, may let them easier distinguish from others.

We don't plan to add other extensions. Introducing external codebase is always a privacy and security risk.

Currently, the NoScript configuration is slightly different from Tor's; Cross-tab Identity Leak Protection is disabled by default.
