### ISSUE TITLE
Temporarily set top-level sites to trusted

### ISSUE THREAD

**Issue by onkq** [mullvad/mullvad-browser#182]
The idea of hiding the NoScript add-on in the toolbar is great, but while setting the security level to _safer_, and clicking an element that has been blocked to allow it, does not work, and requires manually opening NoScript -> Clicking Temp-TRUSTED on the top level domain and reloading the site. Not convenient. Especially when the add-on is hidden by default.

**Comment by Thorin-Oakenpants** [comment]
https://forum.torproject.org/t/missing-no-script-in-toolbar/9985/2?u=thorin .. also see donut's reply

**Comment by Thorin-Oakenpants** [comment]
Yup, I kinda thought as much - NS is not my "thing" man :) Just thought it would be good to link some helpful info for others regardless. Let me try to summon someone

@hackademix

**Comment by hackademix** [comment]
Well, __in general__ clicking a `<video>` or `<audio>` element which has been blocked by NoScript should NOT require setting the top level domain to TRUSTED in order for it to play, _unless_ the site uses also some extra scripting to set up the stream - which, unfortunately, is less and less uncommon - and may not be limited to the top level domain :(

I could add a "More options..." button to the OK/Cancel ones in the dialog to open the "regular UI", but it seems quite niche for Tor Browser / Mullvad Browser users.

Little dirty secret: you can still easily access NoScript's UI by using the `ctrl+shift+N` keyboard shortcut or the contextual menu on the page.
