### ISSUE TITLE
Please enhance the cdn.mullvad.net server

### ISSUE THREAD

**Issue by elvis-hrvat** [mullvad/mullvad-browser#183]
It takes a very long time to download binaries from cdn.mullvad.net using cURL. Sometimes it times out and fails.
Please enhance your server so that it can download faster.

**Comment by jbjorkang** [comment]
Would you be able to give some idea of your set up to help us understand a bit more?

**If you are willing to share of course**

For example the following information:

Location (for example: "Singapore", "Los Angeles"):
Time taken:
VPN status:

We have two servers located in Sweden currently. We are looking to expand in the future of course.

**Comment by elvis-hrvat** [comment]
Hello,

Location: Hong Kong, Tokyo (Multi-hop)
Time taken: In a few minutes `curl: (18) Transferred a partial file` is displayed and exits
VPN status: connected

**Comment by elvis-hrvat** [comment]
I just tried it and found that it fails to download with an error.
No matter how many times I try, I am unable to download.
The same thing happens when I use Firefox instead of cURL. Is the server disconnecting?

**Comment by jbjorkang** [comment]
Thanks for this, it is also possible to download the installer from Github, these are the same as you find on our website, and are signed using Tor's signing key too.

That could be an interim solution.

**Comment by DPirate** [comment]
I am facing the same issue, trying to download from Indonesia. It has worked before multiple times but now download is failing repeatedly.

**Comment by jbjorkang** [comment]
The closest server is located in Singapore. If you're still having problems, another option is our Github page.
