### ISSUE TITLE
MB keeping track of recent opened files?

### ISSUE THREAD

**Issue by rideandrain** [mullvad/mullvad-browser#189]
I'm on MB (direct download - 13.0.4 (based on Mozilla Firefox 115.5.0esr)), up-to-date Fedora 38, KDE Plasma.

Under File > Open File, then Recent, MB is keeping a list of recent files opened through the browser. I have tried clearing history and data from settings, but this list still persists. I have also tried clearing recent file history from system settings, but given that its a direct download (and not installed, MB is not registered with the system, can't set it as default browser) that's expected I guess.

I'm unsure if this is just my system, as I'm also having issues clearing file history in Flatpaks. The recent file list from MB is distinct from other lists, it appears to only track files opened from the browser.

Will appreciate if other users could help check if this is consistent behavior across systems.

**Comment by ruihildt** [comment]
Thanks for the report, this seems to be a flatpack specific issue.
It seems flatpak has direct access to the native file picker (might be the wrong terminology).

As a reminder, we don't officially support flatpak (yet: #6 ).

**Comment by rideandrain** [comment]
To clarify, I am using the direct download of MB. However, around the same time I also observed a similar behavior (of distinct history tracking) from my flatpaks.

However, I've since found a workaround to clear flatpak history for KDE, and FWIW I can no longer reproduce in MB as well.
Given that no one else has commented, it might just be a "me" issue?
