### ISSUE TITLE
Crashes when opening extension popups

### ISSUE THREAD

**Issue by vars1ty** [mullvad/mullvad-browser#190]
The browser crashes when I try and open an extension popup, such as uBlock Origin, or the Mullvad extension.
OS is Arch Linux with Wayland using Hyprland.
https://github.com/mullvad/mullvad-browser/assets/54314240/6253b620-0746-4e51-9977-68f8e1af97fd

Edit: Note, all settings are stock, and it's using the Flatpak build. Everything was reset prior to recording the video.

**Comment by Thorin-Oakenpants** [comment]
see https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/42306

**Comment by voidastro4** [comment]
Tor Browser was issued an update to fix this, Mullvad browser has not received an update...

**Comment by ruihildt** [comment]
We're doing additional testing. As soon as this is completed, we'll release the version with this crash fix.

**Comment by voidastro4** [comment]
> @voidastro4 See: https://github.com/mullvad/mullvad-browser/releases/13.0.6
> 
> Can you confirm it fixes the issue?

I can confirm.

**Comment by vars1ty** [comment]
Any ETA for when the flatpak will be updated, so I can close this issue?

**Comment by ruihildt** [comment]
> Any ETA for when the flatpak will be updated, so I can close this issue?

The flatpak is a community based effort. We have plans to officially support it, but it's not ready yet.
