### ISSUE TITLE
Mullvad Browser is sometimes unusable due to the proxy extension not working

### ISSUE THREAD

**Issue by AutonomousCat** [mullvad/mullvad-browser#193]
Sometimes the proxy I use goes down and I am unable to change it because this window does not let me set another. It persists across restarts as well.

![image](https://github.com/mullvad/mullvad-browser/assets/130127508/75849bc0-0f89-4474-896e-265a850c509a)

**Comment by ruihildt** [comment]
Any specific reason the "Disconnect proxy" doesn't enable you to change server?

I guess we could store the last proxy updates and offer to change from there as well. But if it's the VPN and not the proxy which is down, it might be misleading.

**Comment by ruihildt** [comment]
This is fixed by `0.9.0`, you can now always access the proxy tab and enable/disable/switch any proxy.
