### ISSUE TITLE
File name...?

### ISSUE THREAD

**Issue by ioc2e3** [mullvad/mullvad-browser#194]
Ask for a place...

What is the difference between ( mullvad-browser-windows-x86_64-portable-13.5a2.exe ) and ( mullvad-browser-windows-x86_64-portable-13.5a2.exe.asc ) ?

File name of (portable) ...

Does that is Portable version ?

**Comment by ruihildt** [comment]
`.asc` file is a signature. You can use it to verify the build has not been tampered with.

See: https://mullvad.net/en/help/verifying-mullvad-browser-signature?q=signature

**Comment by ioc2e3** [comment]
> portable

As for...

What does ( portable ) in the file name mean?

**Comment by ruihildt** [comment]
"portable" means it is mostly self-contained in the folder. It is not installed in Program Files and won't register on the system (outside the shortcuts).

This is in opposition to a non-portable version, which is in the work and will be available at some point.

**Comment by ruihildt** [comment]
Yes, you can move it around in your windows system, and it will launch from there. You could also move it to another windows system and it will run from there as well.

**Comment by ioc2e3** [comment]
Thanks for the note

**Comment by Thorin-Oakenpants** [comment]
FYI: there are actually issues with portable geckos - namely extension bits and bobs are not always relative paths

**Comment by ioc2e3** [comment]
> ... 這與非便攜版本相反，非便攜版本正在開發中，並將在某個時候推出。

Still hope ...

here ( https://github.com/mullvad/mullvad-browser/releases ) ...

here ( https://mullvad.net/en/download/browser ) ...

To continue to provide portable version ...

.

**Comment by ruihildt** [comment]
> > ... non-portable version, which is in the work and will be available at some point.
> 
> Still hope ...
> 
> here ( https://github.com/mullvad/mullvad-browser ) ... here ( https://mullvad.net/download/browser ) ...
> 
> To continue to provide portable version ...
> 
> .

The portable version is now called "standalone mode" and is available on install by selecting "Advanced".
