### ISSUE TITLE
Option to disable IPv6

### ISSUE THREAD

**Issue by AutonomousCat** [mullvad/mullvad-browser#195]
I would like to disable IPv6 in Mullvad Browser as my Wireguard configuration purposely has no IPv6 address. I found an unset "ipv6" boolean item in about:config, but setting it to false doesn't do anything it seems.

**Comment by ruihildt** [comment]
@AutonomousCat After a cursory search, it seems that to disable IPv6, you can flip the pref `network.dns.disableIPv6` to `true`.

But in general, we don't want to change Firefox settings which have no impact than privacy and branding.
If you find something that works in Firefox but not in Mullvad Browser, we will of course investigate.
