### ISSUE TITLE
Upgrading Mullvad VPN breaks open Mullvad Browser session

### ISSUE THREAD

**Issue by ave9858** [mullvad/mullvad-browser#196]
Upgrading from Mullvad VPN 2023.5 to 2023.6 while connected to the VPN will cause an opened Mullvad Browser to be unable to connect to the internet after the VPN connection is reopened in the upgraded app. When attempting to quit the browser, it will freeze in the background and eventually crash. Other open apps like Brave or `ping 1.1.1.1 -t` reconnect to the internet normally after the Mullvad VPN app update is complete.

Tested on Windows 10 19044.3693, Mullvad Browser version 13.0.6

**Comment by ruihildt** [comment]
Couldn't reproduce. Feel free to open a new ticket if problem still exists.

**Comment by ave9858** [comment]
I can still reproduce but this seems to be an upstream firefox issue
