### ISSUE TITLE
Package not signed by the usual key

### ISSUE THREAD

**Issue by mdPlusPlus** [mullvad/mullvad-browser#2]
The browser package is signed by `E53D989A9E2D47BF`, but the fingerprint of the provided key by Mullvad is `D5A1D4F266DE8DDF`

https://mullvad.net/media/mullvad-code-signing.asc  
https://mullvad.net/en/download/browser/linux64/latest  
https://mullvad.net/en/download/browser/linux64/latest/signature

```
$ LANG=en_US gpg --verify mullvad-browser-linux64-12.0.4_ALL.tar.xz.asc 
gpg: assuming signed data in 'mullvad-browser-linux64-12.0.4_ALL.tar.xz'
gpg: Signature made Thu Mar 30 19:15:54 2023 CEST
gpg:                using RSA key E53D989A9E2D47BF
gpg: Can't check signature: No public key
```

**Comment by linprof** [comment]
seems to be signed by tor project's key

**Comment by harabat** [comment]
@ruihildt are you also able to clarify this on <https://mullvad.net/en/download/browser/linux>/macOS/etc.? Assuming that most users will be downloading the browser from mullvad.net and following the instructions there?

![mullvad_browser](https://user-images.githubusercontent.com/45575009/229592058-29980d1e-d501-4833-b9f2-35513d6831aa.png)
