### ISSUE TITLE
Browser Icon

### ISSUE THREAD

**Issue by simpvn** [mullvad/mullvad-browser#20]
Hello, I've been Mullvad VPN user for 2 years now and I love the new browser so far.

However I would love for Mullvad to provide different browser icon because personally, I think the app icon looks very weird and hard to recognize as a browser.

**Comment by ruihildt** [comment]
We don't have plans to change the browser icon.

But it is possible to customize the icon on most platforms on your own system if you wish to do so.

**Comment by emacsomancer** [comment]
@simpvn re: user-customised icons, perhaps see [https://gitlab.com/emacsomancer/unofficial-mullvad-browser-icon](https://gitlab.com/emacsomancer/unofficial-mullvad-browser-icon) for some (including svg sources, so they could be bettered/improved/spun-off)

e.g. 

<img width="512" height="512" alt="Image" src="https://github.com/user-attachments/assets/dab0b78b-bee8-47af-8546-ff198344de10" />

<img width="512" height="512" alt="Image" src="https://github.com/user-attachments/assets/4b8d9dd4-088a-4b24-aab6-3e40dc73e0f7" />
