### ISSUE TITLE
Add rpm/deb package repositories?

### ISSUE THREAD

**Issue by abmusse** [mullvad/mullvad-browser#201]
Any plans to add package repositories for MB like we have for Mullvad VPN?

Ref: https://mullvad.net/en/blog/introducing-package-repositories-for-ubuntu-debian-and-fedora

This would streamline installing and updating mullvad browser on Linux.

**Comment by rufusprice** [comment]
+`

**Comment by ruihildt** [comment]
We will add a repository when the .deb and .rpm packages become available.
You can follow the state of the Tor Project regarding the .deb and .rpm package development here:

- https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/28
- https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/29

**Comment by ruihildt** [comment]
@souchikjoardar201 This issue was closed because there is now a .deb package in the alpha channel.

`.deb` will be supported in the Mullvad Browser 13.5 stable release. (`.rpm` should come in the next alpha)

**Comment by ruihildt** [comment]
ℹ️  Deb and rpm packages are now available through our repositories.

These packages are designed exclusively for installation via our repositories to ensure automatic updates.
Installing them directly bypasses this mechanism, and **you won't receive in-browser notifications about new updates**.

To add the repositories to Fedora/Ubuntu/Debian, follow the instructions on the [download page](https://mullvad.net/en/download/browser/linux).
