### ISSUE TITLE
Rendering glitches on Wayland

### ISSUE THREAD

**Issue by planetoryd** [mullvad/mullvad-browser#204]
![2023-12-23_04-44](https://github.com/mullvad/mullvad-browser/assets/68096727/7597f058-5e0b-4b8f-abda-0f332c3d650e)

It happens a lot.

I'm using `Exec=env MOZ_ENABLE_WAYLAND=1 ./start-mullvad-browser.desktop` on 13.0.7 on linux `6.6.7-200.fc39.x86_64 `

# 2

Playing videos on reddit became impossible

![image](https://github.com/mullvad/mullvad-browser/assets/68096727/8d732fe5-c19a-45dd-9b6d-4e4dd78e4b68)

Turning off uBlock doesn't work. I have no other interfering addons. 

![image](https://github.com/mullvad/mullvad-browser/assets/68096727/e6062ca4-dbec-4315-abf2-6c60a55380ff)

**Comment by planetoryd** [comment]
[prefs.tar.gz](https://github.com/mullvad/mullvad-browser/files/13756672/prefs.tar.gz)

**Comment by planetoryd** [comment]
I fixed the NS_BINDING_ABORTED problem by installing openh264

**Comment by ruihildt** [comment]
@planetoryd Can you try downloading the [Mullvad Browser Alpha 14.0a4](https://github.com/mullvad/mullvad-browser/releases/tag/14.0a4) and see if you still have the wayland glitches?

Thanks!
