### ISSUE TITLE
Changing fingerprint defending method

### ISSUE THREAD

**Issue by Tre-brock** [mullvad/mullvad-browser#208]
Instead of making a group all have the same fingerprint make everyone have a randomized fingerprint instead. So every new tab would have a different fingerprint. This would be more effective because even if everyone had the same fingerprint like currently, there are still small difference. But if it was random they you would be different each time. I think the extension "jshelter" could do this well when set to the scrict setting. Also making it so when you click reset identidy, it changed your proxy server.

**Comment by Thorin-Oakenpants** [comment]
All randomizing can be detected, so it's a moot point. The only [1] benefit from randomizing is that scripts that don't bother to check get sucked in. Tor Browser takes the stance of assuming the worst and doesn't waste and resources time randomizing. That said, a few areas we could randomize cheaply are worth it, IMO - https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/42235 - especially now upstream at Mozilla they have engineered it (i.e see below, protecting the seed)

[1] There are other benefits such as compat - e.g canvas - a subtlely randomized canvas, and you would persist the seed per eTLD+1, per session/id, per window type (private, normal, container) to protect the seed, wouldn't render the image unusable. But that also comes with downsides, such as averaging
