### ISSUE TITLE
Cannot add a new certificate.

### ISSUE THREAD

**Issue by Giger22** [mullvad/mullvad-browser#209]
Hello, I am trying to test the Mullvad browser using this instructions:
[DigDeeper-mitmproxy](https://digdeeper.neocities.org/articles/liftingtheveil) but I cannot add a new certificate. I tried using the Librewolf and I had no problems.

**Comment by Thorin-Oakenpants** [comment]
TB/MB disables it - from arkenfox info

```js
/* 5005: disable intermediate certificate caching [FF41+] [RESTART]
 * [NOTE] This affects login/cert/key dbs. The effect is all credentials are session-only.
 * Saved logins and passwords are not available. Reset the pref and restart to return them ***/
   // user_pref("security.nocertdb", true);
```

**Comment by Giger22** [comment]
Ok, I did not know. Closed.
