### ISSUE TITLE
'[: : Integer expression expected' when trying to run

### ISSUE THREAD

**Issue by mjdNjhNJ** [mullvad/mullvad-browser#210]
**Configuration**
Fedora Linux Asahi Remix 39
Apple M2

**Problem**
When trying to run the browser using command `./start-mullvad-browser.desktop --register-app` the prompt fails with errors:
![image](https://github.com/mullvad/mullvad-browser/assets/129977466/7aa63298-8813-4d35-834e-1f11db823b5e)

Maybe corresponds with [this](https://github.com/AsahiLinux/docs/wiki/Broken-Software) problem?

**Comment by ruihildt** [comment]
Mullvad Browser is not yet supported on ARM platform. To follow the progress, see https://github.com/mullvad/mullvad-browser/issues/11
