### ISSUE TITLE
Why including NoScript when uBlock Origin is more flexible and more efficient?

### ISSUE THREAD

**Issue by MrChocolatine** [mullvad/mullvad-browser#213]
I have searched existing issues, some talk about NoScript but not exactly like this issue.

Everything is in the title: what is the point of having NoScript AND uBlock Origin? Why not just uBlock Origin?
The latter is far more flexible, with more features, and I believe can do what NoScript does. (blocking JS, fonts, medias, ...)

On other browsers I have been using uBlock Origin in [hard mode](https://github.com/gorhill/uBlock/wiki/Blocking-mode:-hard-mode) and when using Mullvad Browser I really don't see the value of NoScript.

On Mullvad Browser I have also set uBO in hard mode, and whenever I have to adjust settings for a certain website I have to do it twice, for uBlock Origin and NoScript. This is really tedious.

Would you care to explain please? I may be missing something, I am no expert in this specific domain.

**Comment by Thorin-Oakenpants** [comment]
>  I really don't see the value of NoScript ...  I am no expert in this specific domain

it's integral to TB/MB's strategy - e.g. at a minimum it's integrated with security settings - but it does more than that

**Comment by MrChocolatine** [comment]
> it's integral to TB/MB's strategy - e.g. at a minimum it's integrated with security settings - but it does more than that

If that confirms NoScript really has a usefulness, all right, at least I am "reassured".

> Edit: also uBO will most likely get locked down

How's that? Users not able to configure uBO, add rules etc?

**Comment by ruihildt** [comment]
> If that confirms NoScript really has a usefulness, all right, at least I am "reassured".

Yes I can confirm. Also the NoScript developer is also working on Tor Browser and Mullvad Browser.

**Comment by MrChocolatine** [comment]
Great to know 👍 .

**Comment by Thorin-Oakenpants** [comment]
> How's that? Users not able to configure uBO, add rules etc?

its under discussion - https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/164

**Comment by MrChocolatine** [comment]
May I ask what NoScript brings that uBO does not? Of course I am not trying to push my idea "let's get rid of NoScript", not at all, I am just curious and interested.

From my little understanding (and now, thanks to you, I see I was wrong) I thought uBO could easily surpass NoScript, if configured accordingly.

Is there some kind of comparison out there?

**Comment by ruihildt** [comment]
NoScript powers the Security levels features, which is why it is mandatory.

I am not aware of a comparison between the two, but it might exist.
