### ISSUE TITLE
Download fails with SSL_ERROR_SYSCALL

### ISSUE THREAD

**Issue by elvis-hrvat** [mullvad/mullvad-browser#215]
When I try to download https://cdn.mullvad.net/browser/13.0.7/mullvad-browser-linux-x86_64-13.0.7.tar.xz via cURL, I get `OpenSSL SSL_read: SSL_ERROR_ SYSCALL, errno 0` and the download fails.
Can this problem be fixed?

**Comment by ruihildt** [comment]
Only the latest versions of Mullvad Browser are kept on the CDN, this is why this link is not working.

If you want to access this specific version, you can find it in the archives: https://archive.torproject.org/tor-package-archive/mullvadbrowser/

May I ask you where you found this link? Is it a dead link somewhere?
