### ISSUE TITLE
Drawbacks of Picture In Picture mode?

### ISSUE THREAD

**Issue by ghost** [mullvad/mullvad-browser#216]
I've noticed mullvad browser has picture in picture mode disabled, enabling the following flag allows it to work flawlessly. 

media.videocontrols.picture-in-picture.enabled = true

Are there any privacy concerns by enabling this flag and, if not, please consider enabling it in future releases.

**Comment by pospeselr** [comment]
upstream issue with some context: https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40147

**Comment by ruihildt** [comment]
This has now been fixed with the Mullvad Browser 14.0 release.

See: https://github.com/mullvad/mullvad-browser/releases/tag/14.0
