### ISSUE TITLE
Add a Nix package

### ISSUE THREAD

**Issue by Parrot7483** [mullvad/mullvad-browser#22]
Title says it all. 

Nix is a tool that takes a unique approach to package management and system configuration. Nix packages are reproducible, declarative and reliable. 

The package definition is probably very similar to [Firefox](https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/applications/networking/browsers/firefox/wrapper.nix#L404) or [Tor](https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/applications/networking/browsers/tor-browser-bundle-bin/default.nix#L420).

**Comment by ruihildt** [comment]
Mullvad Browser is indeed reproducible, like Tor Browser.
When it's built, it's actually check for reproducibility by the Tor Browser developers.

We will look into further distributing Mullvad Browser at some point in the future.

**Comment by felschr** [comment]
I've created a PR to add Mullvad Browser to nixpkgs: https://github.com/NixOS/nixpkgs/pull/225322
It's based on the distributed archive, though and not built from source.

**Comment by ruihildt** [comment]
Closing as a Nix package has been made available. Belated thanks @felschr !

Please note this is a community effort.
