### ISSUE TITLE
Enable tab containers by default

### ISSUE THREAD

**Issue by mlario** [mullvad/mullvad-browser#220]
Hi,

Tab containers are very useful in isolating different identities on the same browser profile and session

Could you please enable it by default?

This requires deactivating private browsing, and using clearing cache, cookies, history on browser shutdown

as well as activating set privacy.userContext.enabled to true

this would be same as in arkenfox or librewolf

thanks!

**Comment by Thorin-Oakenpants** [comment]
this is impossible because containers are not compat with PB mode - they weren't engineered that way. PB mode is technically and literally a container - i.e you can't have a container in a container

**Comment by mlario** [comment]
then the question is, are separate tabs with PB isolated from each other - like cookies, cache, etc?

**Comment by mlario** [comment]
also just as a concept, will there be an impact for browser uniqueness/blending into crowd if manually disabling PB, setting sanitization upon browser closing, and setting set privacy.userContext.enabled to true ?

Thanks

**Comment by Thorin-Oakenpants** [comment]
> are separate tabs with PB isolated from each other

no - they all share the same contextual (container) id. In FF, if you start in normal mode, when you open a PB mode window, every subsequent PB mode window is the same until they are all closed, after which it sanitizes (memory)

> will there be an impact for browser uniqueness

yes - it will make you stand out. You cannot hide your window mode, although the lines for this are becoming less blurred, it's taken years (upstream at mozilla) and we're still not there. To be clear, the goal at mozilla is not to make the two modes identical to fingerprinting, it is to make PB mode more compat friendly and less discriminated against by websites whilst still protecting session data isolation and disk "leaks" - so long story short, I can see a future where they might be indistinguishable in TB/MB but it will never happen in FF itself (long story, let's not get into it)

**Comment by ruihildt** [comment]
As answered here, containers are not supported because Mullvad Browser uses the Private Browsing Mode.
