### ISSUE TITLE
Links from external application do not open in mullvad even if it set as default browser

### ISSUE THREAD

**Issue by mlario** [mullvad/mullvad-browser#222]
Please add %U at the end of EXEC command in .desktop file (....... --detach %U)

this way links could be actually opened in mullvad

this issue was mentioned before: https://discussion.fedoraproject.org/t/mullvad-browser-does-not-open-external-links/80520

**Comment by ruihildt** [comment]
Making Mullvad Browser as default is planned, and you can follow the related issues:
- Windows: https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/87
- Linux: https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/233

**Comment by digitalmagicgit** [comment]
https://github.com/mullvad/mullvad-browser/issues/289

**Comment by ruihildt** [comment]
This has now been fixed with the Mullvad Browser 14.0 release.

See: https://github.com/mullvad/mullvad-browser/releases/tag/14.0
