### ISSUE TITLE
Mullvad DNS.

### ISSUE THREAD

**Issue by Giger22** [mullvad/mullvad-browser#223]
Here:
https://github.com/safing/portmaster/issues/1437
`then they probably don't do their actual DNS but probably cache the answers for longer - the indication is that you see some domains but not all.`
So does Mullvad dns have any bug? Is it supposed to use cache? For domains that are not blocked I see p2p connection. Alternative is using https://all.dns.mullvad.net/dns-query to block more hosts but it is very convenient to have your own filter list.

**Comment by ruihildt** [comment]
While we use Mullvad DNS in the browser, I'm not able to answer questions about their implementation.

Please contact support@mullvadvpn.net, they'll be able to help.
