### ISSUE TITLE
Ublock Origin crashes after restarting the browser and does not update

### ISSUE THREAD

**Issue by serial02** [mullvad/mullvad-browser#226]
Hey guys

Ublock Origin crashes after restarting the browser and does not update.

You need to enter the Ublock Origin settings and reset to the default configuration, where all settings already made are lost.
I pulled a log and the information is this:

`Fontconfig warning: "/home/edson/.local/share/mullvad-browser/Browser/fontconfig/fonts.conf", line 42: Use of ambiguous path in <dir> element. please add prefix="cwd" if current behavior is desired.`

If a new image appears of the error presented, I will edit the post

Edited: Below are images of Ublock Origin crashing after configuring it and restarting the browser.  Everything locks, the options are unchecked and it is only possible to return to normal after reset

![Captura de tela de 2024-02-16 17-02-52](https://github.com/mullvad/mullvad-browser/assets/32621790/83d2a17d-6ab5-45e7-af60-d8ee79cf8374)

![Captura de tela de 2024-02-16 17-02-35](https://github.com/mullvad/mullvad-browser/assets/32621790/46a1b16a-14a4-42c7-93b0-4a556c8dedfa)

**Comment by ruihildt** [comment]
Thanks, I will report that to the devs.

**Comment by serial02** [comment]
> Thanks, I will report that to the devs.

Hello

 Mullvad Browser was updated successfully, but the problem with the native Ublock Origin continues to be problematic as can be seen in the image below:


![Captura de tela de 2024-02-20 15-31-33](https://github.com/mullvad/mullvad-browser/assets/32621790/447d695e-cd7f-448f-bbaa-32fd9f586bab)


![Captura de tela de 2024-02-20 15-31-42](https://github.com/mullvad/mullvad-browser/assets/32621790/4d6fcc26-26b0-48ea-8609-a7e1148f9d8e)

**Comment by serial02** [comment]
> Thanks, I will report that to the devs.

Hello

 Apparently this problem was resolved in version 13.0.10.

![Captura de tela de 2024-02-22 17-19-02](https://github.com/mullvad/mullvad-browser/assets/32621790/b61d485b-3feb-4d65-b005-3438e4243ba3)


However, the option to remove an element from Ublock Origin is no longer available in the application or in the browser's context menu.  See the images below.  Does it still need any corrections?

![image](https://github.com/mullvad/mullvad-browser/assets/32621790/1a6b203f-57e7-4777-9a80-0f9c4c52bfb4)

**Comment by ruihildt** [comment]
> However, the option to remove an element from Ublock Origin is no longer available in the application or in the browser's context menu. See the images below. Does it still need any corrections?

This is actually an update from uBlock Origin, which remove the element picker when the "My filters"  list is toggled off from the "Filters list".

See screenshot:
![image](https://github.com/mullvad/mullvad-browser/assets/13787166/c9d3a992-a359-47be-9ed3-0f1afc8adb11)
