### ISSUE TITLE
Folder issue with third-party `mullvad-browser-bin` AUR package

### ISSUE THREAD

**Issue by kulukrok** [mullvad/mullvad-browser#229]
when the browser is started a folder named *UpdateInfo* is created in `/home/user/` by default. my version is `mullvad-browser-bin` from `aur` (arch-linux user repository). this is far from useful for obvious reasons. that folder should go to `.` domain, wherever appropriate.

**Comment by Giger22** [comment]
Also after an update it does not update the file in /user/UpdateInfo/updates/.. It still show "pending".

**Comment by ruihildt** [comment]
@foter @Giger22 Please note that the packages from the `aur` are community provided, and we don't offer support for it.

Could you please contact the `mullvad-browser-bin` maintainer and pass your comments directly to them?

**Comment by foter** [comment]
@ruihildt of course, sorry for the confusion.

**Comment by terminal-root** [comment]
Disabling auto-updates (`about:config` > `app.update.auto`) fixed the issue for me (so far).

**Comment by pospeselr** [comment]
This is being tracked upstream: https://aur.archlinux.org/pkgbase/mullvad-browser-bin/

**Comment by terminal-root** [comment]
@pospeselr I know, just was putting that there for people who end up here like I did. I commented upstream, too.
