### ISSUE TITLE
Images with lines

### ISSUE THREAD

**Issue by Zepfanman** [mullvad/mullvad-browser#230]
Almost daily, I come across websites that render images as lines instead of the proper image/overlay. This affects/breaks my own photo/image uploads sometimes, too.

E.g. (1) https://www.themoviedb.org/movie/1018474-a-trip-through-japan-with-the-ywca

Mullvad 13.0.10 on Windows 11
![image](https://github.com/mullvad/mullvad-browser/assets/8905819/d3363caf-3dd7-461e-91d6-2cb1566707ec)

vs. Firefox 123.0.1 on Win11
![image](https://github.com/mullvad/mullvad-browser/assets/8905819/ed13187e-eee9-4e49-8733-e3294e101cc0)

E.g. (2) I also took this test here and the pdf of the results is almost completely lines https://embrace-autism.com/raads-r/#test
![image](https://github.com/mullvad/mullvad-browser/assets/8905819/7f1b815f-b16a-49a9-a66f-9b272c38e9e6)

**Comment by Thorin-Oakenpants** [comment]
https://github.com/arkenfox/user.js/wiki/3.3-Overrides-[To-RFP-or-Not]#-rfp

**Comment by Zepfanman** [comment]
Ahh, okay, that explains the address bar button alternative, thanks.

**Comment by Thorin-Oakenpants** [comment]
> canvas: you can set a site exception either temporarily or permanently

in Tor Browser and Mullvad Brower the exception is temporary
