### ISSUE TITLE
uBO filters at zerohedge.com fail to activate when importing from Firefox etc

### ISSUE THREAD

**Issue by nadesco** [mullvad/mullvad-browser#231]
Even though the following rules show up in the `My filters` pane after importing to Mullvad, they're not activated when visiting the website <https://www.zerohedge.com> for some reason. 

! [page overlay]
www.zerohedge.com##.ExitModalNewsletter_visible__zAGqx.ExitModalNewsletter_exitModalOverlay__yzG4m
www.zerohedge.com##.Header_sticky__btH7b.Header_mobileContainer__3FO__

! (Top-right side bar)
www.zerohedge.com##.TheMarketEarHomePageSidebar_container__dCIOv

! (Premium Member banner directly above first article)
www.zerohedge.com##.Banner_banner__6PLuA

! (Banner just above Comments section - causes Comments button not to show?)
www.zerohedge.com##.MidArticleNewsletter_midArticle__SM8uv 
www.zerohedge.com##.MidArticleNewsletter_midArticle__tresV

! https://www.zerohedge.com
www.zerohedge.com##.SponsoredPost_nonStickyContainer__KtiGp
www.zerohedge.com##.SponsoredPost_sponsored__ulMyN

! (Small ads at bottom of VBL articles)
www.zerohedge.com##.button-wrapper.node__content > .field__item.field--label-hidden.field--type-text-with-summary.field--name-body.field.text-formatted.clearfix
www.zerohedge.com##.file-embed-details-h2 > .field__item.field--label-hidden.field--type-text-with-summary.field--name-body.field.text-formatted.clearfix > .file-embed-wrapper > .file-embed-container-reader > .file-embed-container-top > .file-embed-details > .file-embed-details-h2

! (pop-up newsletter)
www.zerohedge.com##.ExitModalNewsletter_exitModal__VM_9U
www.zerohedge.com##.ExitModalNewsletter_visible__YnGkR.ExitModalNewsletter_exitModalOverlay__5JqqU
www.zerohedge.com##.Banner_banner__l_dym

! [In EasyPrivacy filter: Exception (add @@) to keep 'number of page views']
@@||zerohedge.com/statistics-ajax?

! [Added @@|| Otherwise ZH doesn't always load properly.]
@@||d2c4ylitp1qu24.cloudfront.net
@@||www.zerohedge.com
@@||zerohedge.com

! 2023-03-18 https://www.zerohedge.com
www.zerohedge.com##.TopPosts_posts__kSDL7

! 2023-04-12 https://www.zerohedge.com
www.zerohedge.com##.SgWebinarPromoBanner_banner__TbgHQ

! 2023-04-13 https://www.zerohedge.com
www.zerohedge.com##.SponsoredPost_nonStickyContainer__GIJ_u
www.zerohedge.com##.SponsoredPost_sponsored__zzGA6

! 2023-10-05 https://www.zerohedge.com
www.zerohedge.com##.PromoBanner_banner__Rr3Jp

! https://zerohedge.com (ad window directly above Show Comments link)
zerohedge.com##.Recirculator_container__w7Z_e
www.zerohedge.com##.Recirculator_container__w7Z_e

zerohedge.com##+js(aeld, scroll)

**Comment by gorhill** [comment]
These cosmetic filters target elements which have variable parts in their class name, these parts are different on my side, so your filters probably no longer match elements on the page. You need to craft filters which target the non-variable parts, for example:

    zerohedge.com##[class*="ExitModalNewsletter_exitModalOverlay__"]

**Comment by nadesco** [comment]
That worked okay. The example you gave was useful. Thanks!
