### ISSUE TITLE
Easiest way to migrate profile/settings to different drive?

### ISSUE THREAD

**Issue by Zepfanman** [mullvad/mullvad-browser#241]
I have two drives on my laptop, Windows 11. I've been using Mullvad Browser on the HDD (D:\Program Files) for a while. What's the easiest way to migrate it to my SSD (C:)? I'm hoping for better performance. Thanks!

**Comment by ruihildt** [comment]
@Zepfanman You should be able to follow the Firefox documentation to move the profile: https://support.mozilla.org/en-US/kb/back-and-restore-information-firefox-profiles

Are you using the standalone install or the regular one?
If you're using the regular one, you should:
- backup your profile
- uninstall Mullvad Browser
- reinstall while choosing the new location on C:
- move the backed up profile to the new location
- delete the old profile in D:
