### ISSUE TITLE
Certain devtool functions store website information in about:config 

### ISSUE THREAD

**Issue by GlowingUmbreon** [mullvad/mullvad-browser#243]
If you use inspect element/devtools on mullvad browser it is possible for certain information to be stored onto the disk in about:config.

The two examples I have are below;
devtools.netmonitor.customRequest - It appears it stores any request you make within the network monitor. The information stored in this config can be a full HTTP request and could potentially include information that you do not want storing on disk such as passwords or tokens.
devtools.debugger.pending-selected-location - It appears to potentially store breakpoint locations for different scripts.

**Comment by ruihildt** [comment]
I asked the developers about it and here's the answer:

> IIRC we've had other similar issues in the past but decided devtools were out of scope since they (in general) do not respect private browsing mode. I suspect there's a lot of stuff here that persists.
>
> Next steps would probably be to identify all the various leaks, and open upstream bugs with Mozilla.

See: https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/347

**Comment by ruihildt** [comment]
Additional comment:

> devtools.netmonitor.customRequest was already fixed and uplifted ([tor-browser#41881 (closed)](https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41881)). The user might have an old profile.
