### ISSUE TITLE
Add Bitcoin/Lightning Payment Method to Reduce Payment Friction & Fees

### ISSUE THREAD

**Issue by alltheseas** [mullvad/mullvad-browser#246]
Operating system: Initially web (mullvad.net), and later suggest adding directly to Mullvad Browser (zap & browse privately!). 

## User Story

As a Mullvad user or prospective user who would like to quickly top up my account using sats, I would like the capability to pay via Bitcoin's Layer 2 Lightning Network, so that I can reduce my payment friction & fees, AND instantly receive a confirmation of my BTC payment via LN to Mullvad.

### Acceptance Criteria
1. Mullvad user has a way to pay via Lightning (⚡ ) on mullvad's website, and this is visible under payment methods. Mockup:
![image](https://github.com/mullvad/mullvad-browser/assets/64376233/7c48a8e0-f201-4116-af10-3f47cc1ba06a)

2. Implementation suggestion: utilize one-time [Bolt11 invoice generated](https://www.bolt11.org/) for customer specified amount (see FOSS [BTCPayServer](https://github.com/btcpayserver) implementation. BTCPayServer is used by lightning.store)

3. Amount specific (see 2.) LN invoice address is displayed and copy-able to clipboard (copy functionality)

4. QR code is automagically generated, which contains LN invoice address (see 3.; see [lightning.store](https://lightning.store/) pay with LN example below)

5. Open in wallet option leads to system default BTC/LN wallet, and automagically transposes LN invoice via copy paste

6. User receives feedback visual "Payment Received" confirmation (e.g. via modal or other method) as soon as LN⚡ payment is received.

![image](https://github.com/mullvad/mullvad-browser/assets/64376233/8c2a4952-c8e4-4219-b807-fcd35fa48e4c)

### context

1. Why now? Mempool fees can be in the tens of dollars - which is a few months of Mullvad service. See snapshot from on-chain fee L1 estimator mempool.space below

![Screenshot from 2024-04-18 16-35-01](https://github.com/mullvad/mullvad-browser/assets/64376233/8c73ef65-757e-45bc-a2d2-fb6b795935b8)

2. Previously submitted [this issue to the mullvad iOS repo](https://github.com/mullvad/mullvadvpn-app/issues/4435), and also sent an email to support at mullvadvpn net.

**Comment by owen1917** [comment]
+1 for this feature. Onchain Bitcoin payments are unsustainable long term. Additionally it is causing users to revert to using 3rd party solutions like [this](https://vpn.sovereign.engineering/), which doesn't feel right from a user perspective.

**Comment by ruihildt** [comment]
There's no plan to integrate any payment method to the browser.

**Comment by alltheseas** [comment]
What's the best place to leave feedback for the website payments page?

**Comment by ruihildt** [comment]
> What's the best place to leave feedback for the website payments page?

Same answer as in https://github.com/mullvad/mullvadvpn-app/issues/4435 :
please contact [support@mullvadvpn.net](mailto:support@mullvadvpn.net).
