### ISSUE TITLE
Make repository accessible as an onion service

### ISSUE THREAD

**Issue by EclipseBazooka** [mullvad/mullvad-browser#247]
This would make it so that Apt *package manager* would handle the verification of the .deb 
instead of having to download and verify with gpg each time which is what the package manager already does anyway.

### Also another option great option would be having an onion respository option

*example*

* Brave Browser 
> Has an onion repository option (they dont tell you how though)
>
> https://brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion/linux/index.html 

* Tor Debian Repository
> Has an onion repositry option (they document how to set it up)
>
>https://support.torproject.org/apt/

#### What the documentation would look something like on website:

```
# Download the Mullvad signing key
sudo curl -fsSLo /usr/share/keyrings/mullvad-keyring.asc https://repository.mullvad.net/deb/mullvad-keyring.asc

# Install Tor requirements for using apt
sudo apt install tor apt-transport-tor
sudo systemctl start tor.service && sudo systemctl enable tor.service 


# Add the Tor Mullvad repository server to apt
echo "deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=$( dpkg --print-architecture )] tor://repository.o54hon2e2vj6c7m3aqqu6uyece65by3vgoxxhlqlsvkmacw6a7m7kiad.onion/deb/stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/mullvad.list
# Or add the Mullvad BETA repository server to apt
echo "deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=$( dpkg --print-architecture )] tor://repository.o54hon2e2vj6c7m3aqqu6uyece65by3vgoxxhlqlsvkmacw6a7m7kiad.onion/deb/beta $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/mullvad.list

# Install the package
sudo apt update
sudo apt install mullvad-vpn
```

**Comment by ruihildt** [comment]
Repositories are already planned for repositories, see: https://github.com/mullvad/mullvad-browser/issues/201.

We have not had request to make the repositories accessible as onion services though, I will forward your feedback to our team.

**Comment by ruihildt** [comment]
It is not planned to make the repository accessible as a Tor onion service.
