### ISSUE TITLE
"secure connection failed" message not useful

### ISSUE THREAD

**Issue by jficz** [mullvad/mullvad-browser#248]
Some sites produce a "secure connection failed" message (see image) even though other browsers (including Mull desktop counterparts like Librewolf) have no issue with the site.

The message says "contact website owner" but it doesn't say anything useful about the actual problem and reporting such issue with the (lack of) available information would be a waste of time of both the reporter and the site admin at best.

The error message should point to what the issue is, otherwise it's useless, especially in respect to Mull's buffed security which possibly introduces more corner cases.

![Screenshot_20240419-185359_Mull](https://github.com/mullvad/mullvad-browser/assets/10010448/db572a49-9e2b-4311-928f-d73f81712221)

**Comment by jficz** [comment]
Sorry, wrong project.

**Comment by ruihildt** [comment]
No worries, have a good day. :)
