### ISSUE TITLE
Mullvad browser works on much lower MacOS versions than advertised

### ISSUE THREAD

**Issue by 0n** [mullvad/mullvad-browser#250]
![Screen Shot 2024-04-21 at 4 18 43 PM](https://github.com/mullvad/mullvad-browser/assets/45835056/d568c08f-bbc7-495f-b515-2df48ccb2979)

**Comment by ruihildt** [comment]
Mullvad Browser might work on more platforms than advertised.

As we don't test those, we can't provide support or any guarantee that it runs correctly.
