### ISSUE TITLE
Bug: cookie exception is cleared on browser restart

### ISSUE THREAD

**Issue by levinberg** [mullvad/mullvad-browser#255]
Mullvad Browser after recent update clears sites that are added to cookie exception. The cookies are kept however, until the second restart. By restart I am *not* referring to "new identity" option. I mean simply closing the browser (Quit from menu) and and reopening it as one would.

Platform: Linux
Version: 13.0.15 (based on Mozilla Firefox 115.11.0esr)

**Steps to reproduce**

- Create a new profile
- Go to about:preferences#privacy and turn off "*Always use private browsing mode*"
- Check "*Remember browsing and download history*"
- Check "*Clear history when Mullvad Browser closes*. Click on the settings button and confirm everything except "*Site settings*" is checked to be cleared upon exit. This is similar to what arkenfox does by default and persists cookie exception.
- Add any webpage to your cookie exception and press save.
- When you reopen the browser, the cookie of that webpage (if there were any set) will be kept. You can confirm that via "*Manage data*" button that is on top of "*Manage exception*".
- However, now if you check "*Manage exception*" panel, it does no longer contains your whitelisted site. If you close the browser this time, your cookie will be gone.

I have been using Mullvad Browser with this settings for quite a while and I never had this problem before. For now as workaround I unchecked the "Delete cookies and site data on close" option altogether.

**Additional comments**

1. I haven't confirmed whether the bug exists with upstream tor browser.
2. I am aware it could be considered bad practice to set cookie exception in a tor-like browser. But I am keeping the main profile intact. Use a new profile to isolate certain services that I am not comfortable opening in my primary browser to keep myself signed in for quick access. I suppose there is no problem with that.

**Comment by Thorin-Oakenpants** [comment]
> Go to about:preferences#privacy and turn off "Always use private browsing mode"

Mullvad Browser does not support this configuration (yet), and they are aware of the friction that Private Browsing mode causes. They are working hard on a solution with Tor Project, and are also aware of UI inconsistencies (such as the one mentioned) which should be hidden until/if supported.

**Comment by ruihildt** [comment]
Closing, as this is not a supported way of using the Mullvad Browser.
