### ISSUE TITLE
Cookies and site data exceptions not persisted

### ISSUE THREAD

**Issue by yannickperrenet** [mullvad/mullvad-browser#258]
I was under the impression that I could specify the exact cookies and site data that I don't want deleted (likely because the `Manage Exceptions` button is lined-up with the `Delete cookies...` checkbox). For example, I want to stay logged-in to particular services. 

Furthermore, whenever I restart the browser the entered exceptions are lost. I don't feel like entering them for every browser session I have.

![image](https://github.com/mullvad/mullvad-browser/assets/26223174/3eead701-d71c-4d0d-9ff4-4c680c2ebe9f)

### Questions

1. Am I correct in thinking that I can specify the cookies that I want to persist, i.e. not-deleted?
2. Why are exceptions not persisted?

Thank you!! :smile_cat:

**Comment by ruihildt** [comment]
Closing as duplicate of #29
