### ISSUE TITLE
uBlock origin: `Enter Element Zapper mode` doesn't create a small window at bottom right

### ISSUE THREAD

**Issue by lamyergeier** [mullvad/mullvad-browser#263]
uBlock origin: `Enter Element Zapper mode` doesn't create a small window at bottom right

**Comment by Thorin-Oakenpants** [comment]
zapp mode does not have a window, it just zapps when you click on an element

But if you right click on an element and choose `Block element`, _then_ you get to set **_cosmetic filters_** and you have a window bottom right (or left I assume if RTL).

This action is only via `Block element...` not zapper
![cosmetic](https://github.com/mullvad/mullvad-browser/assets/16656956/e35a7ef2-504e-4480-af15-0c080262a93c)

This context menu option to `Block element...` is not present in uBO on MB - I assume we turned it off cc @hackademix

**Comment by ruihildt** [comment]
> This context menu option to Block element... is not present in uBO on MB - I assume we turned it off

This is because by default Custom Filters are not enabled in uBO settings.
When you enable them, the context menu option does appear.

Closing as this is not an issue, but a misunderstanding on how uBO filtering works.

**Comment by Thorin-Oakenpants** [comment]
related
- https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/229
- https://github.com/mullvad/mullvad-browser/issues/127
