### ISSUE TITLE
Can't update nor Install Mullvad Flatpak due to erros during install

### ISSUE THREAD

**Issue by mateowoetam** [mullvad/mullvad-browser#264]
I was recently trying to update my flatpaks and got an error regarding the Mullvad browser, I tried installing again and see if that would fix it and got the same issue, now unable to install it:

I have attached the issue as a file.
[Mullvad-Install_issues-fp.txt](https://github.com/user-attachments/files/15907130/Mullvad-Install_issues-fp.txt)

**Comment by ruihildt** [comment]
The flatpak is a community package and we don't provide support for it.

Please contact the maintainer directly: https://github.com/flathub/net.mullvad.MullvadBrowser

**Comment by ruihildt** [comment]
I created an issue for you there: https://github.com/flathub/net.mullvad.MullvadBrowser/issues/45
