### ISSUE TITLE
"Your MullvadBrowser profile cannot be loaded. I may be missing or innaccessible" error with flatpak

### ISSUE THREAD

**Issue by bugerkin** [mullvad/mullvad-browser#265]
![Screenshot from 2024-06-20 00-59-30](https://github.com/mullvad/mullvad-browser/assets/87587767/3859e351-15ef-4f6e-a55a-de316c4a9037)

![Screenshot from 2024-06-20 01-06-45](https://github.com/mullvad/mullvad-browser/assets/87587767/43f27f93-f031-4830-a24c-a666cfd92ba1)

I will be able to provide additional info upon request (with commands if need) in-case this isn't enough info.

**Comment by ruihildt** [comment]
The flatpak is a community package and we don't provide support for it.
Please contact the maintainer directly: https://github.com/flathub/net.mullvad.MullvadBrowser

Note that there's already an issue opened that might or might be the one you're encountering: https://github.com/flathub/net.mullvad.MullvadBrowser/issues/45

**Comment by bugerkin** [comment]
Is it possible to install the .deb file from github and allow the browser to auto update?

**Comment by ruihildt** [comment]
> Is it possible to install the .deb file from github and allow the browser to auto update?

No, I just added a notice on top of the release, because unfortunately we've encountered issues while setting up the repositories and it will take some time to fix them.

> 
> ⚠️ We're currently facing unexpected issues that have delayed the addition of .deb and .rpm packages to our repositories.
> 
> These packages are designed exclusively for installation via our repositories to ensure automatic updates.
> Installing them directly bypasses this mechanism, and you won't receive in-browser notifications about new updates.
> 
> We've chosen to withdraw these packages until further notice, apologies for any inconvenience caused.

**Comment by bugerkin** [comment]
Is it possible to get notified when there's a new release?

If so then how would I remove the current version then install the most recent version. (via .deb)

**Comment by ruihildt** [comment]
I'll reopen this issue until the issue is fixed to make it visible for other users encountering the error.

**Comment by ruihildt** [comment]
> It doesn't mention any breaking changes

I'm very sorry, I opened an issue upstream, see: https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/313
