### ISSUE TITLE
mullvad-browser missing from fedora/ubuntu/debian repository

### ISSUE THREAD

**Issue by piotrowskiadam** [mullvad/mullvad-browser#266]
I followed manual from:
[https://mullvad.net/en/help/install-mullvad-browser](https://mullvad.net/en/help/install-mullvad-browser)

Added repo via:
`sudo dnf config-manager --add-repo https://repository.mullvad.net/rpm/stable/mullvad.repo`
but then when trying to do:
`sudo dnf install mullvad-browser`
It gives me output of:
`Last metadata expiration check: 0:00:35 ago on czw, 20 cze 2024, 12:10:14.
No match for argument: mullvad-browser
Error: Unable to find a match: mullvad-browser`

**Comment by ruihildt** [comment]
We're currently facing unexpected issues adding the .deb and .rpm packages to our repositories.
A warning has been added to our installation guide and on top of the Github release.

![image](https://github.com/mullvad/mullvad-browser/assets/13787166/22d89d0d-4ac4-4ce9-be9c-fbb773f87b58)

I'll keep this issue open until the .deb and .rpm packages are available in the repositories.

**Comment by ruihildt** [comment]
ℹ️  Deb and rpm packages are now available through our repositories.

These packages are designed exclusively for installation via our repositories to ensure automatic updates.
Installing them directly bypasses this mechanism, and **you won't receive in-browser notifications about new updates**.

To add the repositories to Fedora/Ubuntu/Debian, follow the instructions on the [download page](https://mullvad.net/en/download/browser/linux).
