### ISSUE TITLE
Dark theme not working

### ISSUE THREAD

**Issue by matthewblott** [mullvad/mullvad-browser#271]
Mullvad's theme is set to the system theme but this isn't working. I'm on macOS and have dark theme set. If I switch Mullvad to the dark theme specifically this still does not work. This is also the case if I try and set the dark theme for YouTube and other sites. I have added youtube.com and other sites to the cookies exception list but this hasn't worked either. Please advise :-)

**Comment by ruihildt** [comment]
Dark theme in the browser will only change the browser user interface. The page content will always use the clear theme.

This is a feature: unfortunately dark mode is fingerprintable.

**Comment by matthewblott** [comment]
Ah, okay thanks for the response. Probably not gonna work for me then, I have dark mode on everything. My eyes hurt otherwise :-)
