### ISSUE TITLE
Unable to download the browser through the repository

### ISSUE THREAD

**Issue by ruihildt** [mullvad/mullvad-browser#273]
> ℹ️ Deb and rpm packages are now available through our repositories.
> 
> These packages are designed exclusively for installation via our repositories to ensure automatic updates. Installing them directly bypasses this mechanism, and **you won't receive in-browser notifications about new updates**.
> 
> To add the repositories to Fedora/Ubuntu/Debian, follow the instructions on the [download page](https://mullvad.net/en/download/browser/linux).

@ruihildt Maybe a separate issue, but it looks like the mullvad cdn is down so I'm unable to download. Tried both downloading the app using the Mullvad repository option, and the manual installation option. 

EDIT: I used the instructions [here](https://mullvad.net/en/download/vpn/linux)

_Originally posted by @truescotian in https://github.com/mullvad/mullvad-browser/issues/133#issuecomment-2189394565_

**Comment by ruihildt** [comment]
@truescotian Can you confirm for which platform you're downloading?

What happens if you click on the following link?

@truescotian Can you confirm what happens if you click on this link?

https://mullvad.net/en/download/browser/linux-x86_64/latest

**Comment by truescotian** [comment]
@ruihildtIt looks like this resolved itself, I'm able to download the .deb now and verified I can download signing keys. Maybe a brief outage? FWIW I was using chromium on Rasbian Bookworm at the time, and trying to download ARM64 .deb package

**Comment by ruihildt** [comment]
It seems ti was a temporary issue, closing.
