### ISSUE TITLE
Extensions Still Broken After 9 Months

### ISSUE THREAD

**Issue by issuant** [mullvad/mullvad-browser#274]
Beginning even before #178 was opened, the Metamask extension has been broken in Mullvad Browser. With every update since, I've diligently rechecked its status and nothing has changed. The problem hasn't even been acknowledged aside from a generic label addition in March. 

As noted in other comments there, it's not a Firefox issue because the extension works in other forks. The problem is also not isolated to Metamask as https://enkrypt.com's extension essentially has a seizure trying to use it with Mullvad Browser. It's hard for this to ever be a default browser option if extensions remain broken for this long: https://mullvad.net/en/blog/mullvad-browser-135-released-with-letterboxing-improvements-and-new-installation-options

**Comment by tjex** [comment]
Also can't use any extension so far that requires a login (which includes NordVPN). I have a very limited understanding of browser security, so from a laymans point of view, this seems like "ultra secure", but I also want to use my computer... 

So for me at this point, it seems like Mullvad can't be a "daily" driver for the regular user and has no place being set as the default browser like many users are recommending (imagine the onslaught of issue reports by regular users who just think their extensions are broken!! - [like me](https://github.com/WorldBrain/Memex/issues/1279) 😇). It's more of a security anxious user who's happy with forgoing a multitude extensions.

**Comment by ruihildt** [comment]
Closing this in favor of #178. (You'll find a more detailed post there as well.)
