### ISSUE TITLE
Add the EV status cert info tho the address bar (Regression feature request)

### ISSUE THREAD

**Issue by eonlineok** [mullvad/mullvad-browser#276]
Hi all, The certificate information in the address bar because all the sites looks same, the financial or governmental institutions as other institutions must be shown in the address bar the EV status, because as I said before all the net look the same and is not the same.

“In desktop Firefox 70, we intend to remove Extended Validation (EV) indicators from the identity block (the left hand side of the URL bar which is used to display security / privacy information). We will add additional EV information to the identity panel instead, effectively reducing the exposure of EV information to users while keeping it easily accessible,” Johann Hofmann of Mozilla said."

This from Mozilla and is a wrong decision in a wrong direction.

Please consider this before close it.

**Comment by ruihildt** [comment]
Hi thank you for your feedback.

We're not going to to anything different from Mozilla (or basically all the other browsers), since EV certificates have been shown to be more effective or better solve issues from other valid certificates.
