### ISSUE TITLE
connects to internet by itself. where and why?

### ISSUE THREAD

**Issue by mailinglists35** [mullvad/mullvad-browser#278]
<img width="1157" alt="Untitled" src="https://github.com/mullvad/mullvad-browser/assets/2054302/2a73eb59-6aef-41f9-92d7-5d98561cd03c">

**Comment by mailinglists35** [comment]
<img width="1157" alt="Untitled" src="https://github.com/mullvad/mullvad-browser/assets/2054302/a8c5e8f9-ef5e-4ba3-8370-cb5a851c8a84">

**Comment by mailinglists35** [comment]
45.149.104.1
151.101.241.91
185.199.111.153

**Comment by mailinglists35** [comment]
172.66.44.77

**Comment by mailinglists35** [comment]
172.67.73.29

**Comment by mailinglists35** [comment]
185.199.108.153

**Comment by mailinglists35** [comment]
188.114.96.0
35.185.44.232

**Comment by mailinglists35** [comment]
199.232.25.229
172.66.47.179

**Comment by mailinglists35** [comment]
<img width="1206" alt="Untitled" src="https://github.com/mullvad/mullvad-browser/assets/2054302/65e4028d-467d-4d07-a749-85f5f27ad985">

**Comment by mailinglists35** [comment]
<img width="1206" alt="Untitled" src="https://github.com/mullvad/mullvad-browser/assets/2054302/fd8f1d7c-7836-4bf0-937f-036dae7f52dd">

**Comment by mailinglists35** [comment]
https://github.com/mullvad/mullvad-browser/assets/2054302/55f9bfed-8456-4c44-94d2-89c27e9ea2a0

**Comment by ruihildt** [comment]
Mullvad Browser makes a number of outgoing connections, which are listed here: https://mullvad.net/en/help/tag/mullvad-browser#93

This is what you're seeing here. If you notice that some of the connections are not from the one listed there, please open another issue, with the steps to reproduce.

**Comment by PieroV** [comment]
Also, Wireshard might be more helpful, as it will also show the SNI (all the connections are expected to be HTTPS, so at least you'll see the Server Name Indication).

Hostnames are also reported in about:networking.
