### ISSUE TITLE
Zoom not consistent between pages

### ISSUE THREAD

**Issue by tydog98** [mullvad/mullvad-browser#282]
Zoom in on a site, click a link on the same site and the zoom level is reset. Zoom level should be maintained.

**Comment by Thorin-Oakenpants** [comment]
RFP ignores site settings (where zoom info lives) and specifically enforces 100% zoom - especially on new tabs and new eTLD+1

**Comment by ruihildt** [comment]
This is a browser fingerprint protection, so even if inconvenient, we're gonna keep it.
