### ISSUE TITLE
Change gorhill extension for another

### ISSUE THREAD

**Issue by eonlineok** [mullvad/mullvad-browser#284]
Consider change the gorhill extension for another or better a built-in ad-blocker since nobody knows how gorhill finances his projects. This way the browser go to be more confidence in terms of transparency and privacy.

**Comment by ruihildt** [comment]
uBlock Origin is free software and its track record in terms of decision is immaculate.

We currently have no reason to stop trusting it and we value gorhill work as well as the work from all volunteers maintaining blocking lists.

**Comment by 0c0d3** [comment]
It takes only a few seconds to see how this is nonsensical -- keep in mind that this "was manually reviewed by the Mozilla Add-ons team":

    "For add-ons that collect or transmit user data, the user must be informed and provided with a clear and easy way to control this data collection"
    Where is the "data collection" in this file?
        https://github.com/uBlockOrigin/uBOL-home/blob/uBOLite_2024.9.1.1266/firefox/web_accessible_resources/googlesyndication_adsbygoogle.js
    "Your add-on contains minified, concatenated or otherwise machine-generated code"
    Where is the "minification" in these files?
        https://github.com/uBlockOrigin/uBOL-home/blob/uBOLite_2024.9.1.1266/firefox/web_accessible_resources/fingerprint2.js
        https://github.com/uBlockOrigin/uBOL-home/blob/uBOLite_2024.9.1.1266/firefox/web_accessible_resources/google-analytics_analytics.js
        https://github.com/uBlockOrigin/uBOL-home/blob/uBOLite_2024.9.1.1266/firefox/web_accessible_resources/google-analytics_ga.js
        https://github.com/uBlockOrigin/uBOL-home/blob/uBOLite_2024.9.1.1266/firefox/web_accessible_resources/googletagservices_gpt.js
    "Also, if your add-on is listed on addons.mozilla.org, the listing needs to include a privacy policy, and a summary of the data collection should be mentioned in the add-on description."
    Right, it's always been there since the first version published on AMO more than a year ago
        https://github.com/user-attachments/assets/350bc17c-53e2-401a-91a0-2a321337c49e

https://github.com/uBlockOrigin/uBOL-home/issues/197#issuecomment-2377395301

Good luck with that.

All the best.

**Comment by ruihildt** [comment]
Ah well, we're using uBO and not uBO Lite, so thankfully it doesn't impact us.
