### ISSUE TITLE
favicons saved when sites are bookmarked 

### ISSUE THREAD

**Issue by ruihildt** [mullvad/mullvad-browser#285]
> Anyone noticed MullvadBrowser saves favicons when sites are bookmarked sometimes? Could this be a privacy implication?

**Comment by Thorin-Oakenpants** [comment]
so like any stored (state) data, it can be abused for tracking - but IIUIC due to a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1618257), this is not feasible in FF
