### ISSUE TITLE
Unable to updade the browser through the repository?

### ISSUE THREAD

**Issue by hipolitorodrigues** [mullvad/mullvad-browser#286]
Yesterday, I couldn't update using "$ apt update". It's still the same way now. 
I'm using Debian 12.5 on one PC and Pop!_OS 22.04 on another. The same issue occurs on both.

I noticed that PING 45.149.104.1 it's ok.

![Captura de tela de 2024-07-27 14-15-57](https://github.com/user-attachments/assets/f8f70243-ee3b-4cc5-b80b-d5d63fe5078d)

**Comment by ruihildt** [comment]
If there are additional issues with the repository, please contact support@mullvadvpn.net.
