### ISSUE TITLE
Links don't open properly on Linux when Mullvad Browser is set as default

### ISSUE THREAD

**Issue by digitalmagicgit** [mullvad/mullvad-browser#289]
Doesn't work properly in linux.

To get it to work correctly, you need to modify the shortcut by adding the %u parameter in one of three places
 /home/user/.local/share/applications/start-mullvad-browser.desktop 

Exec=sh -c '"$(dirname "$*")"/Browser/start-mullvad-browser --detach **%u** || ([ ! -x "$(dirname "$*")"/Browser/start-mullvad-browser ] && "$(dirname "$*")"/start-mullvad-browser --detach **%u**)" dummy %k **%u**

Full instructions:

1) download and unzip the browser
2) run it with the --register-app parameter
3) modify the created shortcut by adding the %u parameter to it
4) execute xdg-settings set default-web-browser start-mullvad-browser.desktop

that's it, now it's default, links from other applications are opened and no repositories are needed.

**Comment by digitalmagicgit** [comment]
https://github.com/mullvad/mullvad-browser/issues/42

**Comment by digitalmagicgit** [comment]
https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/87
https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/233

**Comment by ruihildt** [comment]
This is the corresponding issue:

https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/334

**Comment by ruihildt** [comment]
This has now been fixed with the Mullvad Browser 14.0 release.

See: https://github.com/mullvad/mullvad-browser/releases/tag/14.0
