### ISSUE TITLE
Automate Browser to Use Mullvad DNS when No Mullvad VPN is connected

### ISSUE THREAD

**Issue by amztc34283** [mullvad/mullvad-browser#291]
I am not sure if this is implemented already or not, but sometimes I want to access websites that blacklisted Mullvad Servers and have to disable the VPN.

Since Mullvad VPN is already using Mullvad DNS, I wonder if there could be a VPN detection so that when VPN is disabled, the DNS will be used automagically.

Any thoughts on this?

**Comment by justin025** [comment]
You could just set the browser to use mullvad's doh in settings

**Comment by amztc34283** [comment]
Thank you, it is very helpful.

In addition, can I connect to Mullvad's proxy servers without using Mullvad VPN?
Looks like there was a similar discussion in Mullvad App: https://github.com/mullvad/mullvadvpn-app/issues/4361

**Comment by justin025** [comment]
Not that I am aware of. If you'd like to use the browser without the vpn you have to disable the proxy.

**Comment by ruihildt** [comment]
As answered, Mullvad Browser ships with Mullvad Encrypted DNS (DOH) by default.
It's not possible to use Mullvad proxy without being connected to Mullvad VPN*.

_* Technically you can achieve this, but it's not recommended as it's complex to setup and easy to shoot yourself in the foot._
