### ISSUE TITLE
Cookies are not displayed in the Cookie Editor extension

### ISSUE THREAD

**Issue by eta66** [mullvad/mullvad-browser#296]
![1](https://github.com/user-attachments/assets/60cee4e7-043f-441b-9cbb-b154124fb936)
![2](https://github.com/user-attachments/assets/acb5c262-104b-4a0c-93f0-79e760ad4157)

https://addons.mozilla.org/en-US/firefox/addon/cookie-editor/

**Comment by morganava** [comment]
Confirmed for me in 13.5a9. As a work-around I can confirm https://addons.mozilla.org/en-US/firefox/addon/cookie-quick-manager/ works.

**Comment by Thorin-Oakenpants** [comment]
probably the extension not handling FPI
