### ISSUE TITLE
Mac app modified date incorrect 

### ISSUE THREAD

**Issue by martinvandiemen** [mullvad/mullvad-browser#297]
Seems something in your build workflow for macOS sets the build date for the app to Januari 1, 2000. It seems there is sometime wrong with the date and time during the build. Could you please fix this? For security reasons the app might seems to be outdated.
<img width="944" alt="image" src="https://github.com/user-attachments/assets/a3db16c5-654f-4500-b85c-c84160f14102">

**Comment by morganava** [comment]
@martinvandiemen this is most likely one of our build reproducibility measures.
