### ISSUE TITLE
version lags behind

### ISSUE THREAD

**Issue by tomByrer** [mullvad/mullvad-browser#299]
Your latest release, v15.5.2 , has "Updated Firefox to 115.14.0esr", & was released 3 weeks ago.
But the actual ESR version is "[128.1.0 August 6, 2024](https://www.mozilla.org/en-US/firefox/128.1.0/releasenotes/)", almost a month ago.
Such an old version is very concerning, not only make me think that Mullvad is behind on security, but will block me from using newer webapps that require latest tech.  I understand you may have a limited budget, so limiting scope to ESR versions make sense, but holding onto a 14 month old upstream version is baffling. 

Edit: Also, having a browser that is older than "Extended Service Release" can be a fingerprint in itself.

**Comment by Thorin-Oakenpants** [comment]
https://whattrainisitnow.com/calendar/

When base browser (the 99% bits in common in Tor Browser and Mullvad Browser) has to jump ESR releases, which are a year apart, there is a lot of rebasing to do including build chains etc. And a lot of auditing to be done. ESR releases have a three (or four) month overlap for enterprises to prepare. This is not something Tor Project can churn out in a day or two.

Meanwhile, the stable version is up to date with security patches and is still maintained by Mozilla - and in fact is until October 1st (when ESR115.15 reaches end of life). So no, it's not behind.

**Comment by tomByrer** [comment]
Handy link!

But can't most of the auditing be completed (mostly) via automation?  There has to be some way to containerize Puppeteer along with Wireshark/etc?

**Comment by Thorin-Oakenpants** [comment]
We always support ESR until EOL in stable, so we always have a 3 month window in which to audit and patch etc. We don't need puppeteer/wireshark - we can always rebase on upstream rapid release

We are looking at two windows. The 3 month ESR transition, and the remaining 9 months. What we want to do in that 9 month window, is
- catch up on auditing upstream changes and then maintain it - so at least that part is not left as a year's worth - this way we will have a list of items ready to go
- do rapid release rebases version by version to sort out other issues (we did that this cycle, but not until FF128 was in beta, from memory)

However, that's all about reducing the amount of work needed to be done in that 3 month window, to give us a head start. It doesn't mean we can move up the change in stable between ESR versions. We really do need 3 months of alpha and testing - but who knows, maybe it could move up a month if we're lucky (there's no rule per se that says we HAVE to wait until EOL, but we do need to be mindful of deprecated systems - e.g. this time round ESR115 is the last for windows 7/8 and macOS < 10.15)

**Comment by morganava** [comment]
@tomByrer see my blog post from the 14.0a2 release for more info on what exactly it is we're doing over the summer:
- https://blog.torproject.org/new-alpha-release-tor-browser-140a2/

And as @Thorin-Oakenpants alluded to, the goal for this coming release cycle (i.e. 14.5 due Spring of 2025) is to also be doing a lot of the audit, re-base, and bug-fixing work throughout the year, rather than waiting until the ESR transition is upon us to start the work. It's been a few years coming, but we've *almost* paid back all the relevant technical debt for this to even be possible.
