### ISSUE TITLE
Distribute the Mullvad Browser through homebrew

### ISSUE THREAD

**Issue by ruihildt** [mullvad/mullvad-browser#3]
> would be nice if you get it into homebrew for macos users so they can just do brew install mullvad-browser

**Comment by jeifour** [comment]
Homebrew needs some mechanism to check for newer versions. GitHub Releases page can work, but the download link URL seems to not be predictable very well. Currently it is: `https://github.com/mullvad/mullvad-browser/releases/download/mullvad-browser-102.9.0esr-12.0-2-build1/MullvadBrowser-12.0.4-macos_ALL.dmg`

Something like `https://github.com/mullvad/mullvad-browser/releases/download/v12.0.4/MullvadBrowser-12.0.4-macos_ALL.dmg` would work better. And of course it should be consistent for all GitHub releases.

**Comment by ruihildt** [comment]
This is the endpoint that the browser will check for updates: `https://cdn.mullvad.net/browser/update_responses/update_1/release/downloads.json`.

You can rely on that. In very rare circumstances, this link could be updated from `update_1` to `update_2`, etc.

**Comment by jeifour** [comment]
My attempt: https://github.com/Homebrew/homebrew-cask/pull/144444 Waiting for review now.

**Comment by jeifour** [comment]
Merged https://github.com/Homebrew/homebrew-cask/commit/c7d44cd3b497b4154e534543bebeda7a3572860f You may want to consider adding additional alternative installation instructions for macOS on your download page (but depends on how much you trust the Homebrew project I guess). Something along the lines of:

Install with Homebrew Cask
brew install --cask mullvad-browser

**Comment by ruihildt** [comment]
Thanks a lot! I'll will check with the team if that is something we would do.
