### ISSUE TITLE
Cannot Open Second/Multiple Windows On Linux

### ISSUE THREAD

**Issue by deron-dev** [mullvad/mullvad-browser#300]
System Info
```
OS: Artix Linux x86_64
Kernel: 6.10.6-artix1-1
Shell: zsh 5.9
WM: sway
```

Mullvad Browser Version (from nix-unstable)
```
Mullvad MullvadBrowser 115.14.0esr
```

Also tested `Mullvad MullvadBrowser 115.14.0esr` from this repo's releases.

When I try to open a second Mullvad Browser window, several seconds go by, then a window this message appears.

```
MullvadBrowser is already running, but is not responding. To use MullvadBrowser, you must first
close the existing MullvadBrowser process, restart your device, or use a different profile.
```

**Comment by PieroV** [comment]
Is it possible you're passing `-no-remote` in the command line argument?
That will prevent a new process from connecting to the existing one, and eventually this will be the result.

**Comment by deron-dev** [comment]
I normally run variants of

```
mullvad-browser --new-window -P <profile> <url>
```

but the default `mullvad-browser` (both from Nix and this repo's releases) behaves similarly.

**Comment by deron-dev** [comment]
Good to know, thanks @PieroV.

The `start-mullvad-browser` has the same behavior.

![image](https://github.com/user-attachments/assets/197dc6c4-97db-4827-92bf-ea4109f6452f)

**Comment by PieroV** [comment]
I tried to replicate in an Artix Mate live image (no sway image is available :unamused:), but I couldn't reproduce.
Do you have a way to test in a clean configuration? E.g., a new VM with a similar config to yours.
Also, could you please test with the current alpha (14.0a3)?

**Comment by deron-dev** [comment]
`14.0a3` behaves the same. I will test on a new Artix VM using the [`artix-base-runit-20240823-x86_64.iso`](https://artixlinux.org/download.php#official) image :+1:.

Here is a portion of my env, in case it is relevant.

<details><summary>my env</summary>

```
ELECTRON_OZONE_PLATFORM_HINT=auto
QTWEBENGINE_CHROMIUM_FLAGS=-blink-settings=darkModeEnabled=true -enable-features=OverlayScrollbar,OverlayScrollbarFlashAfterAnyScrollUpdate,OverlayScrollbarFlashWhenMouseEnter
QT_QPA_PLATFORMTHEME=gtk2
QT_SCALE_FACTOR=1.5
QT_STYLE_OVERRIDE=gtk
WAYLAND_DISPLAY=wayland-1
WINDOWID=102811671114384
XCURSOR_SIZE=24
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_CLASS=user
XDG_SESSION_ID=1
XDG_SESSION_TYPE=wayland
XDG_VTNR=1
_=/usr/bin/env
__HM_SESS_VARS_SOURCED=1
```

</details>

**Comment by deron-dev** [comment]
It is now working. I believe the only significant things I have done since this issue is start launching sway with `dbus-run-session sway` and add the following line to my Sway config.

```
exec dbus-update-activation-environment DISPLAY XAUTHORITY WAYLAND_DISPLAY
```

I did these while working on an issue with the Steam Flatpak.
