### ISSUE TITLE
'Potential Identity Leak' Using Ctrl-Click

### ISSUE THREAD

**Issue by issuant** [mullvad/mullvad-browser#301]
A strange 'Potential Identity Leak' NoScript modal shows up every so often when using Ctrl-Click on links to a different webpage. Having never used NoScript until this browser, I do not know what the text is really supposed to imply.

```
You are about to load a page from otherwebsite.com.

If you are a otherwebsite.com logged-in user, information about your identity might be acquired by thiswebsite.com.

[ ] Load anonymously
[ ] Load normally
```

How is this supposed to work? Are tabs not sandboxed or is that only true of Chromium-based browsers? I do not normally use NoScript but its a default integration in the browser and although I would genuinely rather remove it and buff the uBlock Origin settings, I have read that is ill-advised.

**Comment by Thorin-Oakenpants** [comment]
> Are tabs not sandboxed

IANAE on this, but first, domains are isolated by first party. This is not the same thing as sandboxing. IIUIC processes are sandboxed, not domains or tabs. And the number of processes is finite.

What NoScript is doing here, and hackademix can confirm or correct, is protecting against a form of XSS (cross site scripting) which is not about sandboxing at all - but IANAE

**Comment by hackademix** [comment]
Explained here: https://noscript.net/usage/#crosstab-identity-leak-protection
