### ISSUE TITLE
Random MB Crashes

### ISSUE THREAD

**Issue by rideandrain** [mullvad/mullvad-browser#302]
Over the past 3 weeks or so, MB has been crashing randomly on me. Happens on various websites and after various durations, can't isolate a pattern or obvious cause.

This has happened both while watching YT, as well as when doing general browsing or scrolling without YT at all.
Has happened as quickly as 3 mins, might be as long as after 2 hours of general browsing.

Any advice on how to troubleshoot? Frankly not even sure if its a MB specific issue, but it only happens to MB, FF works as expected.
Does MB capture any crash logs? Could I manually enable it for now?

I'm on the direct download version of MB
MB 13.5.2 (based on Mozilla Firefox 115.14.0esr)
Linux Fedora 40, KDE, Nvidia 560 drivers.

**Comment by ruihildt** [comment]
I have created an issue for the devs directly, see: https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/345

**Comment by rideandrain** [comment]
Closing as I can no longer repro. Not really sure what happened or what fixed it, but MB has been stable for the past week or so.

**Comment by ruihildt** [comment]
Thanks for the report!
