### ISSUE TITLE
Running issues of Mullvad Browser on Raspberry Pi

### ISSUE THREAD

**Issue by JinZhaoLin** [mullvad/mullvad-browser#303]
Please provide support for the Raspberry Pi 5. I purchased it specifically to use with Mullvad and Mullvad Browser for my work, as I need to quickly switch SD cards, destroy system cards, and use it on the go. However, after assembling it, I found that I am unable to install or run Mullvad Browser. I am hesitant to use third-party modified versions of Mullvad Browser.

**Comment by PieroV** [comment]
Hi, Mullvad Browser doesn't officially support aarch64 (the CPU architecture Raspberry Pi >= 3 are based on).
