### ISSUE TITLE
Mullvad browser - RPM repository - checksum doesn't match

### ISSUE THREAD

**Issue by piotrowskiadam** [mullvad/mullvad-browser#304]
Mullvad browser - RPM repository - checksum doesn't match

I tried to install update on fedora after having a message in Software center that there is an update but it cannot install and when doing it via terminal I got the output:
```

=====================================================================================================
 Package                    Architecture      Version                Repository                 Size
=====================================================================================================
Upgrading:
 mullvad-browser            x86_64            13.5.3-1               mullvad-stable            121 M

Transaction Summary
=====================================================================================================
Upgrade  1 Package

Total download size: 121 M
Is this ok [Y/n]:
Downloading Packages:
[MIRROR] mullvad-browser-stable_x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 5a9d8878101d78969a85700f755581b696d7a7b2c6deb26344c727a1970ece1e(sha256)  Expected: 816f0808841fe8022604e3a223269711330af412b663d2f991f73b4988b7d149(sha256)
[MIRROR] mullvad-browser-stable_x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 5a9d8878101d78969a85700f755581b696d7a7b2c6deb26344c727a1970ece1e(sha256)  Expected: 816f0808841fe8022604e3a223269711330af412b663d2f991f73b4988b7d149(sha256)
[MIRROR] mullvad-browser-stable_x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 5a9d8878101d78969a85700f755581b696d7a7b2c6deb26344c727a1970ece1e(sha256)  Expected: 816f0808841fe8022604e3a223269711330af412b663d2f991f73b4988b7d149(sha256)
[MIRROR] mullvad-browser-stable_x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 5a9d8878101d78969a85700f755581b696d7a7b2c6deb26344c727a1970ece1e(sha256)  Expected: 816f0808841fe8022604e3a223269711330af412b663d2f991f73b4988b7d149(sha256)
[FAILED] mullvad-browser-stable_x86_64.rpm: No more mirrors to try - All mirrors were already tried without success

The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  mullvad-browser-13.5.3-1.x86_64: Cannot download, all mirrors were already tried without success
```

**Comment by ruihildt** [comment]
Can you do using `dnf clean all` (it will clear all sort of cache) then try installing it again?

**Comment by piotrowskiadam** [comment]
Unfortunately, it didn't fix the issue.

**Comment by ruihildt** [comment]
Please contact support@mullvadvpn.net, my knowledge of repositories is unfortunately very limited.

**Comment by Martin-Buchholz** [comment]
On an apt-based system (Pop-OS) I see

E: Failed to fetch https://repository.mullvad.net/deb/stable/dists/jammy/main/binary-amd64/Packages.gz  File has unexpected size (904 != 901). Mirror sync in progress? [IP: 45.149.104.1 443]
   Hashes of expected file:
    - Filesize:901 [weak]
    - SHA256:0327c6e6bdf2a7b5b7f6dad1a6379a7f479baa0b5332d464fd59f6d82cd78285
    - SHA1:9cccb2851f172f45a88f8c5eaa15c9884ae32a71 [weak]
    - MD5Sum:ff752d3651ba29bb385db136fda323d9 [weak]
   Release file created at: Thu, 05 Sep 2024 15:31:47 +0000

I'm disappointed that this issue was closed as "completed" when it clearly was not.

**Comment by piotrowskiadam** [comment]
Unexpectedly the issue stopped even before they responded to my email.

I just reapplied commands from https://mullvad.net/en/download/browser/linux

and after running these
```
# Add the Mullvad repository server to dnf
sudo dnf config-manager --add-repo https://repository.mullvad.net/rpm/stable/mullvad.repo

# Install the package
sudo dnf install mullvad-browser 
```
It just updated without issues. @Martin-Buchholz  maybe try the same thing.

**Comment by Martin-Buchholz** [comment]
My problem also went away, without my taking any action, and without any obvious updates on repository.mullvad.net.  Probably Mullvad release engineering folk fixed something, and I'm curious to know what it might be.

**Comment by ruihildt** [comment]
@Martin-Buchholz This repository is about the browser itself. The infrastructure to distribute it is not taken care by the same team. While I will try to help as much as possible, the best way to receive help and timely follow up is through support@mullvadvpn.net which routinely deals with such issues.

I understand closing as `completed` sends the wrong message without better communication from my part. Sorry for that.
