### ISSUE TITLE
Update failure (Unverifiable PGP signature)

### ISSUE THREAD

**Issue by Zakanuva** [mullvad/mullvad-browser#305]
I have the Mullvad Browser installed on a PC running Manjaro Linux, and for the past few days, whenever performing system updates via the GUI package manager, the Browser has consistently failed to update while everything else hasn't had any trouble doing so.

This is the latest output from the package manager's back-end:
```
Preparing...
Synchronizing package databases...

Refreshing extra.db...
Cloning mullvad-browser-bin build files...
Generating mullvad-browser-bin information...
Checking mullvad-browser-bin dependencies...
Warning: nano-syntax-highlighting: local (2020.10.10+10+g1aa64a8-2) is newer than extra (2020.10.10-2)
Warning: python-inputs: local (0.5.0-1) is newer than extra (0.5-6)
Resolving dependencies...
Checking inter-conflicts...

Building mullvad-browser-bin...
==> Making package: mullvad-browser-bin 13.5.3-1 (Sat 07 Sep 2024 02:07:54 PM PDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found mullvad-browser-linux-x86_64-13.5.3.tar.xz
  -> Found mullvad-browser-linux-x86_64-13.5.3.tar.xz.asc
  -> Found mullvad-browser.sh
  -> Found mullvad-browser.desktop
==> Validating source files with sha256sums...
    mullvad-browser-linux-x86_64-13.5.3.tar.xz ... Passed
    mullvad-browser-linux-x86_64-13.5.3.tar.xz.asc ... Skipped
    mullvad-browser.sh ... Passed
    mullvad-browser.desktop ... Passed
==> Verifying source file signatures with gpg...
    mullvad-browser-linux-x86_64-13.5.3.tar.xz ... FAILED (unknown public key 157432CF78A65729)
==> ERROR: One or more PGP signatures could not be verified!
Failed to build mullvad-browser-bin
```

How do I fix this?

**Comment by boklm** [comment]
> ==> Verifying source file signatures with gpg...
>     mullvad-browser-linux-x86_64-13.5.3.tar.xz ... FAILED (unknown public key 157432CF78A65729)

This release is signed by a new gpg subkey. So it looks like you need to
refresh the key.

**Comment by Zakanuva** [comment]
> ==> Verifying source file signatures with gpg... mullvad-browser-linux-x86_64-13.5.3.tar.xz ... FAILED (unknown public key 157432CF78A65729)
> This release is signed by a new gpg subkey. So it looks like you need to refresh the key.

How do I do that?

**Comment by ruihildt** [comment]
You can try refreshing your key with `gpg --refresh-keys EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290`.

**Comment by Zakanuva** [comment]
> You can try refreshing your key with `gpg --refresh-keys EF6E286DDA85EA2A4BA7DE684E2C6E8793298290`.
> 
> Or `gpg --auto-key-locate nodefault,wkd --locate-keys torbrowser@torproject.org` is the keyserver is not located.

The second command seems to work, but the first one doesn't do anything:
```
    ~  gpg --refresh-keys EF6E286DDA85EA2A4BA7DE684E2C6E8793298290                         ✔ 
gpg: refreshing 1 key from hkps://keyserver.ubuntu.com
gpg: keyserver refresh failed: No data
    ~  gpg --auto-key-locate nodefault,wkd --locate-keys torbrowser@torproject.org       2 ✘ 
gpg: key 4E2C6E8793298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" 5 new signatures
gpg: key 4E2C6E8793298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" 2 new subkeys
gpg: Total number processed: 1
gpg:            new subkeys: 2
gpg:         new signatures: 5
pub   rsa4096 2014-12-15 [C] [expires: 2027-07-15]
      EF6E286DDA85EA2A4BA7DE684E2C6E8793298290
uid           [ unknown] Tor Browser Developers (signing key) <torbrowser@torproject.org>
sub   rsa4096 2021-09-17 [S] [expires: 2024-09-13]
sub   rsa4096 2024-07-15 [S] [expires: 2026-10-26]

    ~  gpg --refresh-keys EF6E286DDA85EA2A4BA7DE684E2C6E8793298290                         ✔ 
gpg: refreshing 1 key from hkps://keyserver.ubuntu.com
gpg: keyserver refresh failed: No data
```

...So now what do I do?

**Comment by boklm** [comment]
If other keyservers are not working, you can try using `keys.openpgp.org`:
```
gpg --keyserver hkps://keys.openpgp.org --refresh-keys EF6E286DDA85EA2A4BA7DE684E2C6E8793298290
```

What I don't know is if the Manjaro package is using the default gpg
keyring. Was refreshing the key in the default keyring enough to solve
the problem?

**Comment by Zakanuva** [comment]
> If other keyservers are not working, you can try using `keys.openpgp.org`: ``` gpg --keyserver hkps://keys.openpgp.org --refresh-keys EF6E286DDA85EA2A4BA7DE684E2C6E8793298290 ``` What I don't know is if the Manjaro package is using the default gpg keyring. Was refreshing the key in the default keyring enough to solve the problem?

I don't know. I've had no other issues with `mullvad-browser` since closing this issue months ago, and I'm not tech-savvy enough to troubleshoot what even happened to fix whatever was wrong...
