### ISSUE TITLE
Search bar not working

### ISSUE THREAD

**Issue by mentalmuzzy** [mullvad/mullvad-browser#309]
When i try to use the search bar it no longer works i have to type the full url out

In the image you can see i tried searching for youtube but nothing happens i have to type the full URL out for mullvad to work so what i have been doing is going to google.com and using that search bar to search since i have not been able to find a fix

![image](https://github.com/user-attachments/assets/135fa4e6-c205-471c-af66-4effa39468b0)

**Comment by ruihildt** [comment]
In a "regular" browser, autocomplete would most likely be based on history. since we don't have this what you can do is bookmark a website, and it will then show up in the autocomplete.

**Comment by mentalmuzzy** [comment]
> In a "regular" browser, autocomplete would most likely be based on history. since we don't have this what you can do is bookmark a website, and it will then show up in the autocomplete.

This is not what i mean if you look at the image the duck duck go search engine is not searching i will upload a video to better show what i mean as you can see in the video when search for youtube or google nothing happens but URL's work fine i know this worked originally when i first downloaded mullvad browser

https://github.com/user-attachments/assets/775322f0-a25a-4b83-a9dd-50fc4a26e135

**Comment by Thorin-Oakenpants** [comment]
both DDG's work for me on windows. Are you using a VPN or proxy?

What happens if you choose different search engines - where in the drop down it says "this time search with.." - i.e is this only a specific DDG, or all DDG, or all .. search engines
