### ISSUE TITLE
mullvad browser 32 bit

### ISSUE THREAD

**Issue by tortino2** [mullvad/mullvad-browser#31]
please create a 32 bit version for mullvad browser (windows 10).
I use a win10 32 bit tablet and I'd like to use mullvad on it.
thanks.

**Comment by ruihildt** [comment]
The supported versions on the website corresponds to the platforms we test.
We currently test on the following platforms:

    macOS 12 (intel / arm)
    macOS 13 (intel / arm)
    Fedora 37 (Latest version)
    Ubuntu 22.04 (Latest LTS)
    Windows 10
    Windows 11

Because testing takes time and resources, we decided to only test on the platforms we support.
