### ISSUE TITLE
Allow easy uninstalling of mullvad browser from windows

### ISSUE THREAD

**Issue by kevin0t** [mullvad/mullvad-browser#32]
I had installed mullvad browser for testing purpose in my windows 10 computer and now i want to uninstall it , but i can't see any uninstaller in the install directory , nor do i see program with name Mullvad browser in the control panel>programs>program & features list.  For context i had installed it in a non-standard directory like `C:\Users\user2\Applications\Mullvad Browser`
I don't know if this is expected behavior or a problem with my install.
Please let me know about any fixes for this issue.

**Comment by ruihildt** [comment]
Currently on Windows (and Linux), there is no integration to the system, outside shortcuts, if you tick the corresponding option during the "Install" process.
To remove Mullvad Browser on Windows, simply delete its folder, and remove the shortcuts.

We might add a proper installer at some point, but it's not currently planned.

We will add this to our FAQ, thanks for reporting it.

**Comment by ioc2e3** [comment]
> 目前，在 Windows（和 Linux）上，除了快捷方式外，如果您在「安裝」過程中勾選了相應的選項，則 Mullvad 瀏覽器目前沒有整合到系統中。 ...

Excuse me ...

Installation process ( which options ) ...

.

**Comment by ruihildt** [comment]
> > 目前，在 Windows（和 Linux）上，除了快捷方式外，如果您在「安裝」過程中勾選了相應的選項，則 Mullvad 瀏覽器目前沒有整合到系統中。
> 
> Excuse me ...
> 
> Installation process ...
> 
> Select ( which options ) ...
> 
> Mullvad Browser no integrated into the system ...
> 
> .

If you use the default settings, Mullvad Browser will be installed as any regular program.
