### ISSUE TITLE
Metadata Leak

### ISSUE THREAD

**Issue by issuant** [mullvad/mullvad-browser#321]
In `about:config`, I just noticed there's data of at least one extension, Metamask, I tested (because of #178) but removed a long time ago when I activate `Show only modified preferences`. No idea if there is more elsewhere but I see this explicitly in `browser.uiCustomization.state`. Is this something that can be deleted?

**Comment by ruihildt** [comment]
> In `about:config`, I just noticed there's data of at least one extension

Can you be more specific as to what youobserve? What's the key modified and what's the value?

**Comment by ruihildt** [comment]
This is a left-over from the extension install and only indicates the placement of the extension icon while it was installed. There's an existing issue upstream: https://bugzilla.mozilla.org/show_bug.cgi?id=1885885

This is not a fingerprint vector
