### ISSUE TITLE
Firefox 115 ESR Support

### ISSUE THREAD

**Issue by rtherhsfhsfhfsdh** [mullvad/mullvad-browser#323]
Hello, 

I was wondering if Mullvad Browser will still support Firefox 115ESR after the release of Firefox 128.3.0ESR? Because Mozilla has officially announced that they will be extending support for version 115 all the way to the end of March in 2025. The TOR Project appears to have started working on the next ESR release for 115, which is 115.16.0ESR, but I do not see it being done in the Mullvad repository. The benefit to supporting the old ESR is it will give more time for users on older operating systems, like Windows 7, to upgrade.

thank you 🤲

**Comment by ruihildt** [comment]
Unfortunately, no. When Mullvad Browser 14.0 based on Firefox 128 ESR will be released, we will not provide updates for the 115ESR branch.

We don't test or support platforms that reached their end of life for security reasons. You can always find on our website the list of platforms actively supported.

**Comment by ruihildt** [comment]
> I do not know what you mean by, “we do not support platforms that have reached end of life.”

Instead of "platform", read "operating system". Both Windows 7/8 have reached end of life.
I'm sorry we're not able to support the users still on those platforms for a few more months. :/

**Comment by ruihildt** [comment]
> Just one last thing, I noticed that the email for feedback and support provided in the README.md appears to be outdated. Should I make another issue for that?

Thank you, this is fixed.
