### ISSUE TITLE
Linux deb install "package not found"

### ISSUE THREAD

**Issue by 4Kstreams** [mullvad/mullvad-browser#328]
Following the steps in the linux deb guide, when you reach "apt install mullvad-browser" you are greeted with an error indicating that there is no package with name mullvad-browser.

**Comment by LinuxOnTheDesktop** [comment]
Hello there. Today I see something similar, on Mint 22.

```
$ sudo apt update
[. . .]
Ign:11 https://repository.mullvad.net/deb/stable wilma InRelease                                                                
Err:12 https://repository.mullvad.net/deb/stable wilma Release                                                                  
  404  Not Found [IP: 45.149.104.1 443]
[. . .]
Reading package lists... Done
E: The repository 'https://repository.mullvad.net/deb/stable wilma Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by ruihildt** [comment]
@LinuxOnTheDesktop The error you see is because the repo doesn't have a `wilma` release.

On Linux Mint, you can add our repository by following the instructions with a small change: instead of `$(lsb_release -cs)`, you add the code version for the Ubuntu used by Linux Mint. for Linux Mint 22, it's `noble`.

**Comment by LinuxOnTheDesktop** [comment]
@ruihildt 

Aha. Thank you for imparting that. You might want to amend (supplement) the instructions on [this (nicely-formatted!) page](https://mullvad.net/en/download/browser/linux).

**Comment by bit-man** [comment]
Currently using [Linux Mint Debian Edition 6](https://linuxmint.com/download_lmde.php) and found the same problem. To solve it copied the version name from official package repository (**wookwom** for LMDE 6)

This are the whole command line instructions
```
# Download the Mullvad signing key
sudo curl -fsSLo /usr/share/keyrings/mullvad-keyring.asc https://repository.mullvad.net/deb/mullvad-keyring.asc

# Add the Mullvad repository server to apt
echo "deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=$( dpkg --print-architecture )] https://repository.mullvad.net/deb/stable $(grep debian /etc/apt/sources.list.d/official-package-repositories.list  | head -1 | awk '{print $3}') main" | sudo tee /etc/apt/sources.list.d/mullvad.list

# Install the package
sudo apt update
sudo apt install mullvad-browser
```

**Comment by ruihildt** [comment]
I had this version that works for both Debian/Ubuntu based distros:

```
echo "deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=$(dpkg --print-architecture)] https://repository.mullvad.net/deb/stable $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") main" | sudo tee /etc/apt/sources.list.d/mullvad.list
```

But I'm not sure we would want to put this on our website, since we don't officially support other distributions than Fedora/Ubuntu/Debian.
