### ISSUE TITLE
MacOS auto-updates do not work when app is in local user Applications folder rather than the system one.

### ISSUE THREAD

**Issue by ghost** [mullvad/mullvad-browser#329]
To be fair, I haven't experienced this in Mullvad Browser yet (no release has been posted) but it does occur for the Tor Browser so I assumed it would apply here too. Why does the auto-update not work?

**Comment by ruihildt** [comment]
An update is now available, can you confirm and report please?

**Comment by ruihildt** [comment]
I don't know, I recommend you check in Tor Browser issue tracker if it has been reported, and if not, to open one:

https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/

**Comment by boklm** [comment]
> Issue does not occur on Mullvad browser. Not sure why it occurs on Tor Browser. Do you have any idea?

This was probably due to this issue:
https://gitlab.torproject.org/tpo/applications/tor-browser-build/-/issues/41245#note_3088067

Which should be fixed now.
