### ISSUE TITLE
The font fingerprints still work.

### ISSUE THREAD

**Issue by ruihildt** [mullvad/mullvad-browser#33]
Report from a user:

> You can check it here:
> https://browserleaks.com/fonts
> This extension solved the problem:
> https://addons.mozilla.org/en-US/firefox/addon/font-fingerprint-defender/

**Comment by ruihildt** [comment]
> How is that?
> 
> browserleaks and creepjs give me different/equal fonts results for TB, MB and partially for LW (part of the results are the same from my vanilla FF).

It is expected for each browser to have a different fingeprint.

**Comment by ave9858** [comment]
I noticed the font fingerprint changes if Microsoft Office is installed vs when it hasn't been installed, is that expected? There is one additional font after office has been installed

**Comment by Thorin-Oakenpants** [comment]
@ave9858 
- What OS, I assume Windows?
- Is this Office 365?
- What test did you use?
- What are the full font results - and what is the one additional font you say is detected?

Disclosure: I work on fingerprint stuff

**Comment by ave9858** [comment]
@Thorin-Oakenpants 
Windows, Office 365 downloaded from [here](https://c2rsetup.officeapps.live.com/c2r/download.aspx?ProductreleaseID=O365ProPlusRetail&platform=x64&language=en-us&version=O16GA) (activation not required, just install), I found the extra font thru https://arkenfox.github.io/TZP/tzp.html#fonts and confirmed it with some JS, the extra font is Gill Sans. 

To reproduce, run the installer on a fresh VM and reload the page once office is installed. Uninstalling office seems to keep the font installed.

**Comment by Thorin-Oakenpants** [comment]
Hah, yes this is a known issue :) thanks for reporting

Just a question though - did you not have to choose after installation to use Gill Sans from the cloud (it shouldn't install it per see in windows/fonts, but adds it in an office folder somewhere for use in Office products)? Something like this: https://filestore.community.support.microsoft.com/api/images/b071b00b-3f17-4f5a-93a7-b1378aca29a4 (see the little cloud symbol)

cc @PieroV

**Comment by Thorin-Oakenpants** [comment]
BTW, I am the author of TZP :)

Can you tell me if you have gill sans in your windows/fonts directory?

**Comment by ave9858** [comment]
> Just a question though - did you not have to choose after installation to use Gill Sans from the cloud (it shouldn't install it per se in windows/fonts, but adds it in an office folder somewhere for use in Office products)? Something like this: https://filestore.community.support.microsoft.com/api/images/b071b00b-3f17-4f5a-93a7-b1378aca29a4 (see the little cloud symbol)

I didn't run office at all after install, it added the font before the installer even sent the notification the install was complete.



> BTW, I am the author of TZP :)

ik, i've been following your work, ty for the help



> Can you tell me if you have gill sans in your windows/fonts directory?

Yep, I see it there

**Comment by Thorin-Oakenpants** [comment]
Thanks, the font being added to `windows/fonts` is news to me, we'll check it our with your link in a new VM. We did research (murk office docs, thanks MS), and somewhat test and we did check with a real live user with office 365 ( see https://github.com/arkenfox/user.js/issues/1801 )

fyi: we know it can exist there (fonts dir) from much older windows office installs (office 2013 or earlier?) maybe as additional components (not sure), and it takes a certain `gill` font combo to trigger it - so given the super unlikely chance it happens, we haven't patched it _yet_ but I added the font to TZP's windows list.

So free 🍺 for me for adding it, and free 🍕 for you for reporting it :) I shall stick PieroV onto it, he loves windows VMs 😁

**Comment by PieroV** [comment]
:wave:

@ave9858 thanks for the information!

Which version of Office did you install? From archived docs we found Gill Sans hasn't been shipped by default since Office 2013, otherwise it's always been part of Office.

**Comment by Thorin-Oakenpants** [comment]
> otherwise it's always been part of Office.

not always. My office 2007 (or is it 2010) doesn't

**Comment by ave9858** [comment]
> Which version of Office did you install? From archived docs we found Gill Sans hasn't been shipped by default since Office 2013, otherwise it's always been part of Office.

Tested with latest 365 ProPlus, I'll start testing some other versions. I'm guessing it will affect most or all modern c2r office versions.

**Comment by ave9858** [comment]
I tried a bunch of older office versions and didn't see the font, then rebooted and it was there, so I know at least some non-365 versions of office are affected but not what specific editions and versions install the font, so I'm cleaning the VM and testing again.

**Comment by ave9858** [comment]
Can't find exactly what causes the font to be installed, it seems to depends on how you install office and not just what edition you have, upgrading to 365 from an older version didn't install the font, even though both versions were c2r based and updated to the same build. I'll try to ask some other people to see how common the issue is.

**Comment by Thorin-Oakenpants** [comment]
Sounds like a bit of a rabbit hole :) We thought it would be rare - e.g. windows 7/8* users with some older MS offices. But also some of those users who upgraded to win10 (IDK what happens to all the fonts here, do they also get updated to the newer versions? and of course anything installed by MS Office or a third party app or manually added would stay). Also in TB14 windows 7/8* is no longer supported so at least that starts to remove some entropy (lack of win10+ fonts), but wouldn't remove fonts (like gill sans).

And with office 365, users can add cloud fonts to their `windows/font` dir, there are articles on how to use office 365 fonts in other apps.

So all said and done, we know there's an issue. And now we know it's more prevalent than we thought. So I don't know if deep diving a heap of office installs + upgrades is that worthwhile to be honest - to save you your time @ave9858 :) And we know we need to patch it, so I think we're done here ... see bug, patch bug :)

**Comment by PieroV** [comment]
Thanks for the updates!
I've tried a patch yesterday, but it wasn't enough.
I'll have to wrestle a little bit more to debug cross-compiled builds (VS doesn't like the PDBs this time).
Otherwise, I know of a Gill Sans-specific workaround, but I'd like to find the root cause, in case Mozilla adds other exceptions in the future.

**Comment by ave9858** [comment]
Can confirm this is fixed in MB 13.0.12
