### ISSUE TITLE
Add mullvad browser to applications list with linux binary setup

### ISSUE THREAD

**Issue by kevin0t** [mullvad/mullvad-browser#331]
When using the Mullvad browser binary and clicking on the setup file , the mullvad browser sits in its folder but as a issue of convenience , if the setup automatically adds itself to the list of applications in start menu , it would be great. I know user could possibly configure it manually but the user experience takes a bad hit if not done automatically. 
I am not an expert on linux on advising how to do it but i have seen telegram binary do the same easily.
thanks

**Comment by ruihildt** [comment]
You can actually add the Mullvad Browser to the applications list by running the following command `./start-mullvad-browser.desktop --register-app`.

This will create the correct shortcut in `~/.local/share/applications/`. (For now, it won't be possible to set the browser as default though)

**Comment by kevin0t** [comment]
thanks for the answer . can you please add these to the mullvad download page instructions. I know being on linux you are supposed to know everything but for noobs like me it wouldhttps://github.com/signalapp/Signal-Desktop create less friction.
Also the steps for installing the deb repo on Linux mint as you mentioned in another issue
