### ISSUE TITLE
Cannot play audio

### ISSUE THREAD

**Issue by lvgrr** [mullvad/mullvad-browser#334]
When I try to play an audio stream I get this warning:
```
[Child 9247, MediaDecoderStateMachine #1] WARNING: 72133b9fda60 OpenCubeb() failed to init cubeb: file /var/tmp/build/firefox-0697953d6d52/dom/media/AudioStream.cpp:281
[Child 9247, MediaDecoderStateMachine #1] WARNING: Decoder=721356ed3700 [OnMediaSinkAudioError]: file /var/tmp/build/firefox-0697953d6d52/dom/media/MediaDecoderStateMachine.cpp:4604
```
Version number:
```
Mullvad MullvadBrowser 115.16.0esr 20241008182800 20241008182800 
```

I've installed the browser through the Arch User Repository, but I've also tried the official binary package from mullvad.net and it has the same issue.

**Comment by ruihildt** [comment]
Would you mind checking if you have the same issue with Tor Browser and [Firefox ESR](https://www.mozilla.org/en-US/firefox/all/desktop-esr/)?

**Comment by lvgrr** [comment]
Yes the issue is still there:

Firefox version:
```
Mozilla Firefox 128.3.1esr 20241008174909 20241008174909 
```

Debug:
```
[Child 3241, MediaDecoderStateMachine #1] WARNING: 7021020aaca0 OpenCubeb() failed to init cubeb: file /builds/worker/checkouts/gecko/dom/media/AudioStream.cpp:285
[Child 3241, MediaDecoderStateMachine #1] WARNING: Decoder=7020f8bbc700 [OnMediaSinkAudioError]: file /builds/worker/checkouts/gecko/dom/media/MediaDecoderStateMachine.cpp:4654
```


Tor Browser version:
```
Mozilla Firefox 128.3.1esr 20241008174909 20241008174909 
```

Debug:
```
[Child 6781, MediaDecoderStateMachine #1] WARNING: 7b01ab848b80 OpenCubeb() failed to init cubeb: file /var/tmp/build/firefox-e9a98dae2430/dom/media/AudioStream.cpp:281
[Child 6781, MediaDecoderStateMachine #1] WARNING: Decoder=7b01920e2a00 [OnMediaSinkAudioError]: file /var/tmp/build/firefox-e9a98dae2430/dom/media/MediaDecoderStateMachine.cpp:4604
```

**Comment by ruihildt** [comment]
Do you have the same issue with the latest Firefox as well?

**Comment by lvgrr** [comment]
No, the latest Firefox works fine.

**Comment by ruihildt** [comment]
Final test, can you try the latest Mullvad Browser Alpha?

https://github.com/mullvad/mullvad-browser/releases/tag/14.0a9

**Comment by lvgrr** [comment]
Does not work with the latest alpha:
```
[Child 13765, MediaDecoderStateMachine #1] WARNING: 7dcf61fe0a60 OpenCubeb() failed to init cubeb: file /var/tmp/build/firefox-0375bee4e021/dom/media/AudioStream.cpp:285
[Child 13765, MediaDecoderStateMachine #1] WARNING: Decoder=7dcf62bf1c00 [OnMediaSinkAudioError]: file /var/tmp/build/firefox-0375bee4e021/dom/media/MediaDecoderStateMachine.cpp:4654
```

**Comment by Thorin-Oakenpants** [comment]
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/28017

**Comment by ruihildt** [comment]
@lvgrr Do you confirm you use ALSA? If so we can close this issue as a won't fix.

**Comment by lvgrr** [comment]
Yes, I do use that. I didn't know that PulseAudio was required, but I was able to fix the issue by following the instructions at the [ArchWiki page for PipeWire](https://wiki.archlinux.org/title/PipeWire#PulseAudio_clients), i.e.by  installing [`pipewire-pulse`](https://archlinux.org/packages/extra/x86_64/pipewire-pulse/) and starting `pipewire-pulse.service`.

**Comment by ruihildt** [comment]
Great to hear, closing the issue.
