### ISSUE TITLE
Can't play H264 videos anymore...

### ISSUE THREAD

**Issue by Arkenium** [mullvad/mullvad-browser#337]
For some reason, my Mullvad browser doesn't want to play H264 videos anymore.
It started yesterday and I have no idea why...
OS: Ubuntu 24.04

Here are 2 examples of videos not playing:
https://tools.woolyss.com/html5-audio-video-tester/?u=woolyss.com/f/avc-mp3-sita.mov
https://tools.woolyss.com/html5-audio-video-tester/?u=woolyss.com/f/avc-aac-big-buck-bunny.m4v

Other formats seem to be playing just fine based on my tests.
https://tools.woolyss.com/html5-audio-video-tester/

Anyone is experiencing the same issue ?
Any solution that you know of ?

Thx

**Comment by Dispatch3376** [comment]
Same problem here, this also seems to affect some youtube videos as well.

OS: Linux Mint 22 Cinnamon
Version: 13.5.7 (flatpak)

**Comment by Refold3547** [comment]
I'm using win11 and this problem doesn't happen. It must be something specific to linux.

**Comment by Arkenium** [comment]
No, it has anything to do with Linux/Ubuntu.
Videos work just fine on my LibreWolf browser.
It has something to do with the Mullvad browser specifically.
But I don't know what it is...

**Comment by Thorin-Oakenpants** [comment]
> No, it has nothing to do with Linux/Ubuntu.

Yes it does. It's implied that we're comparing MB (windows) to MB (linux). So Refold3547 is right - it's linux specific issue (assuming mac isn't affected).

---

Does the problem also occur in Tor Browser? We're about to hit MB/TB 14 in stable (based on Firefox ESR128) so I wouldn't test yet (unless you want to download and run alphas) - just wait until 14 lands in hopefully a few days

**Comment by slubman** [comment]
This is an issue specific with the latest flatpak package.

Using the previous flatpak which is the same browser version (13.5.7) with another SDK can play videos just fine.

Also using the package provided via the mullvad repository, which is the same version (13.5.7), videos are also playing just fine.

**Comment by Arkenium** [comment]
> Yes it does. It's implied that we're comparing MB (windows) to MB (linux). So Refold3547 is right - it's linux specific issue (assuming mac isn't affected).
I thought he meant the OS not MB on the OS. My bad.

> This is an issue specific with the latest flatpak package.
Ok, thank you. I'll wait for MB 14 as suggested above.

Thank you all for your kind replies.

**Comment by Erick555** [comment]
The problem was incompatibility between FF ESR115 and ffmpeg 7+ , see https://github.com/flathub/net.mullvad.MullvadBrowser/issues/54#issuecomment-2426919705 . FF ESR128 and later will be fine

**Comment by dtwn-Git** [comment]
Problem still persists, issue is playing videos on mullvad browser with a linux OS.


- using version 14.0.3 (based on Mozilla Firefox 128.5.0esr) of mullvad browser
