### ISSUE TITLE
Local JS file (custom start page) gives CORS error

### ISSUE THREAD

**Issue by seanluse41** [mullvad/mullvad-browser#346]
New to the mullvad browser, and appreciate the work you all do.
I am sure there is some setting I am missing, but having a custom url (local html file) which imports some local js file gives a CORS error, and I can't figure out which setting is blocking it.
Sorry for the noob question.

**Comment by Thorin-Oakenpants** [comment]
Does this also happen in Firefox?

**Comment by ruihildt** [comment]
Can you check with the [latest alpha](https://github.com/mullvad/mullvad-browser/releases/tag/14.0a10)? 

A potential fix was included for this.

**Comment by seanluse41** [comment]
Just checked on Firefox Beta 133.0b3 (64-bit)
Same behavior. My mistake all.

**Comment by seanluse41** [comment]
For future reference, the above behavior is due to the following setting in both mullvad-browser and firefox:

`about:config`
`security.fileuri.strict_origin_policy -> True --> False`
This is obviously, in place for security reasons and should not be changed without full knowledge of what that entails.
Personally, I decided to host the custom startpage on github pages and set the custom startup page url to there.
