### ISSUE TITLE
Lazy loading attributes are only forcibly neutralized when scripting is disabled by NoScript

### ISSUE THREAD

**Issue by Jee-Hex** [mullvad/mullvad-browser#348]
NoScript has recently introduced a [patch](https://github.com/hackademix/noscript/commit/f5cf60b4a9d467ebb8f80ced67e87602df33cef4) to modify all `[loading="lazy"]` attributes to `[loading="eager"]` when "scripting is disabled". However on Mullvad Browser this only happens (on HTTPS sites) when you set the security level to safest, but **not** when you disable JS in uBO using the `Disable JavaScript` option (equivalent to `no-scripting: * true` in My rules) and/or by disabling inline scripts + 1st-party scripts + 3rd-party scripts globally (equivalent to 

```
* * 1p-script block
* * 3p-script block
* * inline-script block
```

in  My rules).

I am also reproducing the same behavior with Firefox + uBlock Origin + NoScript.

Was this intentional or another case of WebExtension-related limitation? Because I thought the CSP bug was fixed quite some time ago in [Bug 1462989](https://bugzilla.mozilla.org/show_bug.cgi?id=1462989).

**Comment by Thorin-Oakenpants** [comment]
pinging @hackademix

**Comment by Thorin-Oakenpants** [comment]
@Jee-Hex https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/42805 => https://github.com/hackademix/noscript/commit/f5cf60b4a9d467ebb8f80ced67e87602df33cef4 is probably what you're after. There's another related (but confidential) gitlab issue, and an upstream issue was opened but I can't find it

**Comment by Thorin-Oakenpants** [comment]
> There's another ... upstream issue

ok, found it - https://bugzilla.mozilla.org/show_bug.cgi?id=1919496
