### ISSUE TITLE
leta.mullvad.net not connecting

### ISSUE THREAD

**Issue by gonzo425** [mullvad/mullvad-browser#350]
The proxy server is refusing connections via Mullvad browser.

Browser works ok, just not connecting to the leta server. 

VPN is on and has been working just fine until this morning.

**Comment by gonzo425** [comment]
leta.mullvad.net is set to always be proxied through us-atl-wg-108

**Comment by ruihildt** [comment]
`us-atl-wg-108` is not a valid server anymore. you'll need to pick another server.
