### ISSUE TITLE
Unable to install Mullvad Browser repository on Fedora 41

### ISSUE THREAD

**Issue by serial02** [mullvad/mullvad-browser#357]
Hello

Unable to install Mullvad Browser repository on Fedora 41

![Captura de tela de 2024-11-13 18-34-49](https://github.com/user-attachments/assets/06048b51-a38e-4fdd-b82c-af615ecaac39)

I'm waiting for a solution

Thanks

**Comment by ruihildt** [comment]
There were some networking issues that are now fixed. Thanks for reporting.
