### ISSUE TITLE
Scrambeled Image

### ISSUE THREAD

**Issue by Isaac-Piscopo** [mullvad/mullvad-browser#358]
I am trying to upload an image however upon upload the image is scrambled. The result is random every time.

Other closed issues were found regarding this issue but I didn't understand the solution.
How would I fix this?
![Corrupted](https://github.com/user-attachments/assets/955329e8-4fe2-4939-b620-92a14010bf55)

**Comment by Isaac-Piscopo** [comment]
As a minor update going on about:config and setting `privacy.resistFingerprinting.randomDataOnCanvasExtract` to `false` removes the scrambling but leaves a blank white image instead.

**Comment by ruihildt** [comment]
This is because some functionality of HTML Canvas are randomized, so you can't get uniquely identified.

If for example you go to fingeprint.com, you'll see on the left of the URL bar an image icon. You can temporarily allow canvas to extract more information, which might restore functionality temporarily.

**Comment by ruihildt** [comment]
Would you be comfortable sharing the URL of that website?

**Comment by Isaac-Piscopo** [comment]
[](https://www.messenger.com)

**Comment by Isaac-Piscopo** [comment]
I do know that if I disable this I would get more easily uniquely identified however I am fine with this trade off.

**Comment by Thorin-Oakenpants** [comment]
you fix it like this

- 🔹BREAKAGE
   - canvas: you can set a site exception either temporarily or permanently <sup>1</sup> 🥇 `99% of breakage`
       - Note: totally randomizing the canvas per execution is by design
       - ![rfpCanvas](https://github.com/user-attachments/assets/3275a720-08da-47dd-b26c-118c74170d8f)
          - A trained user can spot a RFP canvas by it's wavy pattern
       - ![rfpCanvasException](https://github.com/user-attachments/assets/ed1ed98c-90b3-4c7d-8a47-a50127c472f4)
          - Set/revoke site exceptions via the urlbar or `Ctrl-I > Permissions`

The canvas icon in the urlbar may not be displayed if canvas hasn't been "triggered" yet - e.g. you are yet to upload. In that case you can use the `Ctrl-I > Permissions`

**Comment by Isaac-Piscopo** [comment]
I have seen that however I do not full understand it. I have managed through the lock icon to open the permission list but do not know which permissions to change. If I set 'Extract canvas data' to Allow I see no change.

**Comment by Thorin-Oakenpants** [comment]
yes that is the permission and settings - untick use default and select allow. You will have to _reupload_ the image

![permissions](https://github.com/user-attachments/assets/4d75e538-f456-4e65-9a7b-ab7d10db3890)
