### ISSUE TITLE
tab groups extensions

### ISSUE THREAD

**Issue by tortino2** [mullvad/mullvad-browser#36]
Hello,
I want to use an extension to manage tab groups.
I installed Simple Tab Groups and it doesn't work in private mode.

So I tried other extensions, like Panorama View, Power Tabs, Tiled Tab Groups.
The extensions installs correctly if I enable the flag to run them in private windows.

At first they seems to work, but after closing the browser and reopening it all the groups are gone.
The setting are never remembered.

Any way to fix this issue?
Thanks.

**Comment by ruihildt** [comment]
Since Mullvad Browser is always in Private Browsing Mode, this extension can't run.

The extension developer confirmed it as much: https://github.com/Drive4ik/simple-tab-groups/issues/720#issuecomment-726092474
