### ISSUE TITLE
Bug 329: Remove the Security Levels icon from the toolbar [mullvad-browser]

### ISSUE THREAD

**Issue by ghost** [mullvad/mullvad-browser#363]
Why was this removed? Tor browser keeps it in toolbar, it is way more user-friendly this way.

**Comment by Thorin-Oakenpants** [comment]
First of all ... MB is not TB and there are differences in threat model and usage

Did you read the issue? https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/329 - note that the first linked item `tor-browser#42572` is confidential, so you won't be getting the full picture

also ... if you whip on your big girl pants
> The icon could still be re-added by dragging it from the `Customize toolbar menu`

**Comment by ruihildt** [comment]
This is an extract from the blog post coming out today:

> Security levels

> Changing the security level modifies the browser fingerprint, and is not recommended. Consequently, the Security levels button has been removed from the toolbar. Security levels are still accessible through the browser settings.
