### ISSUE TITLE
 "Zoom text only" breaks pdfjs

### ISSUE THREAD

**Issue by Kobaxidze256** [mullvad/mullvad-browser#368]
Steps to reproduce:

    Increase "Default zoom"
    Enable "Zoom text only"
    Open a PDF with pdfjs https://media.pragprog.com/titles/dsproc/gestures.pdf

Actual results:

Text in the PDF is unreadable

Expected results:

Text in the PDF should not be zoomed at all or I should at least be allowed to decrease text size

**Comment by Thorin-Oakenpants** [comment]
100%
![100](https://github.com/user-attachments/assets/61c11a67-b75f-4a95-82c8-1840e9514489)

120%
![120](https://github.com/user-attachments/assets/779ab287-d763-4f6b-8a2a-f84078909ff3)

120% text only
![120 textonly](https://github.com/user-attachments/assets/59725469-f995-4f77-a0de-ac674c1ffc02)

**Comment by Thorin-Oakenpants** [comment]
ESR128 - 120% text only (which looks suspiciously like it's actually at 100% see MB 100% result)

![ESR128](https://github.com/user-attachments/assets/63b0880f-baf6-4aed-99a4-837eed803b76)

**Comment by Thorin-Oakenpants** [comment]
cc @PieroV

**Comment by PieroV** [comment]
I tested a little bit, but it doesn't seem trivial.
I opened https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/43338 on tor-browser.git so that it can be triaged properly.

**Comment by morganava** [comment]
> should be fixed with https://gitlab.torproject.org/tpo/applications/tor-browser/-/merge_requests/1311

Merged, should be available in the early January reelase.
