### ISSUE TITLE
Enable WebAuth for everyone

### ISSUE THREAD

**Issue by MooseExplorer637** [mullvad/mullvad-browser#38]
WebAuth is a critical security feature, and with the passwordless future incoming, its role will only increase, so disabling it by default makes little sense to me. If you enable it for everyone, it shouldn't affect the fingerprint, but currently, when users have to enable it manually, it will make them possibly stand out from the crowd.

**Comment by ruihildt** [comment]
Closing in favor of #53 (conversation is bigger)
