### ISSUE TITLE
Wayland support?

### ISSUE THREAD

**Issue by mumbledenoise** [mullvad/mullvad-browser#39]
My typical tricks to get Wayland support don't seem to work with Mullvad Browser:

1. Start with MOZ_ENABLE_WAYLAND=1 ./mullvadbrowser

2. Disable X11 permissions from the app with Flatseal (doesn't work as Mullvad Browser isn't a Flatpak yet).

Is this not supported yet, or is there another way I can run Mullvad Browser with Wayland enabled? I prefer this as pinch to zoom and other touchpad gestures are only supported when Firefox is run with Wayland.

**Comment by okpersonvern** [comment]
`MOZ_ENABLE_WAYLAND=1 ./start-mullvad-browser --detach`

**Comment by mumbledenoise** [comment]
> `MOZ_ENABLE_WAYLAND=1 ./start-mullvad-browser --detach`

That works!

Surprisingly, my command from #1 works now too, but the detach is a very useful addition. Thanks!
