### ISSUE TITLE
Why keep the 1000x1000 value for privacy.window.maxInner instead of using 900x1600 values like Arkenfox?

### ISSUE THREAD

**Issue by llnngg** [mullvad/mullvad-browser#40]
Also why network.trr.mode is set to 3 instead of 0 if MB is also intended to be used with another VPN providers?

Thank you.

**Comment by Thorin-Oakenpants** [comment]
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/33282 - this is an upstream issue, but MB can easily increase width for usability without, I believe, affecting entropy much if at all - it's just a pref change

Not sure if I would go with 1600 x 900 - to be sure - it needs a little number crunching on aspect ratios vs system scaling vs fuzzy available screen sizes (taskbar/docker sizes and positions)

**Comment by ruihildt** [comment]
We'll be looking into it. 

Anecdotally it's annoying that the https://mullvad.net website shows the mobile menu under the current size. ;)

**Comment by ruihildt** [comment]
> Also why network.trr.mode is set to 3 instead of 0 if MB is also intended to be used with another VPN providers?

It is set to 3, because we recommend to use an encrypted DNS resolver when not using a VPN. As we have no way to know if a Mullvad Browser is using a VPN or not or how their VPN deals with DNS, we defaulted to use Mullvad DoH.

You are of course free to change the value as you see fit.

**Comment by ruihildt** [comment]
This has been fixed with the release of Mullvad Browser 13.0.

See: https://mullvad.net/en/blog/2023/10/13/mullvad-browser-130-released-with-multilingual-support/
