### ISSUE TITLE
Imported NoScript settings revert to default after restart

### ISSUE THREAD

**Issue by nadesco** [mullvad/mullvad-browser#41]
I've tried different settings in the browser and even did a clean reinstall of Mullvad, but imported txt file Options and Permissions are always lost after a restart. On the other hand everything is preserved when the same kind of file is imported into uBlock Origin.

Not sure if it's related but there's a similar problem with _Enable HTTPS-Only in all windows_ mode. That is, any urls added to Exceptions are gone after a restart. I've tried adding them from the addr bar and manually in Manage Exceptions, as I usually do in LibreWolf or Firefox. _Private browsing mode_ and _Site settings / Offline website data_  are disabled in Settings.

Mac OS 12.6

**Comment by Thorin-Oakenpants** [comment]
HTTPS-Only exceptions are session only - by design (site exceptions are not written to disk, they are memory-only and vanish when you exit the app)

As for NoScript, I'll ping @hackademix - this sounds like something recently fixed but may not have made it into the current release

**Comment by hackademix** [comment]
Similarly to what happens in the Tor Browser, NoScript settings are tied to the Security Level and any customization is reset on browser restart.

If you want them to persist, __NoScript Options>Advanced>Override Mullvad Browser's Security Level preset__.

**Comment by nadesco** [comment]
The override setting did it. Thanks for your help, guys.

**Comment by Thorin-Oakenpants** [comment]
> If you want them to persist, NoScript Options>Advanced>Override Mullvad Browser's Security Level preset.

sounds like something for the Mullvad FAQ @ruihildt

**Comment by Thorin-Oakenpants** [comment]
#126 
> sounds like something for the Mullvad FAQ @ruihildt :)

**Comment by ruihildt** [comment]
Indeed, which is why I tagged it with `documentation`. :)
