### ISSUE TITLE
Allow Mullvad Browser to be set as Default Browser

### ISSUE THREAD

**Issue by robinkleem** [mullvad/mullvad-browser#42]
Firstly, thank you for providing an important tool in the ongoing fight for personal privacy.

Due to the current installation method, Mullvad Browser can not easily be set as the default browser for a operating system. That is to say, Mullvad should be the browser that launches when URLs are clicked in applications running on the Operating System.

While the approach required will likely be different from OS to OS, I would imagine that if a viable approach can be found for Linux, Windows and MacOS, it would help with the day to day usage of the browser.

With regards to Linux, if the app was packaged as a Flatpak it would likely be identified by the OS as a acceptable candidate for default browser. In a sense, this is similar to [Issue #6](https://github.com/mullvad/mullvad-browser/issues/6)

Please accept my apologies for clumsy writing as English is not my mother language.

**Comment by Thorin-Oakenpants** [comment]
https://support.torproject.org/tbb/#tbb_tbb-32

speaking from a windows experience - I use firefox portables a lot, and TB of course. These are not installed - they are simply unpacked and the option in the UI does not work (because it points to the firefox.exe and not the wrapper or portable.exe - and you end up creating a new default profile). In order to set a portable as default, you need to hack the registry.

I don't think this is something that will ever be addressed, it's been a known issue upstream since day 1 - for example https://gitlab.torproject.org/legacy/trac/-/issues/12763

**Comment by alltheseas** [comment]
> Due to the current installation method, Mullvad Browser can not easily be set as the default browser for a operating system.

Which OS are you on? 

On MacOS you can easily set as default browser in settings.

**Comment by ruihildt** [comment]
> On MacOS you can easily set as default browser in settings.

macOS is the exception here. 🙂

**Comment by robinkleem** [comment]
> I think you can run `./start-mullvad-browser.desktop --setDefaultBrowser` to set Mullvad Browser as your default browser.

Hi. Thank you for the suggestion. I tried it and it did not work. I am running Linux (specifically Ubuntu 22.04).

**Comment by robinkleem** [comment]
> > Due to the current installation method, Mullvad Browser can not easily be set as the default browser for a operating system.
> 
> Which OS are you on?
> 
> On MacOS you can easily set as default browser in settings.

I am currently running on Ubuntu 22.04.

**Comment by robinkleem** [comment]
> https://support.torproject.org/tbb/#tbb_tbb-32
> 
> speaking from a windows experience - I use firefox portables a lot, and TB of course. These are not installed - they are simply unpacked and the option in the UI does not work (because it points to the firefox.exe and not the wrapper or portable.exe - and you end up creating a new default profile). In order to set a portable as default, you need to hack the registry.
> 
> I don't think this is something that will ever be addressed, it's been a known issue upstream since day 1 - for example https://gitlab.torproject.org/legacy/trac/-/issues/12763

Thank you for the insight. I understand the comments and perspectives of the posts that seek to isolate the browser as much as possible from the primary OS.  However I still think that enabling this functionality would allow for a nice convenience trade-off and a set-and-forget configuration that would allow all future links clicked somewhere in the OS or applications to launch in Mullvad Browser without any thought.

This takes me back to the consideration of packaging Mullvad Browser as a flatpak which would then allow people to self-select the small convenience vs privacy trade-off.

But then of course then there is the need to support multiple package formats which the devs would understandably want to avoid.

No clear solutions, but I still think the ability to enable Mullvad Browser as the default for the OS would be a boon for many.

**Comment by Deviner75** [comment]
> > Hi. Thank you for the suggestion. I tried it and it did not work. I am running Linux (specifically Ubuntu 22.04).
> 
> Try this:
> 
>     1. Open a Terminal and download the latest release for your current user:
>        `cd ~/.local/share && wget https://mullvad.net/en/download/browser/linux64/latest -O mullvad-browser.tar.xz`
> 
>     2. Extract the content of the downloaded file into a `mullvad-browser` folder:
>        `tar -xvf mullvad-browser.tar.xz mullvad-browser`
> 
>     3. Delete the downloaded tar.xz file as you don't need it anymore and enter the extracted folder:
>        `rm mullvad-browser.tar.xz && cd mullvad-browser`
> 
>     4. Launch Mullvad Browser with the `--register-app` flag, this should register Mullvad Browser as a desktop app for the current user:
>        `./start-mullvad-browser.desktop --register-app`

thank you, it works on arch for me

**Comment by iferca** [comment]
I was able to `--register-app` and to set Mullvad browser as default browser in Linux (Pop OS) using something like this: 

`xdg-settings set default-web-browser start-mullvad-browser.desktop`

But the prolem @robinkleem mentioned in the original report regarding not being able to open a link with existing configuration still persist. I can get mullvad browser open when clicking a link, say in the terminal, but the link is not passed to the browser.

Have anyone solved this issue?

**Comment by Victor239** [comment]
> Do you know any alternative to BrokenURL for Linux?

Junction, it's available as a Flatpak. However note it works best with other Flatpak-based browsers, if you use it with non-Flatpak browsers then it'll open the browser but not the webpage itself.

**Comment by piazzai** [comment]
> > Do you know any alternative to BrokenURL for Linux?
> 
> Junction, it's available as a Flatpak. However note it works best with other Flatpak-based browsers, if you use it with non-Flatpak browsers then it'll open the browser but not the webpage itself.

Thanks a lot for the tip. MB is available on Flathub, so I installed it from there and with Junction it works fine (Pop OS 22.04).

**Comment by FeyrisTan** [comment]
Anybody figured this out yet for windows? I can do it when having a second browser installed via regedit. But I don't really need a second browser.

**Comment by Thorin-Oakenpants** [comment]
just right click `html`, `htm`, `pdf` if you want (etc), for each filetype
- choose `open with` > `choose another app`.. `choose an app on your pc` > browse for `path\Mullvad Browser\Browser\mullvadbrowser.exe` , click `always` and be done with it

**Comment by Thorin-Oakenpants** [comment]
> That doesn't fix clicking a url outside of the browser

true :) I actually registered my portable FF as a program, and may have modified reg entries to point to `FirefoxPortable.exe` instead of `firefox.exe` (if you directly start firefox.exe it doesn't know where the profile is and creates a new one - you won't have this problem with mullvad)

TBH, I'm sure exactly what I did on win11. I already had installed firefoxes (nightly, dev) so I may have piggybacked on them

I am not vouching for these links, I already had a `RegisterFirefoxPortable.exe` from many years ago
- yes, I used this on Win 11
- https://www.winhelponline.com/blog/register-firefox-portable-with-default-apps/
- https://portableapps.com/comment/249909#comment-249909
- it's basically just a bunch of reg entries

> I can do it when having a second browser installed via regedit. But I don't really need a second browser.

which means you know how to do it already. Having a secondary browser installed is no big deal IMO :) In fact it's very handy

**Comment by steel-steven-87** [comment]
Has anyone from the team looked into this? I have the same issue. I can't seem to find a way to set this as the default browser in Linux.

**Comment by ruihildt** [comment]
> Has anyone from the team looked into this? I have the same issue. I can't seem to find a way to set this as the default browser in Linux.

This is indeed something we're looking into.

**Comment by ruihildt** [comment]
@AutonomousCat We will do things differently from Tor Browser where that makes sense.

The next major release will contain an updated Search engines list.

**Comment by ruihildt** [comment]
As mentioned previously, this is planned.

**Comment by jaw-sh** [comment]
I'd like to show support for this issue. I am playing with Mullvad after having used Brave or other Chromium forks for years and I am pleasantly surprised to see that FireFox has made their browser considerably faster, more resource efficient.

My biggest problems with it have been that Mullvad is too close to the Tor browser, which is portable and is designed for people whose personal safety may depend on the browser not exposing them or allowing them to be tracked. However, on Mullvad, it has been difficult to turn off some anti-fingerprinting settings which are required to actually use it effectively (such as U2F keys).

Mullvad would benefit from having an installer with two standards of security: "I want a private browser" that is a standard installation ready for work out the box, and "My life depends on it" which is more strict (and honestly you should just be using the Tor browser anyways).

Thanks!

**Comment by ruihildt** [comment]
This is being currently being worked on, you can track progress here: https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/80

**Comment by Hestia-23** [comment]
Hello. Thanks for working on this. I look forward to being able to set Mullvad as my default browser. All the best.

**Comment by ruihildt** [comment]
@Hestia-23 Mullvad Browser 13.5 makes it possible to set the browser as default for Windows / Fedora / Debian / Ubuntu (you could already do it on macOS).
