### ISSUE TITLE
font cache is enabled! 

### ISSUE THREAD

**Issue by flatsponge** [mullvad/mullvad-browser#51]
I have encountered a serious issue with the browser's font cache. It seems that the font cache is enabled by default, which makes the browser vulnerable for State Partitioning tracking. This is a technique that allows websites to abuse stateful APIs (such as cookies and localStorage) for cross-site tracking. By providing different storage locations to every website, trackers can store and retrieve user identifiers across sites. This is a privacy violation and a security risk....

This is weird considering that Tor Browser (TB), which MB is based upon does not have this issue. TB has implemented State Partitioning for its font cache since version 10.0. 

Please fix this issue as soon as possible, as it compromises the privacy and security of the users.
Thank you for your attention and cooperation. ❤️

Source with someone else experiencing this issue : https://privacytests.org
```
write: async (key) => {
let style = document.createElement("style");
style.type-text/css';
let fontURI = testURI("resource", "font", key);
style.innerHTML = @font-face {font-family: "myFont"; src:
url("$ (fontURI)"); } body { font-family: "myFont" }*
document.getElementsByTagName("head")
[0].appendChild(style);
return key;
}
read: async (key) => {
let style = document.createElement"style");
style.type='text/css';
let fontURI = testURI("resource", "font", key);
style.innerHTML = @font-face {font-family: "myFont"; src:
url("$(fontURI)"); } body { font-family: "myFont" }*
document.getElementsByTagName("head")
[0].appendChild (style);
await sleepMs(500);
let response = await fetch(
testURI("ctr", "font", key), {"cache": "reload"});
return (await response.text()).trim();
```

**Comment by Thorin-Oakenpants** [comment]
https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/167
