### ISSUE TITLE
KeePassXC Extension Support

### ISSUE THREAD

**Issue by terminal-root** [mullvad/mullvad-browser#55]
I would like to use the KeePassXC extension, but to use a browser that is not officially supported, I need to know where a directory normally called `native-messaging-hosts` (or something similar) is located. For Firefox, this would normally be `~/.config/mozilla/native-messaging-hosts/`. Where is the equivalent directory for Mullvad?

**Comment by serial02** [comment]
> I would like to use the KeePassXC extension, but to use a browser that is not officially supported, I need to know where a directory normally called `native-messaging-hosts` (or something similar) is located. For Firefox, this would normally be `~/.config/mozilla/native-messaging-hosts/`. Where is the equivalent directory for Mullvad?

Hello @terminal-root 

I'm not part of the Mullvad Browser team and I don't answer for them, but yesterday I had the same problem and I solved it as follows:

Copy all paste ./mozilla to /.local/share/mullvad-browser/Data/
/home/user (Here put your name after home) /.local/share/mullvad-browser/Data/.mozilla/native-messaging-hosts

Here for me it is like this:
KeePassXC-Browser is connected to KeePassXC and has been configured using the following identifier: Mullvad Browser

**Comment by terminal-root** [comment]
Noticed on Windows, after turning on "Firefox and Tor Browser" in KeePassXC on Windows in `Settings > Browser Integration > General`, the extension works without further configuration. Thanks Mullvad Team :)

**Comment by chris02000** [comment]
I just enabled Chromium and it worked.

**Comment by yourmother9** [comment]
i download/install extension from https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/

in "Manage Your Extensions" list its seems te be activated but i can't do nothing.

it does not show up in toolbar. you have that to?

**Comment by terminal-root** [comment]
replying to @yourmother9 - [their comment]

What map are you referring to?

**Comment by terminal-root** [comment]
Update. Running a new install of Artix and this issue is not a problem anymore. Enabling Firefox support makes Mullvad Browser work in my case. It could be that this time I installed from the [AUR](https://aur.archlinux.org/packages/mullvad-browser-bin) instead of a manual install.

![image](https://github.com/mullvad/mullvad-browser/assets/24536673/d5f0cfaf-ecde-45ec-892a-8ca57c6be8a5)
