### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Abyssgrowth** [mullvad/mullvad-browser#58]
According to https://privacytests.org/ the mullvad browser has no tracking protection regarding font cache.
Is that correct or did mullvad handle the font cache tracking in another way that we might be unware of?

Also according to https://privacytests.org/ mullvad fails in all "Tracking query parameter tests".
Could you explain why there is no tracking protection for this cathegory and what are chances to implement this in the future?

![2](https://user-images.githubusercontent.com/125774114/231432052-9416946a-df28-4f60-b5c6-e35114802f7b.PNG)

![1](https://user-images.githubusercontent.com/125774114/231431987-60e1c2ce-3117-4392-a39e-92239e63c433.PNG)

**Comment by ruihildt** [comment]
At least as of Mullvad Browser 13.0, both these issues have been fixed.
