### ISSUE TITLE
Importing bookmarks automatically doesn't show other browsers

### ISSUE THREAD

**Issue by ruihildt** [mullvad/mullvad-browser#67]
`Bookmarks > Manage bookmarks > Import and Backup > Import Data from Another Browser`

results in : `Nor programs that contains (...) could be found`

**Comment by ruihildt** [comment]
> Mint+MATE-21.2: Just downloaded the Linux version and "Import data from another browser" but it does not see FFx. Showed something "Found no other browser..."
> 
> I then used FFx to "Backup" Bookmarks and tried to import that file into Mullvad. Blanks sheet. I moved the file to the Downloads folder, (Desktop can be iffy) same again. In fact, when I select "All Files" I still get a bank screen.
> 
> The Download file dialog shows "JSON" in caps and Linux is strict about Case. Could it be looking for "json" that FFx uses?
> 
> For now, back to FFX -- damn short visit.

**Comment by Denyreal** [comment]
Hi friends
On Fedora 38 

millvad-browser-flatpack 1.0
12.5.3 (based on Mozilla Firefox 102.15.0esr)

Unfortunately i can't import bookmarks exported from firefox (html and json) 

It's the only reason i don't fully migrate to mullvad browser which seems to be a very exciting project.

**Comment by Denyreal** [comment]
My bad it worked. Just had to reorganize the bookmarks.

Now i'm fully mullvad browser ! 

Thanks you mullvad and tor browser

**Comment by ruihildt** [comment]
This is tracked in https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/170

**Comment by ruihildt** [comment]
Importing bookmarks now works correctly since Mullvad Browser 13.5 on all platforms! 🎆
