### ISSUE TITLE
Blurry elements on some websites

### ISSUE THREAD

**Issue by ruihildt** [mullvad/mullvad-browser#75]
Finding several sites to have blurry elements on the Mulvad browser.
MacOS Monterey 12.0.1

Screenshots comparing Office 365 excel on Firefox and Mullvad browser.
![image](https://user-images.githubusercontent.com/13787166/232756809-80da7a28-e419-4702-9f93-dd90fece8011.png)
![image](https://user-images.githubusercontent.com/13787166/232756895-798de24b-2baf-4409-88bc-43f7dd72d99d.png)

Blurry elements in gmail on top and left menu

![image](https://user-images.githubusercontent.com/13787166/232756741-c66f1ef2-702f-46d1-addc-efe97fc1ee99.png)

**Comment by ruihildt** [comment]
> The blur happens because of canvas fingerprinting protections, happens on google docs, nextcloud, etc
> Anywhere that uses canvas rendering which checks the users DPI: basically canvas know its dimensions in 'content space' (so in terms of css pixels) and these apps will set the canvas's real resolution such that it lines up with the real screen space using the provided DPI. Since we spoof DPI these types of renderings will necessarily be blurry (unless your real dpi is the same as the spoofed)

**Comment by Thorin-Oakenpants** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1554751

**Comment by ruihildt** [comment]
@Thorin-Oakenpants looking at this bug report, it seem sit would be worth it to change it to `2` as an experiment.

**Comment by Thorin-Oakenpants** [comment]
yeah, @fxbrit was going to test it (maybe some weird edge cases happen where it affects sizes?) but never got around to it - and then push it on LW (~150k users?) and if success tell upstream

**Comment by Thorin-Oakenpants** [comment]
https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/41740

**Comment by ruihildt** [comment]
> PS: Do you want to be a guinea pig?

I think we're good candidate to test these kind of things.

**Comment by ruihildt** [comment]
We have now added the following FAQ entry to our guides: https://mullvad.net/en/help/tag/mullvad-browser/#114

>  The blur happens because of canvas fingerprinting protection. 
> 
> A canvas element has its dimensions specified in “content space” (in CSS pixels) and to render it properly, the website will ask the browser for the [devicePixelRatio property](https://developer.mozilla.org/en-US/docs/Web/API/Window/devicePixelRatio), which indicates how many of the screen's actual pixels should be used to draw a single CSS pixel.
> 
> When Mullvad Browser spoof the devicePixelRatio property, the canvas based elements can be rendered blurry if your screen's actual devicePixelRatio does not match the spoofed value.

**Comment by ruihildt** [comment]
Implemented in Mullvad Browser 13.0
