### ISSUE TITLE
Rebase to 102.10.0esr

### ISSUE THREAD

**Issue by okpersonvern** [mullvad/mullvad-browser#77]
Consider prioritizing the upgrade to [Firefox 102.10.0esr,](https://www.mozilla.org/en-US/firefox/102.10.0/releasenotes/) released on April 11, containing various security fixes.

**Comment by ruihildt** [comment]
This is already planned, but there's no ETA for this work.

You can follow the upstream issue here: https://gitlab.torproject.org/tpo/applications/mullvad-browser/-/issues/169

**Comment by felschr** [comment]
Looks like that issue is related to the 12.5 alpha branch, so I'm assuming we won't get a 12.0.5 release with Firefox 102.10.0esr like Tor Browser released on 2023-04-19?

What's the plan for the future regarding releases and versioning? Do you plan to release alongside Tor with same version numbers or will you deviate from it in the future?
What's the strategy for delivering security updates in a timely manner?

**Comment by ruihildt** [comment]
> Looks like that issue is related to the 12.5 alpha branch, so I'm assuming we won't get a 12.0.5 release with Firefox 102.10.0esr like Tor Browser released on 2023-04-19?

12.0.5 will be based on `102.10.0esr` as well. I just checked the pre-release version used for internal testing to confirm it.

> What's the plan for the future regarding releases and versioning? Do you plan to release alongside Tor Browser with same version numbers or will you deviate from it in the future?

The plan is to update Mullvad Browser right after Tor Browser (which has priority). There's no plan to deviate the version number as we are based on the same base.

The way it currently works is that there's a `base-browser` branch which contains all the patches common to Tor Browser and Mullvad Browser. Tor Browser / Mullvad Browser then apply their specific patches on top of that branch.

> What's the strategy for delivering security updates in a timely manner?
Same as Tor Browser. It is the same developers that are releasing both browsers.

**Comment by pospeselr** [comment]
In the future for folks following at home, you can use this gitlab link to track our Mullvad Browser release pep:

- https://gitlab.torproject.org/groups/tpo/applications/-/issues/?search=Mullvad&state=opened&label_name[]=Release%20Prep

**Comment by ruihildt** [comment]
Fixed in [Mullvad 12.0.5](https://github.com/mullvad/mullvad-browser/releases/tag/mullvad-browser-102.10.0esr-12.0-2-build2)
