### ISSUE TITLE
[General/Question] canvas, screen width/height, fonts, navigator properties, screen available width/height, audio data

### ISSUE THREAD

**Issue by nsde** [mullvad/mullvad-browser#78]
Hello, I'd like to ask a question here.
I'm concerned about the actual anonymity of this browser.

A test on
https://amiunique.org/fp
gave me these results:
![image](https://user-images.githubusercontent.com/67185896/233672101-741d025a-b8e6-415f-ba76-f702ff11d5d8.png)

Which is a much worse result than on `ungoogled-chromium`:
![image](https://user-images.githubusercontent.com/67185896/233672936-c0bfee83-0718-44ac-9a5a-c52ea7406fc3.png)

Are these issues planned to be addressed?

**Comment by Thorin-Oakenpants** [comment]
please stop using entropy figures from these sites - the figures are NONSENSE - see https://github.com/mullvad/mullvad-browser/issues/5#issuecomment-1495230655

All these except audio are already addressed, and audio entropy in gecko is extremely low to start with, and is currently being "fixed" upstream at Mozilla

**Comment by nsde** [comment]
Okay, thank you!
