### ISSUE TITLE
Tabs below Address bar

### ISSUE THREAD

**Issue by Aiecea** [mullvad/mullvad-browser#79]
Hi, 
Not sure if this goes under "issues"!
I've been testing the browser and would like to use it. However, I know it might seem trivial to some people, but judging from what I've read about other alternatives to FF a lot of pppl seem to want this, It's practically one of the only reasons I'm still using FF. I would really like to have my tabs below the address bar (see attached). Is this feature available to users in the Mullvad browser, the ability to change the settings?
![grafik](https://user-images.githubusercontent.com/75490555/233781136-c2b05908-64f6-45e8-9e7f-dab2b5d8ed70.png)
Thanks.

**Comment by Thorin-Oakenpants** [comment]
This is beyond the scope of TB or MB's mission, If you want this UI feature, petition Mozilla - and they will tell you that you can use userChrome.css - which is unofficial and not supported (and css naming may change, it's up to you to maintain it), as has been the case for the last decade...

**Comment by ruihildt** [comment]
Not planned, see @Thorin-Oakenpants comment.
