### ISSUE TITLE
uBlock Origin filter lists not enabled

### ISSUE THREAD

**Issue by ave9858** [mullvad/mullvad-browser#8]
The [hard facts](https://mullvad.net/en/browser/hard-facts) page says that Adguard URL Tracking Protection and EasyList Cookie have been enabled in uBlock Origin, but looking in the config for ublock origin shows that these lists are not enabled. Cookie banners are not blocked until that list is manually enabled.

Edit: This was tested using the Windows version of the browser.

**Comment by ruihildt** [comment]
Thanks for your report, we'll look into this.

**Comment by ruihildt** [comment]
Fixed by https://github.com/mullvad/mullvad-browser/releases/tag/mullvad-browser-102.10.0esr-12.0-2-build2
