### ISSUE TITLE
the DNS of mullvad-browser is broken!!

### ISSUE THREAD

**Issue by a-recent-converter-to-mullvadianism** [mullvad/mullvad-browser#80]
had to turn off https dns of mullvad for the browser to work, pls fix it as i like using thatover anything, thx

**Comment by GlowingUmbreon** [comment]
What happens if you set `network.trr.bootstrapAddress` in `about:config` to `194.242.2.2` and re-enable dns over HTTP with the default server enabked. Does this resolved your issue?

**Comment by a-recent-converter-to-mullvadianism** [comment]
I will try it next time as it seems to have resolved itself or was fixed, thx for the info tho, will keep it in mind

**Comment by yanagibashi-mt** [comment]
There was an issue with Mullvad public DNS servers on Sunday, I also noticed this outside the Mullvad Browser just with regular DoH clients like dnscrypt-proxy2 or manually querying. In my testing, the domain resolved successfully but the server didn't answer at all, so @GlowingUmbreon 's suggestion would not have helped. Unfortunately I wasn't able to find a status page on this service or any news about the outage. Seeing as this is a preset setting in the Mullvad Browser and there will probably be a considerable amount of users getting affected just like @a-recent-converter-to-mullvadianism when using the browser during an outage, it would be nice to hear more from Mullvad about this incident.
