### ISSUE TITLE
Uploading images via Mullvad browser makes them unrecognizable

### ISSUE THREAD

**Issue by ProPatte** [mullvad/mullvad-browser#81]
Uploading images on any website via Mullvad browser makes images unrecognizable. Websites I tried are Instagram, eBay, Twitter and others. Works without issues with other browsers.

OS: Windows 11
Mullvad Browser Version: 12.0.4

Example on eBay:
![Screenshot 2023-04-24 130711](https://user-images.githubusercontent.com/18471911/233980223-6e16b9f5-c56f-4ab6-ba90-99557c18e7a2.jpg)

Twitter:
![Screenshot 2023-04-24 131624](https://user-images.githubusercontent.com/18471911/233981158-4023eebd-e866-45b8-9e3e-65696a8fbae5.jpg)

**Comment by ProPatte** [comment]
How it looks like uploading it with Mullvad browser:
![Screenshot 2023-04-24 130711](https://user-images.githubusercontent.com/18471911/233980433-ebcaf535-fb09-42e0-9b53-cebdecaf0675.jpg)

**Comment by Thorin-Oakenpants** [comment]
whilst on the site, click the canvas exception (this is browser session only in MB)
- here's the steps and a pic - https://github.com/arkenfox/user.js/wiki/3.3-Overrides-[To-RFP-or-Not]#-rfp - the bit about canvas

**Comment by ProPatte** [comment]
> whilst on the site, click the canvas exception (this is browser session only in MB)
> 
>     * here's the steps and a pic - [https://github.com/arkenfox/user.js/wiki/3.3-Overrides-[To-RFP-or-Not]#-rfp](https://github.com/arkenfox/user.js/wiki/3.3-Overrides-%5BTo-RFP-or-Not%5D#-rfp) - the bit about canvas

That works. Thank you <3

**Comment by LinuxOnTheDesktop** [comment]
I think that the page you mean to link is [this one](https://github.com/arkenfox/user.js/wiki/3.3-Overrides-%5BTo-RFP-or-Not%5D) - and that the part of the page at issue is the section headed, 'BREAKAGE'. That section tells one how to set a permanent per-site override. I presume that somehow security would be weakened were the feature somehow to be disabled for all sites.

1) _Surely this breakage needs to be advertised_ to users of Mullvad-Browser.

2) 2a) _The webpage at issue makes it somewhat hard to see how one should start to set a (temporary or permanent) per-site exception_ - but, in short: press `ctrl-i`. 2b) So far as I can see, _the page does not actually inform the user as to what to do with the following resultant list of options_ (and note also that one must selected the 'permissions' tab).

![image](https://user-images.githubusercontent.com/47056543/235362259-d6b31438-40d5-4d39-b0fa-a13d142a0168.png)

**Comment by Thorin-Oakenpants** [comment]
> I presume that somehow security would be weakened were the feature somehow to be disabled for all sites

There is no means for MB users to disable canvas protection globally (excluding disabling RFP itself)

TB/MB/FFusers-with-RFP all need those canvas unbreaking steps _somewhere_. It is not, repeat NOT, a security issue. It is a FPing issue. It's a bit more nuanced than just saying what I said on the wiki page as below

> Assuming it is even fingerprinting and the exact same canvas test is widespread, this does not compromise your fingerprint - it is a single metric and only on those sites you exempt.

There are/may be issued with cascading "permissions" - e.g 3rd party iframes (I would need to check), and then if you have logged into a site and you exempt, it may still not be your real ID, and there are cases where it ids prudent to still spoof. It may be possible in the future to subtly randomize if exempted

PS: the best method to indicate canvas as a possible issue, and to control it, is the canvas icon in the urlbar - as per my pic on the wiki

**Comment by LinuxOnTheDesktop** [comment]
@Thorin-Oakenpants: there is a danger that your comments, which are of a technical nature, will obscure the points of mine that I numbered '1' and '2' respectively. Those points summarise thusly: _the Mullvad Browser needs to tell users about this breakage and to advise them - clearly and succinctly - what they might do about it._

**Comment by Thorin-Oakenpants** [comment]
This is a closed issue ... and has now for some reason evolved into is a discussion about how to inform users - not the actual info that will be presented. Mullvad already knows, and will be improving the faq

My first point was to correct you on the issue of security. The second was to once again, show the simplest method (urlbar canvas icon) as it is 1) an instant visual check/clue and 2) a faster method to toggle. All the rest is for other readers. As someone who has been working with Tor Uplift, TB, MB, etc - for many years - including UX - I don't need to be educated on this subject thank you

**Comment by ruihildt** [comment]
@LinuxOnTheDesktop  Canvas breakages are hard to reliably communicate to the users, as the behavior of the notifications depends on multiple factor.

In general, we're looking into improving the user experience, but it will be a long process.

**Comment by LinuxOnTheDesktop** [comment]
@ruihildt

Right. Still, the browser, or some release notes, or a download page, or similar, could tell the prospective user that X, Y and Z might be broken.

**Comment by ruihildt** [comment]
You're right, and we will continue updating our FAQ based on your and other user's feedback.
