### ISSUE TITLE
Flatpak version

### ISSUE THREAD

**Issue by jvillasante** [mullvad/mullvad-browser#83]
I see there's a Flatpak version on [Flathub](https://flathub.org/apps/net.mullvad.MullvadBrowser)

Is that official and safe to use?
Are there plans to keep it up to date with the latest version from the Mullvad download site?

**Comment by ruihildt** [comment]
> Is that official and safe to use?

This is not an official release and we haven't verified it.
We are currently considering how to best handle this.
