### ISSUE TITLE
Unable to auto update to 12.0.5 (Windows)

### ISSUE THREAD

**Issue by Disrooting** [mullvad/mullvad-browser#84]
I would like to address that there is an issue with the automatic update built-in, it keeps redirecting me to download the latest version from the website, even though i've already clicked the download button, until it says: Mullvad Browser couldn't update automatically.

**Comment by ruihildt** [comment]
Thanks, I can confirm we're in the process of fixing this bug.

We rely on the same script for auto-update and displaying download options on the website: unfortunately, trying to fix one broke the other.

**Comment by ruihildt** [comment]
@Disrooting Updating should work know. (and reversely, the download button on the website is now broken)

**Comment by Disrooting** [comment]
i can confirm that i got an "update & restart" prompt now and it updated to the latest version. thank you guys
