### ISSUE TITLE
Downloading Mullvad Browser 12.0.5 for Windows ends up in error (404)

### ISSUE THREAD

**Issue by Smokemic** [mullvad/mullvad-browser#85]
[Webaufnahme_5-5-2023_19144_cdn mullvad net](https://user-images.githubusercontent.com/97992936/236521051-d6b78198-d109-4639-a1e3-20f93e0118c0.jpeg)

Not Found!

The requested URL was not found on this server

**Comment by ruihildt** [comment]
This is a known issue, we're looking into it and will deploy a fix as soon as possible.

In the meantime, you can download [Mullvad Browser 12.0.4](https://cdn.mullvad.net/browser/12.0.4/mullvadbrowser-install-win64-12.0.4_ALL.exe) ([signature](https://cdn.mullvad.net/browser/12.0.4/mullvadbrowser-install-win64-12.0.4_ALL.exe.asc)) and it will auto-update after launch.

**Comment by ruihildt** [comment]
This is (somewhat) fixed.

If you now click on the download link, you will download Mullvad Browser 12.0.4.
It will then get auto-updated to the latest version when you launch it.
