### ISSUE TITLE
I can't use Mullvad browser with AdGuard, pls fix it.

### ISSUE THREAD

**Issue by ruihildt** [mullvad/mullvad-browser#87]
I can't use Mullvad browser with AdGuard, pls fix it.

_Originally posted by @wft44maqb in https://github.com/mullvad/mullvad-browser/issues/76#issuecomment-1527220134_

**Comment by ruihildt** [comment]
@wft44maqb Can you give more info?

**Comment by gsture** [comment]
Mullvad comes with ublock as default adblocker. It's not advisable to install other plugins because it makes you stand out from the crowd and makes tracking you easier. It defeats the purpose of the mullvad browser.

**Comment by iam-py-test** [comment]
I think the OP wants to use Mullvad with the AdGuard application, but could be wrong.

**Comment by ruihildt** [comment]
Closing this as this wasn't opened by a user and we haven't heard back from them.

Feel free to re-open if needed.
