### ISSUE TITLE
Add arm64 support for Linux Raspberry Pi users

### ISSUE THREAD

**Issue by andyinthevalley** [mullvad/mullvad-browser#90]
Both Firefox and Mullvad VPN work perfectly on arm64 on Ubuntu 64 bit.

It would be great if the Mullvad browser also worked there.

**Comment by simonrolfmore** [comment]
Also useful for Asahi Linux on ARM Macs, now [Fedora Asahi Remix](https://asahilinux.org/fedora/?ref=upstract.com) is out :)

**Comment by ruihildt** [comment]
Belatedly closing this as a duplicate of #11
