### ISSUE TITLE
Select a different language

### ISSUE THREAD

**Issue by KatyPurry** [mullvad/mullvad-browser#93]
Hello,

During the installation I chose French but Mullvad seems to stay in English and I can't add an extra language. (v12.0.6)

![image](https://github.com/mullvad/mullvad-browser/assets/89610869/58569d3c-461d-4dcc-b426-1d775792eefa)

Is it intendend ?

Thank you

**Comment by ruihildt** [comment]
@KatyPurry For now Mullvad Browser is only availabl ein English. But we're planning to add support for French (and other languages) in the next major version.

**Comment by ruihildt** [comment]
Mullvad Browser 13.0 is now available, and in multiple languages.

See the blog post: https://mullvad.net/en/blog/2023/10/13/mullvad-browser-130-released-with-multilingual-support/
