### ISSUE TITLE
Does not build with current (stable) rust 1.70.0

### ISSUE THREAD

**Issue by eclairevoyant** [mullvad/mullvad-browser#94]
See mozilla/mp4parse-rust#406 for build errors. 

The minimum version of `mp4parse` needs to be 0.16.0 to include the fix (https://github.com/mozilla/mp4parse-rust/commit/8b5b652d38e007e736bb442ccd5aa5ed699db100) but is currently [pinned to 0.13.0](https://github.com/mullvad/mullvad-browser/blob/mullvad-browser-102.12.0esr-12.0-1-build1/Cargo.lock#L3407-L3435).

**Comment by PieroV** [comment]
Hi @eclairevoyant.
Mullvad Browser 12.0 is based on Firefox 102 ESR, which is compiled with Rust 1.60.0. (`taskcluster/ci/fetch/toolchains.yml` also references 1.61.0 now, but I think the actual builds are still made with 1.60.0 also on Mozilla's side).
Rust 1.69.0 should work, too, and I'm currently on 1.68.2 for my dev builds.
Maybe you could open [a bug upstream](https://bugzilla.mozilla.org), but we are not going to update dependencies unless upstream does.
For this release, you'll need to install an older Rustc version.

**Comment by ruihildt** [comment]
@eclairevoyant With Mullvad Browser 12.5.1, it will be possible to use  Rust 1.69.

See: https://bugzilla.mozilla.org/show_bug.cgi?id=1840323
