### ISSUE TITLE
Disrupted sound in video call (BBB)

### ISSUE THREAD

**Issue by RhizomaticNomad** [mullvad/mullvad-browser#95]
While i.e. with chromium the sound (and video) in a video call works flawlessly, it unfortunately gets disrupted in mullvad-browser. The video works fine, but if you speak (already in the mic setup test of big blue button) the sound gets interrupted and makes mullvad-browser unusable for a video conference. The underlying OS is Arch Linux.

**Comment by RhizomaticNomad** [comment]
@ruihildt I don't know which version of MB I was using when I've opened this bug report. I've checked now again with the 13.0.1-1 version and the problem seems to be solved, as I was able to do a call via BigBlueButton without the interrupted sound.

**Comment by Thorin-Oakenpants** [comment]
> but that is also not working with Firefox (with arkenfox settings)

I assume with RFP enabled - so same base (mostly) as MB. Sounds like webgl. In FF with arkenfox, if you flip `webgl.disabled` to `false` in about:config and test again, it would help pinpoint it as an issue in BBB
