### ISSUE TITLE
Detected as virus after installing update / McAfee Total Protection

### ISSUE THREAD

**Issue by gracie95** [mullvad/mullvad-browser#98]
![Screenshot 2023-06-15 234944](https://github.com/mullvad/mullvad-browser/assets/107738923/3f93a40c-f070-407d-b1fa-c4b5a96316e0)

With the kind threat as shown at picture.

**Comment by iam-py-test** [comment]
What EDR/antimalware is detecting this?
IMO you need to report a false positive to *them*

**Comment by gracie95** [comment]
McAfee Total Protection.


Jun 16, 2023, 06:34 by ***@***.***:

**Comment by iam-py-test** [comment]
Report a FP to them: https://www.mcafee.com/support/?articleId=TS103032&page=shell&shell=article-view
Thanks

**Comment by ruihildt** [comment]
Thanks for the report @gracie95.

Can you confirm you updated Mullvad Browser from 12.0.6 to 12.0.7?

I have submitted a dispute to the McAffee with a link to this issue, using the following form: https://www.mcafee.com/en-us/consumer-support/dispute-detection-allowlisting.html

**Comment by gracie95** [comment]
Yes. That version I got problem.



Jun 16, 2023, 17:15 by ***@***.***:

**Comment by gracie95** [comment]
Still same. Tested to latest version.

![Screenshot 2023-06-29 122450](https://github.com/mullvad/mullvad-browser/assets/107738923/52902324-b87e-4e09-ade2-08f0a93c85f8)

**Comment by ruihildt** [comment]
Unfortunately, McAffee hasn't replied to my submission.

**Comment by ruihildt** [comment]
> I've been having issues using the mullvad browser and I finally found out my anti-virus (McAfee) was quarantining the browser whenever I tried to launch it because it saw it as a threat. This the threat name I get whenever I try and use the application (t!619F0A2B143A). Is there any guidance you can provide? I can't seem to find the corresponding threat for this.

**Comment by ruihildt** [comment]
It hasn't been reported, so I will close. But as these come up periodically, there's not much we can do, especially when antivirus vendors are not responding,
